# A355119: a(n) is the number of n-th order magic triangles composed of the numbers from 1 to n(n+1)/2 which the sum of k-th row and (n-k+1)-th row is same for all k and all three directions, counted up to rotations and reflections.

In [1]:
import itertools
import numpy as np

## Firstly, arrange central six numbers to calculate a(5)

In [2]:
i=0
sum3=24
for A in itertools.combinations(range(1,16), 6):
    for B in itertools.permutations(A,6):
        if B[0]>B[2] and B[2]>B[4]:
            if B[0]+B[1]+B[2]==sum3 and B[0]+B[5]+B[4]==sum3 and B[2]+B[3]+B[4]==sum3:
                print(B)
                i+=1
print(i)

(12, 1, 11, 3, 10, 2)
(13, 1, 10, 5, 9, 2)
(14, 1, 9, 7, 8, 2)
(15, 1, 8, 9, 7, 2)
(15, 1, 8, 14, 2, 7)
(14, 1, 9, 13, 2, 8)
(14, 2, 8, 15, 1, 9)
(13, 1, 10, 12, 2, 9)
(13, 2, 9, 14, 1, 10)
(12, 2, 10, 13, 1, 11)
(12, 1, 11, 4, 9, 3)
(13, 1, 10, 6, 8, 3)
(15, 1, 8, 10, 6, 3)
(15, 1, 8, 13, 3, 6)
(14, 1, 9, 8, 7, 3)
(14, 1, 9, 12, 3, 7)
(13, 1, 10, 11, 3, 8)
(13, 3, 8, 15, 1, 10)
(12, 1, 11, 10, 3, 9)
(12, 3, 9, 14, 1, 11)
(11, 3, 10, 13, 1, 12)
(12, 1, 11, 5, 8, 4)
(15, 1, 8, 11, 5, 4)
(15, 1, 8, 12, 4, 5)
(14, 1, 9, 11, 4, 6)
(12, 1, 11, 9, 4, 8)
(12, 4, 8, 15, 1, 11)
(11, 4, 9, 14, 1, 12)
(12, 1, 11, 6, 7, 5)
(13, 1, 10, 8, 6, 5)
(13, 1, 10, 9, 5, 6)
(12, 1, 11, 8, 5, 7)
(11, 5, 8, 15, 1, 12)
(10, 5, 9, 14, 1, 13)
(10, 6, 8, 15, 1, 13)
(9, 7, 8, 15, 1, 14)
(12, 2, 10, 5, 9, 3)
(15, 2, 7, 11, 6, 3)
(15, 2, 7, 14, 3, 6)
(13, 2, 9, 7, 8, 3)
(14, 2, 8, 9, 7, 3)
(14, 2, 8, 13, 3, 7)
(14, 3, 7, 15, 2, 8)
(13, 2, 9, 12, 3, 8)
(13, 3, 8, 14, 2, 9)
(12, 2, 10, 11, 3, 9)
(12, 3, 9, 13, 2, 10)


In [3]:
# 0 1 2
# 5 3
#  4

In [4]:
i=0
sum3=24
for A in itertools.combinations(range(1,16), 6):
    for B in itertools.permutations(A,6):
        if B[0]>B[2] and B[2]>B[4]:
            if B[0]+B[1]+B[2]==sum3 and B[0]+B[5]+B[4]==sum3 and B[2]+B[3]+B[4]==sum3:
                print(B,np.sum(B))
                i+=1
print(i)

(12, 1, 11, 3, 10, 2) 39
(13, 1, 10, 5, 9, 2) 40
(14, 1, 9, 7, 8, 2) 41
(15, 1, 8, 9, 7, 2) 42
(15, 1, 8, 14, 2, 7) 47
(14, 1, 9, 13, 2, 8) 47
(14, 2, 8, 15, 1, 9) 49
(13, 1, 10, 12, 2, 9) 47
(13, 2, 9, 14, 1, 10) 49
(12, 2, 10, 13, 1, 11) 49
(12, 1, 11, 4, 9, 3) 40
(13, 1, 10, 6, 8, 3) 41
(15, 1, 8, 10, 6, 3) 43
(15, 1, 8, 13, 3, 6) 46
(14, 1, 9, 8, 7, 3) 42
(14, 1, 9, 12, 3, 7) 46
(13, 1, 10, 11, 3, 8) 46
(13, 3, 8, 15, 1, 10) 50
(12, 1, 11, 10, 3, 9) 46
(12, 3, 9, 14, 1, 11) 50
(11, 3, 10, 13, 1, 12) 50
(12, 1, 11, 5, 8, 4) 41
(15, 1, 8, 11, 5, 4) 44
(15, 1, 8, 12, 4, 5) 45
(14, 1, 9, 11, 4, 6) 45
(12, 1, 11, 9, 4, 8) 45
(12, 4, 8, 15, 1, 11) 51
(11, 4, 9, 14, 1, 12) 51
(12, 1, 11, 6, 7, 5) 42
(13, 1, 10, 8, 6, 5) 43
(13, 1, 10, 9, 5, 6) 44
(12, 1, 11, 8, 5, 7) 44
(11, 5, 8, 15, 1, 12) 52
(10, 5, 9, 14, 1, 13) 52
(10, 6, 8, 15, 1, 13) 53
(9, 7, 8, 15, 1, 14) 54
(12, 2, 10, 5, 9, 3) 41
(15, 2, 7, 11, 6, 3) 44
(15, 2, 7, 14, 3, 6) 47
(13, 2, 9, 7, 8, 3) 42
(14, 2, 8, 9, 7, 3) 43
(14, 

In [5]:
i=0
Bs=np.zeros([134,6],dtype=int)
sum3=24
for A in itertools.combinations(range(1,16), 6):
    for B in itertools.permutations(A,6):
        if B[0]>B[2] and B[2]>B[4]:
            if B[0]+B[1]+B[2]==sum3 and B[0]+B[5]+B[4]==sum3 and B[2]+B[3]+B[4]==sum3:
                Bs[i,:]=B
                print(B,np.sum(B))
                i+=1
print(i)

(12, 1, 11, 3, 10, 2) 39
(13, 1, 10, 5, 9, 2) 40
(14, 1, 9, 7, 8, 2) 41
(15, 1, 8, 9, 7, 2) 42
(15, 1, 8, 14, 2, 7) 47
(14, 1, 9, 13, 2, 8) 47
(14, 2, 8, 15, 1, 9) 49
(13, 1, 10, 12, 2, 9) 47
(13, 2, 9, 14, 1, 10) 49
(12, 2, 10, 13, 1, 11) 49
(12, 1, 11, 4, 9, 3) 40
(13, 1, 10, 6, 8, 3) 41
(15, 1, 8, 10, 6, 3) 43
(15, 1, 8, 13, 3, 6) 46
(14, 1, 9, 8, 7, 3) 42
(14, 1, 9, 12, 3, 7) 46
(13, 1, 10, 11, 3, 8) 46
(13, 3, 8, 15, 1, 10) 50
(12, 1, 11, 10, 3, 9) 46
(12, 3, 9, 14, 1, 11) 50
(11, 3, 10, 13, 1, 12) 50
(12, 1, 11, 5, 8, 4) 41
(15, 1, 8, 11, 5, 4) 44
(15, 1, 8, 12, 4, 5) 45
(14, 1, 9, 11, 4, 6) 45
(12, 1, 11, 9, 4, 8) 45
(12, 4, 8, 15, 1, 11) 51
(11, 4, 9, 14, 1, 12) 51
(12, 1, 11, 6, 7, 5) 42
(13, 1, 10, 8, 6, 5) 43
(13, 1, 10, 9, 5, 6) 44
(12, 1, 11, 8, 5, 7) 44
(11, 5, 8, 15, 1, 12) 52
(10, 5, 9, 14, 1, 13) 52
(10, 6, 8, 15, 1, 13) 53
(9, 7, 8, 15, 1, 14) 54
(12, 2, 10, 5, 9, 3) 41
(15, 2, 7, 11, 6, 3) 44
(15, 2, 7, 14, 3, 6) 47
(13, 2, 9, 7, 8, 3) 42
(14, 2, 8, 9, 7, 3) 43
(14, 

In [6]:
sum6=sum3*2
i=0
for k in range(134):
    B=Bs[k,:]
    set9=set(range(1,16))-set(B)
    for C in itertools.permutations(set9,6):
        if C[0]+C[1]+C[5]+B[5]+B[3]+C[2]==sum6:
            if C[0]+B[1]+C[3]+B[3]+C[5]+C[4]==sum6:
                if C[1]+B[1]+B[5]+C[4]+C[3]+C[2]==sum6:
                    if C[0]+B[0]+C[5]==C[4]+B[4]+C[3]:
                        if C[4]+B[4]+C[3]==C[1]+B[2]+C[2]:
                            i+=1
print(i)

1264


In [7]:
#     D2
#    C0 C1
#   B0 B1 B2
# C5 B5 B3 C2
#D0 C4 B4 C3 D1

In [8]:
sum6=sum3*2
i=0
for k in range(134):
    B=Bs[k,:]
    set9=set(range(1,16))-set(B)
    for C in itertools.permutations(set9,6):
        if C[0]+C[1]+C[5]+B[5]+B[3]+C[2]==sum6:
            if C[0]+B[1]+C[3]+B[3]+C[5]+C[4]==sum6:
                if C[1]+B[1]+B[5]+C[4]+C[3]+C[2]==sum6:
                    if C[0]+B[0]+C[5]==C[4]+B[4]+C[3]:
                        if C[4]+B[4]+C[3]==C[1]+B[2]+C[2]:
                            set3=set9-set(C)
                            print(B,C,set3)
                            i+=1
print(i)

[12  1 11  3 10  2] (7, 9, 13, 8, 15, 14) {4, 5, 6}
[12  1 11  3 10  2] (7, 9, 13, 15, 8, 14) {4, 5, 6}
[12  1 11  3 10  2] (7, 13, 9, 8, 15, 14) {4, 5, 6}
[12  1 11  3 10  2] (7, 13, 9, 15, 8, 14) {4, 5, 6}
[12  1 11  3 10  2] (8, 7, 15, 9, 14, 13) {4, 5, 6}
[12  1 11  3 10  2] (8, 7, 15, 14, 9, 13) {4, 5, 6}
[12  1 11  3 10  2] (8, 15, 7, 9, 14, 13) {4, 5, 6}
[12  1 11  3 10  2] (8, 15, 7, 14, 9, 13) {4, 5, 6}
[12  1 11  3 10  2] (13, 7, 15, 9, 14, 8) {4, 5, 6}
[12  1 11  3 10  2] (13, 7, 15, 14, 9, 8) {4, 5, 6}
[12  1 11  3 10  2] (13, 15, 7, 9, 14, 8) {4, 5, 6}
[12  1 11  3 10  2] (13, 15, 7, 14, 9, 8) {4, 5, 6}
[12  1 11  3 10  2] (14, 9, 13, 8, 15, 7) {4, 5, 6}
[12  1 11  3 10  2] (14, 9, 13, 15, 8, 7) {4, 5, 6}
[12  1 11  3 10  2] (14, 13, 9, 8, 15, 7) {4, 5, 6}
[12  1 11  3 10  2] (14, 13, 9, 15, 8, 7) {4, 5, 6}
[13  1 10  5  9  2] (4, 8, 14, 11, 12, 15) {3, 6, 7}
[13  1 10  5  9  2] (4, 8, 14, 12, 11, 15) {3, 6, 7}
[13  1 10  5  9  2] (4, 14, 8, 11, 12, 15) {3, 6, 7}
[13  1 10

[11  3 10 13  1 12] (2, 4, 8, 6, 15, 9) {5, 14, 7}
[11  3 10 13  1 12] (2, 4, 8, 7, 14, 9) {5, 6, 15}
[11  3 10 13  1 12] (2, 4, 8, 14, 7, 9) {5, 6, 15}
[11  3 10 13  1 12] (2, 4, 8, 15, 6, 9) {5, 14, 7}
[11  3 10 13  1 12] (2, 5, 7, 6, 15, 9) {8, 4, 14}
[11  3 10 13  1 12] (2, 5, 7, 15, 6, 9) {8, 4, 14}
[11  3 10 13  1 12] (2, 7, 5, 6, 15, 9) {8, 4, 14}
[11  3 10 13  1 12] (2, 7, 5, 15, 6, 9) {8, 4, 14}
[11  3 10 13  1 12] (2, 8, 4, 6, 15, 9) {5, 14, 7}
[11  3 10 13  1 12] (2, 8, 4, 7, 14, 9) {5, 6, 15}
[11  3 10 13  1 12] (2, 8, 4, 14, 7, 9) {5, 6, 15}
[11  3 10 13  1 12] (2, 8, 4, 15, 6, 9) {5, 14, 7}
[11  3 10 13  1 12] (5, 4, 8, 7, 14, 6) {9, 2, 15}
[11  3 10 13  1 12] (5, 4, 8, 14, 7, 6) {9, 2, 15}
[11  3 10 13  1 12] (5, 8, 4, 7, 14, 6) {9, 2, 15}
[11  3 10 13  1 12] (5, 8, 4, 14, 7, 6) {9, 2, 15}
[11  3 10 13  1 12] (6, 4, 8, 7, 14, 5) {9, 2, 15}
[11  3 10 13  1 12] (6, 4, 8, 14, 7, 5) {9, 2, 15}
[11  3 10 13  1 12] (6, 8, 4, 7, 14, 5) {9, 2, 15}
[11  3 10 13  1 12] (6, 8, 4, 1

[10  6  8 15  1 13] (4, 2, 9, 7, 11, 5) {3, 12, 14}
[10  6  8 15  1 13] (4, 2, 9, 11, 7, 5) {3, 12, 14}
[10  6  8 15  1 13] (4, 9, 2, 7, 11, 5) {3, 12, 14}
[10  6  8 15  1 13] (4, 9, 2, 11, 7, 5) {3, 12, 14}
[10  6  8 15  1 13] (5, 2, 9, 7, 11, 4) {3, 12, 14}
[10  6  8 15  1 13] (5, 2, 9, 11, 7, 4) {3, 12, 14}
[10  6  8 15  1 13] (5, 9, 2, 7, 11, 4) {3, 12, 14}
[10  6  8 15  1 13] (5, 9, 2, 11, 7, 4) {3, 12, 14}
[15  2  7 11  6  3] (4, 8, 13, 10, 12, 9) {1, 5, 14}
[15  2  7 11  6  3] (4, 8, 13, 12, 10, 9) {1, 5, 14}
[15  2  7 11  6  3] (4, 13, 8, 10, 12, 9) {1, 5, 14}
[15  2  7 11  6  3] (4, 13, 8, 12, 10, 9) {1, 5, 14}
[15  2  7 11  6  3] (9, 8, 13, 10, 12, 4) {1, 5, 14}
[15  2  7 11  6  3] (9, 8, 13, 12, 10, 4) {1, 5, 14}
[15  2  7 11  6  3] (9, 13, 8, 10, 12, 4) {1, 5, 14}
[15  2  7 11  6  3] (9, 13, 8, 12, 10, 4) {1, 5, 14}
[15  2  7 14  3  6] (1, 5, 13, 10, 12, 9) {8, 11, 4}
[15  2  7 14  3  6] (1, 5, 13, 12, 10, 9) {8, 11, 4}
[15  2  7 14  3  6] (1, 13, 5, 10, 12, 9) {8, 11, 4}
[

[13  4  7 15  2  9] (8, 5, 10, 6, 14, 1) {11, 3, 12}
[13  4  7 15  2  9] (8, 5, 10, 14, 6, 1) {11, 3, 12}
[13  4  7 15  2  9] (8, 10, 5, 6, 14, 1) {11, 3, 12}
[13  4  7 15  2  9] (8, 10, 5, 14, 6, 1) {11, 3, 12}
[13  4  7 15  2  9] (8, 12, 3, 6, 14, 1) {10, 11, 5}
[13  4  7 15  2  9] (8, 12, 3, 14, 6, 1) {10, 11, 5}
[12  4  8 14  2 10] (1, 3, 11, 5, 15, 9) {13, 6, 7}
[12  4  8 14  2 10] (1, 3, 11, 7, 13, 9) {5, 6, 15}
[12  4  8 14  2 10] (1, 3, 11, 13, 7, 9) {5, 6, 15}
[12  4  8 14  2 10] (1, 3, 11, 15, 5, 9) {13, 6, 7}
[12  4  8 14  2 10] (1, 11, 3, 5, 15, 9) {13, 6, 7}
[12  4  8 14  2 10] (1, 11, 3, 7, 13, 9) {5, 6, 15}
[12  4  8 14  2 10] (1, 11, 3, 13, 7, 9) {5, 6, 15}
[12  4  8 14  2 10] (1, 11, 3, 15, 5, 9) {13, 6, 7}
[12  4  8 14  2 10] (3, 1, 13, 5, 15, 7) {9, 11, 6}
[12  4  8 14  2 10] (3, 1, 13, 9, 11, 7) {5, 6, 15}
[12  4  8 14  2 10] (3, 1, 13, 11, 9, 7) {5, 6, 15}
[12  4  8 14  2 10] (3, 1, 13, 15, 5, 7) {9, 11, 6}
[12  4  8 14  2 10] (3, 13, 1, 5, 15, 7) {9, 11, 6}
[12  4

[11  3 10  5  9  4] (6, 8, 12, 7, 14, 13) {1, 2, 15}
[11  3 10  5  9  4] (6, 8, 12, 14, 7, 13) {1, 2, 15}
[11  3 10  5  9  4] (6, 12, 8, 7, 14, 13) {1, 2, 15}
[11  3 10  5  9  4] (6, 12, 8, 14, 7, 13) {1, 2, 15}
[11  3 10  5  9  4] (7, 6, 14, 8, 13, 12) {1, 2, 15}
[11  3 10  5  9  4] (7, 6, 14, 13, 8, 12) {1, 2, 15}
[11  3 10  5  9  4] (7, 14, 6, 8, 13, 12) {1, 2, 15}
[11  3 10  5  9  4] (7, 14, 6, 13, 8, 12) {1, 2, 15}
[11  3 10  5  9  4] (12, 6, 14, 8, 13, 7) {1, 2, 15}
[11  3 10  5  9  4] (12, 6, 14, 13, 8, 7) {1, 2, 15}
[11  3 10  5  9  4] (12, 14, 6, 8, 13, 7) {1, 2, 15}
[11  3 10  5  9  4] (12, 14, 6, 13, 8, 7) {1, 2, 15}
[11  3 10  5  9  4] (13, 8, 12, 7, 14, 6) {1, 2, 15}
[11  3 10  5  9  4] (13, 8, 12, 14, 7, 6) {1, 2, 15}
[11  3 10  5  9  4] (13, 12, 8, 7, 14, 6) {1, 2, 15}
[11  3 10  5  9  4] (13, 12, 8, 14, 7, 6) {1, 2, 15}
[14  3  7 11  6  4] (1, 5, 15, 8, 13, 12) {9, 2, 10}
[14  3  7 11  6  4] (1, 5, 15, 13, 8, 12) {9, 2, 10}
[14  3  7 11  6  4] (1, 15, 5, 8, 13, 12) {9, 

[11  3 10  8  6  7] (2, 13, 4, 9, 12, 14) {1, 5, 15}
[11  3 10  8  6  7] (2, 13, 4, 12, 9, 14) {1, 5, 15}
[11  3 10  8  6  7] (14, 4, 13, 9, 12, 2) {1, 5, 15}
[11  3 10  8  6  7] (14, 4, 13, 12, 9, 2) {1, 5, 15}
[11  3 10  8  6  7] (14, 13, 4, 9, 12, 2) {1, 5, 15}
[11  3 10  8  6  7] (14, 13, 4, 12, 9, 2) {1, 5, 15}
[11  3 10  8  6  7] (15, 4, 13, 9, 12, 1) {2, 5, 14}
[11  3 10  8  6  7] (15, 4, 13, 12, 9, 1) {2, 5, 14}
[11  3 10  8  6  7] (15, 13, 4, 9, 12, 1) {2, 5, 14}
[11  3 10  8  6  7] (15, 13, 4, 12, 9, 1) {2, 5, 14}
[11  6  7 14  3 10] (1, 2, 12, 5, 13, 9) {8, 4, 15}
[11  6  7 14  3 10] (1, 2, 12, 13, 5, 9) {8, 4, 15}
[11  6  7 14  3 10] (1, 12, 2, 5, 13, 9) {8, 4, 15}
[11  6  7 14  3 10] (1, 12, 2, 13, 5, 9) {8, 4, 15}
[11  6  7 14  3 10] (9, 2, 12, 5, 13, 1) {8, 4, 15}
[11  6  7 14  3 10] (9, 2, 12, 13, 5, 1) {8, 4, 15}
[11  6  7 14  3 10] (9, 12, 2, 5, 13, 1) {8, 4, 15}
[11  6  7 14  3 10] (9, 12, 2, 13, 5, 1) {8, 4, 15}
[11  7  6 15  3 10] (1, 2, 12, 4, 13, 8) {9, 5, 14}
[1

[11  5  8 12  4  9] (10, 1, 14, 6, 13, 2) {3, 15, 7}
[11  5  8 12  4  9] (10, 1, 14, 13, 6, 2) {3, 15, 7}
[11  5  8 12  4  9] (10, 14, 1, 6, 13, 2) {3, 15, 7}
[11  5  8 12  4  9] (10, 14, 1, 13, 6, 2) {3, 15, 7}
[11  8  5 15  4  9] (2, 1, 14, 3, 13, 7) {10, 12, 6}
[11  8  5 15  4  9] (2, 1, 14, 6, 10, 7) {3, 12, 13}
[11  8  5 15  4  9] (2, 1, 14, 10, 6, 7) {3, 12, 13}
[11  8  5 15  4  9] (2, 1, 14, 13, 3, 7) {10, 12, 6}
[11  8  5 15  4  9] (2, 3, 12, 6, 10, 7) {1, 13, 14}
[11  8  5 15  4  9] (2, 3, 12, 10, 6, 7) {1, 13, 14}
[11  8  5 15  4  9] (2, 12, 3, 6, 10, 7) {1, 13, 14}
[11  8  5 15  4  9] (2, 12, 3, 10, 6, 7) {1, 13, 14}
[11  8  5 15  4  9] (2, 14, 1, 3, 13, 7) {10, 12, 6}
[11  8  5 15  4  9] (2, 14, 1, 6, 10, 7) {3, 12, 13}
[11  8  5 15  4  9] (2, 14, 1, 10, 6, 7) {3, 12, 13}
[11  8  5 15  4  9] (2, 14, 1, 13, 3, 7) {10, 12, 6}
[11  8  5 15  4  9] (7, 1, 14, 3, 13, 2) {10, 12, 6}
[11  8  5 15  4  9] (7, 1, 14, 6, 10, 2) {3, 12, 13}
[11  8  5 15  4  9] (7, 1, 14, 10, 6, 2) {3, 1

[10  8  6 13  5  9] (7, 3, 12, 2, 14, 4) {1, 11, 15}
[10  8  6 13  5  9] (7, 3, 12, 14, 2, 4) {1, 11, 15}
[10  8  6 13  5  9] (7, 3, 12, 15, 1, 4) {2, 11, 14}
[10  8  6 13  5  9] (7, 12, 3, 1, 15, 4) {2, 11, 14}
[10  8  6 13  5  9] (7, 12, 3, 2, 14, 4) {1, 11, 15}
[10  8  6 13  5  9] (7, 12, 3, 14, 2, 4) {1, 11, 15}
[10  8  6 13  5  9] (7, 12, 3, 15, 1, 4) {2, 11, 14}
1264


In [9]:
print("for k>=3, a(n) are multiple of 6 because the rotation of only three corners does not affect the sum of 1-st row and n-th row.")

for k>=3, a(n) are multiple of 6 because the rotation of only three corners does not affect the sum of 1-st row and n-th row.


In [10]:
print("therefore, a(5) is 6*1264=7584")

therefore, a(5) is 6*1264=7584


In [11]:
sum3

24

In [12]:
sum6

48