In [1]:
import itertools

In [2]:
from itertools import product
from itertools import permutations
from itertools import combinations

In [3]:
tt=list(combinations(list(range(1,25)),6))

In [4]:
import numpy as np


In [5]:
comb=np.array(tt)

In [6]:
comb.shape

(134596, 6)

In [7]:
c=(comb.sum(axis=1)==75)
c.sum(axis=0)

3486

In [8]:
d=0
candid=np.zeros([c.sum(axis=0),6],dtype='int32')
for i in range(134596):
    if c[i]==True:
        candid[d,:]=comb[i,:]
        d+=1

In [9]:
candid

array([[ 1,  2,  3, 22, 23, 24],
       [ 1,  2,  4, 21, 23, 24],
       [ 1,  2,  5, 20, 23, 24],
       ...,
       [ 9, 10, 12, 13, 15, 16],
       [ 9, 11, 12, 13, 14, 16],
       [10, 11, 12, 13, 14, 15]])

NameError: name 'parities' is not defined

In [11]:
dicts={"1100":1,
"1010":2,
"1001":3,
"100-":4,
"10-0":5,
"1-00":6,

"0110":7,
"0101":8,
"010-":9,
"01-0":10,
"0011":11,
"001-":12,
"00-1":13,
"00--":14,
"0-10":15,
"0-01":16,
"0-0-":17,
"0--0":18,

"-100":19,
"-010":20,
"-001":21,
"-00-":22,
"-0-0":23,
"--00":24}


In [12]:
dicts

{'1100': 1,
 '1010': 2,
 '1001': 3,
 '100-': 4,
 '10-0': 5,
 '1-00': 6,
 '0110': 7,
 '0101': 8,
 '010-': 9,
 '01-0': 10,
 '0011': 11,
 '001-': 12,
 '00-1': 13,
 '00--': 14,
 '0-10': 15,
 '0-01': 16,
 '0-0-': 17,
 '0--0': 18,
 '-100': 19,
 '-010': 20,
 '-001': 21,
 '-00-': 22,
 '-0-0': 23,
 '--00': 24}

In [13]:
dicts['1100']

1

In [14]:
def coord24(a1,a2,a3,a4,a5,a6):
    return dicts[a1],dicts[a2],dicts[a3],dicts[a4],dicts[a5],dicts[a6]

In [15]:
coord24('1100','1001','100-','1010','10-0','1-00')

(1, 3, 4, 2, 5, 6)

In [16]:
coord24('-100','-001','-00-','-010','-0-0','--00')

(19, 21, 22, 20, 23, 24)

In [18]:
coord24('1100','0101','010-','0110','01-0','-100')

(1, 8, 9, 7, 10, 19)

In [19]:
coord24('1-00','0-01','0-0-','0-10','0--0','--00')

(6, 16, 17, 15, 18, 24)

In [20]:
coord24('1010','0011','001-','0110','0-10','-010')

(2, 11, 12, 7, 15, 20)

In [21]:
coord24('10-0','00-1','00--','01-0','0--0','-0-0')

(5, 13, 14, 10, 18, 23)

In [22]:
coord24('1001','0011','00-1','0101','0-01','-001')

(3, 11, 13, 8, 16, 21)

In [23]:
coord24('100-','001-','00--','010-','0-0-','-00-')

(4, 12, 14, 9, 17, 22)

In [24]:
coord1=np.array([(1, 3, 4, 2, 5, 6),(19, 21, 22, 20, 23, 24),(1, 8, 9, 7, 10, 19),(6, 16, 17, 15, 18, 24),(2, 11, 12, 7, 15, 20),(5, 13, 14, 10, 18, 23),(3, 11, 13, 8, 16, 21),(4, 12, 14, 9, 17, 22)])

In [25]:
coord1

array([[ 1,  3,  4,  2,  5,  6],
       [19, 21, 22, 20, 23, 24],
       [ 1,  8,  9,  7, 10, 19],
       [ 6, 16, 17, 15, 18, 24],
       [ 2, 11, 12,  7, 15, 20],
       [ 5, 13, 14, 10, 18, 23],
       [ 3, 11, 13,  8, 16, 21],
       [ 4, 12, 14,  9, 17, 22]])

In [26]:
temps=np.array([[1,1,0,0],[1,0,1,0],[1,0,0,1],[0,0,1,1],[0,1,0,1],[0,1,1,0]])

In [27]:
b=np.zeros([16,4],dtype='int32')
for i in range(16):
    b[i] = np.array([int(j) for j in list('{0:04b}'.format(i))])
b=b*2-1

In [28]:
for i in range(16):
    b[i]*temps

In [29]:
b[i]*temps

array([[1, 1, 0, 0],
       [1, 0, 1, 0],
       [1, 0, 0, 1],
       [0, 0, 1, 1],
       [0, 1, 0, 1],
       [0, 1, 1, 0]])

In [30]:
((b[i]*temps)*[27,9,3,1]).sum(axis=1)

array([36, 30, 28,  4, 10, 12])

In [31]:
(np.array([[1,1,0,0],
[1,0,1,0],
[1,0,0,1],
[1,0,0,-1],
[1,0,-1,0],
[1,-1,0,0],

[0,1,1,0],
[0,1,0,1],
[0,1,0,-1],
[0,1,-1,0],
[0,0,1,1],
[0,0,1,-1],
[0,0,-1,1],
[0,0,-1,-1],
[0,-1,1,0],
[0,-1,0,1],
[0,-1,0,-1],
[0,-1,-1,0],

[-1,1,0,0],
[-1,0,1,0],
[-1,0,0,1],
[-1,0,0,-1],
[-1,0,-1,0],
[-1,-1,0,0]])*[27,9,3,1]).sum(axis=1)


array([ 36,  30,  28,  26,  24,  18,  12,  10,   8,   6,   4,   2,  -2,
        -4,  -6,  -8, -10, -12, -18, -24, -26, -28, -30, -36])

In [32]:
np.array([ 36,  30,  28,  26,  24,  18,  12,  10,   8,   6,   4,   2,  -2,
        -4,  -6,  -8, -10, -12, -18, -24, -26, -28, -30, -36])

array([ 36,  30,  28,  26,  24,  18,  12,  10,   8,   6,   4,   2,  -2,
        -4,  -6,  -8, -10, -12, -18, -24, -26, -28, -30, -36])

In [33]:
dictnum={ 36:1,  30:2,  28:3,  26:4,  24:5,  18:6,  12:7,  10:8,   8:9,   6:10,   4:11,   2:12, 
         -2:13, -4:14,  -6:15,  -8:16, -10:17, -12:18, -18:19, -24:20, -26:21, -28:22, -30:23, -36:24}

In [34]:
coord2=np.zeros([16,6],dtype='int32')
for i in range(16):
    temp=(((b[i]*temps)*[27,9,3,1]).sum(axis=1)).tolist()
    coord2[i]=list(map(lambda x: dictnum[x], temp))

In [35]:
  coord2

array([[24, 23, 22, 14, 17, 18],
       [24, 23, 21, 13, 16, 18],
       [24, 20, 22, 12, 17, 15],
       [24, 20, 21, 11, 16, 15],
       [19, 23, 22, 14,  9, 10],
       [19, 23, 21, 13,  8, 10],
       [19, 20, 22, 12,  9,  7],
       [19, 20, 21, 11,  8,  7],
       [ 6,  5,  4, 14, 17, 18],
       [ 6,  5,  3, 13, 16, 18],
       [ 6,  2,  4, 12, 17, 15],
       [ 6,  2,  3, 11, 16, 15],
       [ 1,  5,  4, 14,  9, 10],
       [ 1,  5,  3, 13,  8, 10],
       [ 1,  2,  4, 12,  9,  7],
       [ 1,  2,  3, 11,  8,  7]])

In [135]:
i

15

In [36]:
coord=np.concatenate((coord1,coord2))

In [37]:
coord

array([[ 1,  3,  4,  2,  5,  6],
       [19, 21, 22, 20, 23, 24],
       [ 1,  8,  9,  7, 10, 19],
       [ 6, 16, 17, 15, 18, 24],
       [ 2, 11, 12,  7, 15, 20],
       [ 5, 13, 14, 10, 18, 23],
       [ 3, 11, 13,  8, 16, 21],
       [ 4, 12, 14,  9, 17, 22],
       [24, 23, 22, 14, 17, 18],
       [24, 23, 21, 13, 16, 18],
       [24, 20, 22, 12, 17, 15],
       [24, 20, 21, 11, 16, 15],
       [19, 23, 22, 14,  9, 10],
       [19, 23, 21, 13,  8, 10],
       [19, 20, 22, 12,  9,  7],
       [19, 20, 21, 11,  8,  7],
       [ 6,  5,  4, 14, 17, 18],
       [ 6,  5,  3, 13, 16, 18],
       [ 6,  2,  4, 12, 17, 15],
       [ 6,  2,  3, 11, 16, 15],
       [ 1,  5,  4, 14,  9, 10],
       [ 1,  5,  3, 13,  8, 10],
       [ 1,  2,  4, 12,  9,  7],
       [ 1,  2,  3, 11,  8,  7]])

In [38]:
coordmat=np.zeros((24,24), dtype=int)
for i in range(24):
    tmp=coord[i]
    for j in range(6):
        coordmat[i]+=np.eye(24, dtype=int)[tmp[j]-1]

In [39]:
coordmat

array([[1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
        1, 1],
       [1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
        0, 1],
       [0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
        0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
        1, 0],
       [0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,
        0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
        0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1,
        1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
        1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1,
        0, 1],
       [0, 0, 0, 0, 0

In [40]:
ss=np.zeros(24, dtype=int)
for i in range(6):
    ss+=np.eye(24, dtype=int)[coord[1,i]-1]

In [41]:
ss

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 1])

In [42]:
coord[1]

array([19, 21, 22, 20, 23, 24])

In [43]:
s=combinations(range(1,25),12)

In [44]:
iters=list(s)

In [45]:
s=np.array(iters)

In [46]:
sdim=s.shape

In [47]:
combs=np.zeros((sdim[0],24), dtype=int)
for i in range(sdim[0]):
    tmp=s[i]
    for j in range(12):
        combs[i]+=np.eye(24, dtype=int)[tmp[j]-1]

In [48]:
combs.shape

(2704156, 24)

In [49]:
combs[0]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [50]:
tex=np.matmul(combs,np.transpose(coordmat))%2

In [51]:
sums=np.sum(tex,axis=1)

In [52]:
np.sum(sums==24)

256

In [53]:
parities=np.zeros((256,24), dtype=int)
ind=0
for i in range(sdim[0]):
    if sums[i] ==24:
        parities[ind]=combs[i]
        ind+=1

In [54]:
parities[0]

array([1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0])

In [55]:
for i in range(256):
    print(np.sum(coordmat*parities[i],axis=1))

[5 1 5 1 3 3 3 3 1 1 1 1 3 3 3 3 3 3 3 3 5 5 5 5]
[5 1 5 1 3 3 3 3 1 1 1 1 3 3 3 3 3 3 3 3 5 5 5 5]
[5 1 5 1 3 3 3 3 1 1 1 1 3 3 3 3 3 3 3 3 5 5 5 5]
[5 1 3 3 5 1 3 3 1 1 3 3 1 1 3 3 3 3 5 5 3 3 5 5]
[5 1 5 1 3 3 3 3 1 1 1 1 3 3 3 3 3 3 3 3 5 5 5 5]
[5 1 3 3 3 3 5 1 1 3 1 3 1 3 1 3 3 5 3 5 3 5 3 5]
[5 1 3 3 3 3 1 5 3 1 3 1 3 1 3 1 5 3 5 3 5 3 5 3]
[5 1 3 3 1 5 3 3 3 3 1 1 3 3 1 1 5 5 3 3 5 5 3 3]
[5 1 5 1 3 3 3 3 1 1 1 1 3 3 3 3 3 3 3 3 5 5 5 5]
[5 1 3 3 5 1 3 3 1 1 3 3 1 1 3 3 3 3 5 5 3 3 5 5]
[5 1 3 3 5 1 3 3 1 1 3 3 1 1 3 3 3 3 5 5 3 3 5 5]
[5 1 3 3 5 1 3 3 1 1 3 3 1 1 3 3 3 3 5 5 3 3 5 5]
[5 1 3 3 5 1 3 3 1 1 3 3 1 1 3 3 3 3 5 5 3 3 5 5]
[5 1 3 3 3 3 5 1 1 3 1 3 1 3 1 3 3 5 3 5 3 5 3 5]
[5 1 3 3 3 3 1 5 3 1 3 1 3 1 3 1 5 3 5 3 5 3 5 3]
[5 1 1 5 3 3 3 3 3 3 3 3 1 1 1 1 5 5 5 5 3 3 3 3]
[5 1 5 1 3 3 3 3 1 1 1 1 3 3 3 3 3 3 3 3 5 5 5 5]
[5 1 3 3 3 3 5 1 1 3 1 3 1 3 1 3 3 5 3 5 3 5 3 5]
[5 1 3 3 5 1 3 3 1 1 3 3 1 1 3 3 3 3 5 5 3 3 5 5]
[5 1 3 3 3 3 5 1 1 3 1 3 1 3 1 3 3 5 3 5 3 5 3 5]


In [56]:
print("64개는, 모든 정팔면체에 모두 홀짝이 3개씩이고, 나머지 192개는 홀짝이 5개/1개로 나뉜 경우도 있다.")

64개는, 모든 정팔면체에 모두 홀짝이 3개씩이고, 나머지 192개는 홀짝이 5개/1개로 나뉜 경우도 있다.


In [57]:
for i in range(256):
    print(parities[i])

[1 1 1 1 1 0 1 1 1 0 0 0 1 1 1 0 0 0 1 0 0 0 0 0]
[1 1 1 1 1 0 1 1 0 1 0 1 0 1 0 1 0 0 1 0 0 0 0 0]
[1 1 1 1 1 0 1 0 1 1 1 0 1 0 0 0 1 0 1 0 0 0 0 0]
[1 1 1 1 1 0 1 0 0 0 1 1 0 0 1 1 1 0 1 0 0 0 0 0]
[1 1 1 1 1 0 0 1 1 1 1 1 0 0 0 0 0 1 1 0 0 0 0 0]
[1 1 1 1 1 0 0 1 0 0 1 0 1 0 1 1 0 1 1 0 0 0 0 0]
[1 1 1 1 1 0 0 0 1 0 0 1 0 1 1 0 1 1 1 0 0 0 0 0]
[1 1 1 1 1 0 0 0 0 1 0 0 1 1 0 1 1 1 1 0 0 0 0 0]
[1 1 1 1 0 1 1 1 1 1 0 0 1 1 0 0 0 0 0 1 0 0 0 0]
[1 1 1 1 0 1 1 1 0 0 0 1 0 1 1 1 0 0 0 1 0 0 0 0]
[1 1 1 1 0 1 1 0 1 0 1 0 1 0 1 0 1 0 0 1 0 0 0 0]
[1 1 1 1 0 1 1 0 0 1 1 1 0 0 0 1 1 0 0 1 0 0 0 0]
[1 1 1 1 0 1 0 1 1 0 1 1 0 0 1 0 0 1 0 1 0 0 0 0]
[1 1 1 1 0 1 0 1 0 1 1 0 1 0 0 1 0 1 0 1 0 0 0 0]
[1 1 1 1 0 1 0 0 1 1 0 1 0 1 0 0 1 1 0 1 0 0 0 0]
[1 1 1 1 0 1 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 0 0 0]
[1 1 1 0 1 1 1 1 1 1 0 1 0 1 0 0 0 0 0 0 1 0 0 0]
[1 1 1 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 0 0 0]
[1 1 1 0 1 1 1 0 1 0 1 1 0 0 1 0 1 0 0 0 1 0 0 0]
[1 1 1 0 1 1 1 0 0 1 1 0 1 0 0 1 1 0 0 0 1 0 0 0]


In [58]:
np.savez('24-cell',candid,parities,coord,coordmat)

In [59]:
fivesu=np.zeros(256,dtype=int)
for i in range(256):
    fivesu[i]=np.sum(np.sum(coordmat*parities[i],axis=1)==5)

In [60]:
fivesu

array([6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 0, 6, 0, 6, 6, 6, 0, 6, 0, 0, 0, 6, 6, 6, 0, 0, 0, 0, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 6, 0, 0, 0, 6, 6, 6, 0, 6, 6, 0, 6,
       6, 6, 0, 0, 0, 6, 0, 6, 6, 6, 6, 0, 6, 0, 6, 6, 6, 0, 6, 0, 0, 0,
       6, 6, 6, 0, 0, 0, 0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0, 6, 6, 6, 0, 0, 0, 6, 0, 6, 6, 6,
       0, 6, 0, 6, 6, 6, 6, 0, 6, 0, 0, 0, 6, 6, 6, 0, 6, 6, 0, 6, 6, 6,
       0, 0, 0, 6, 0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0, 6,
       6, 6, 0, 0, 0, 6, 0, 6, 6, 6, 0, 6, 0, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 0, 0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6])

In [61]:
for i in range(256):
    print(parities[i]+np.flip(parities[i]))

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [62]:
print("좌표축 기준 마주보는 점 끼리는 홀짝성이 달라야 한다.")

좌표축 기준 마주보는 점 끼리는 홀짝성이 달라야 한다.


In [63]:
coordmat

array([[1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
        1, 1],
       [1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
        0, 1],
       [0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
        0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
        1, 0],
       [0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,
        0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
        0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1,
        1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
        1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1,
        0, 1],
       [0, 0, 0, 0, 0

In [64]:
sixtets=np.zeros((192,24), dtype=int)
sixtet=np.zeros((192,3), dtype=int)
l=0
for i in range(24):
    for j in range(24):
        for k in range(24):
            temp=coordmat[i]+coordmat[j]+coordmat[k]
            if np.max(temp)==1:
                sixtet[l]=[i,j,k]
                sixtets[l]=np.ones(24,dtype=int)-(coordmat[i]+coordmat[j]+coordmat[k])
                l+=1

In [65]:
for i in range(192):
    print(sixtets[i])

[0 0 0 0 0 0 0 0 1 1 0 1 1 0 1 1 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 1 0 1 1 0 0 1 1 0 1 0 0 0 0 0 0 0]
[0 0 0 0 0 0 1 0 1 0 1 0 0 1 0 1 0 1 0 0 0 0 0 0]
[0 0 0 0 0 0 1 1 0 0 0 1 1 0 0 0 1 1 0 0 0 0 0 0]
[0 0 0 0 0 0 1 1 0 0 0 1 1 0 0 0 1 1 0 0 0 0 0 0]
[0 0 0 0 0 0 1 0 1 0 1 0 0 1 0 1 0 1 0 0 0 0 0 0]
[0 0 0 0 0 0 0 1 0 1 1 0 0 1 1 0 1 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 1 1 0 1 1 0 1 1 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 1 1 0 1 1 0 1 1 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 1 0 1 1 0 0 1 1 0 1 0 0 0 0 0 0 0]
[0 0 0 0 0 0 1 0 1 0 1 0 0 1 0 1 0 1 0 0 0 0 0 0]
[0 0 0 0 0 0 1 1 0 0 0 1 1 0 0 0 1 1 0 0 0 0 0 0]
[0 0 0 0 0 0 1 1 0 0 0 1 1 0 0 0 1 1 0 0 0 0 0 0]
[0 0 0 0 0 0 1 0 1 0 1 0 0 1 0 1 0 1 0 0 0 0 0 0]
[0 0 0 0 0 0 0 1 0 1 1 0 0 1 1 0 1 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 1 1 0 1 1 0 1 1 0 0 0 0 0 0 0 0]
[0 0 0 1 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 0 0 0]
[0 0 1 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 1 0 1 0 0]
[0 1 0 1 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 1 0 1 0]
[0 1 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 1 0]


In [66]:
np.unique([[1,1],[2,2],[1,1]], axis=0)

array([[1, 1],
       [2, 2]])

In [67]:
np.unique(sixtets, axis=0)

array([[0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
        0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
        0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
        0, 0],
       [0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0,
        0, 0],
       [0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
        0, 0],
       [0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
        0, 0],
       [0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
        0, 0],
       [0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
        0, 0],
       [0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
        0, 0],
       [0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
        1, 0],
       [0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
        1, 0],
       [0, 1, 1, 0, 0

In [68]:
sixtetunik=np.unique(sixtets, axis=0)

In [69]:
for i in range(16):
    print(sixtetunik[i]-np.flip(sixtetunik[i]))

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [70]:
np.savez('24-cell',candid,parities,coord,coordmat,sixtetunik)

In [71]:
print('0=5=10=11.1=4=7=8,3=6=9=2')

0=5=10=11.1=4=7=8,3=6=9=2


In [72]:
samsams=np.zeros((64,24), dtype=int)
j=0
for i in range(256):
    if fivesu[i]==0:
        samsams[j]=parities[i]
        j+=1
j

64

In [75]:
for i in range(64):
    print(samsams[i])

[1 1 1 0 0 0 0 0 1 0 0 0 1 1 1 0 1 1 1 1 1 0 0 0]
[1 1 1 0 0 0 0 0 0 1 0 1 0 1 0 1 1 1 1 1 1 0 0 0]
[1 1 0 1 0 0 0 1 0 0 0 0 1 1 1 1 0 1 1 1 0 1 0 0]
[1 1 0 1 0 0 0 0 0 1 1 0 1 0 0 1 1 1 1 1 0 1 0 0]
[1 1 0 0 1 0 1 0 0 0 0 0 1 1 1 1 1 0 1 0 1 1 0 0]
[1 1 0 0 1 0 0 1 0 0 0 1 0 1 1 1 0 1 1 0 1 1 0 0]
[1 1 0 0 1 0 0 0 1 0 1 0 1 0 1 0 1 1 1 0 1 1 0 0]
[1 1 0 0 1 0 0 0 0 1 1 1 0 0 0 1 1 1 1 0 1 1 0 0]
[1 1 0 0 0 1 1 0 0 1 0 0 1 1 0 1 1 0 0 1 1 1 0 0]
[1 1 0 0 0 1 0 1 1 0 0 0 1 1 1 0 0 1 0 1 1 1 0 0]
[1 1 0 0 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 1 1 0 0]
[1 1 0 0 0 1 0 0 1 1 1 0 1 0 0 0 1 1 0 1 1 1 0 0]
[1 0 1 1 0 0 1 0 0 0 0 0 1 1 1 1 1 0 1 1 0 0 1 0]
[1 0 1 1 0 0 0 1 0 0 0 1 0 1 1 1 0 1 1 1 0 0 1 0]
[1 0 1 1 0 0 0 0 1 0 1 0 1 0 1 0 1 1 1 1 0 0 1 0]
[1 0 1 1 0 0 0 0 0 1 1 1 0 0 0 1 1 1 1 1 0 0 1 0]
[1 0 1 0 1 0 1 0 0 0 0 1 0 1 1 1 1 0 1 0 1 0 1 0]
[1 0 1 0 1 0 0 0 1 0 1 1 0 0 1 0 1 1 1 0 1 0 1 0]
[1 0 1 0 0 1 1 0 1 0 0 0 1 1 1 0 1 0 0 1 1 0 1 0]
[1 0 1 0 0 1 1 0 0 1 0 1 0 1 0 1 1 0 0 1 1 0 1 0]


In [ ]:
print('0=5=10=11.1=4=7=8,3=6=9=2')

In [80]:
tricolor=[1,2,3,3,2,1,3,2,2,3,1,1,1,1,3,2,2,3,1,2,3,3,2,1]

In [92]:
h=0
for i in range(64):
    for j in range(64):
        for k in range(64):
            temp=12*samsams[i]+6*samsams[j]+3*samsams[k]+tricolor
            if np.size(np.unique(temp))==24:
                print([i,j,k])
                h+=1
h

[0, 7, 19]
[0, 7, 29]
[0, 7, 34]
[0, 7, 44]
[0, 10, 15]
[0, 10, 26]
[0, 10, 37]
[0, 10, 48]
[0, 15, 10]
[0, 15, 26]
[0, 15, 37]
[0, 15, 53]
[0, 19, 7]
[0, 19, 29]
[0, 19, 34]
[0, 19, 56]
[0, 26, 10]
[0, 26, 15]
[0, 26, 48]
[0, 26, 53]
[0, 29, 7]
[0, 29, 19]
[0, 29, 44]
[0, 29, 56]
[0, 34, 7]
[0, 34, 19]
[0, 34, 44]
[0, 34, 56]
[0, 37, 10]
[0, 37, 15]
[0, 37, 48]
[0, 37, 53]
[0, 44, 7]
[0, 44, 29]
[0, 44, 34]
[0, 44, 56]
[0, 48, 10]
[0, 48, 26]
[0, 48, 37]
[0, 48, 53]
[0, 53, 15]
[0, 53, 26]
[0, 53, 37]
[0, 53, 48]
[0, 56, 19]
[0, 56, 29]
[0, 56, 34]
[0, 56, 44]
[1, 6, 18]
[1, 6, 30]
[1, 6, 33]
[1, 6, 45]
[1, 9, 14]
[1, 9, 27]
[1, 9, 36]
[1, 9, 49]
[1, 14, 9]
[1, 14, 27]
[1, 14, 36]
[1, 14, 54]
[1, 18, 6]
[1, 18, 30]
[1, 18, 33]
[1, 18, 57]
[1, 27, 9]
[1, 27, 14]
[1, 27, 49]
[1, 27, 54]
[1, 30, 6]
[1, 30, 18]
[1, 30, 45]
[1, 30, 57]
[1, 33, 6]
[1, 33, 18]
[1, 33, 45]
[1, 33, 57]
[1, 36, 9]
[1, 36, 14]
[1, 36, 49]
[1, 36, 54]
[1, 45, 6]
[1, 45, 30]
[1, 45, 33]
[1, 45, 57]
[1, 49, 9]
[1, 

[15, 10, 0]
[15, 10, 26]
[15, 10, 37]
[15, 10, 63]
[15, 11, 2]
[15, 11, 20]
[15, 11, 43]
[15, 11, 61]
[15, 20, 2]
[15, 20, 11]
[15, 20, 52]
[15, 20, 61]
[15, 26, 0]
[15, 26, 10]
[15, 26, 53]
[15, 26, 63]
[15, 37, 0]
[15, 37, 10]
[15, 37, 53]
[15, 37, 63]
[15, 43, 2]
[15, 43, 11]
[15, 43, 52]
[15, 43, 61]
[15, 52, 2]
[15, 52, 20]
[15, 52, 43]
[15, 52, 61]
[15, 53, 0]
[15, 53, 26]
[15, 53, 37]
[15, 53, 63]
[15, 61, 11]
[15, 61, 20]
[15, 61, 43]
[15, 61, 52]
[15, 63, 10]
[15, 63, 26]
[15, 63, 37]
[15, 63, 53]
[16, 6, 8]
[16, 6, 21]
[16, 6, 42]
[16, 6, 55]
[16, 8, 6]
[16, 8, 21]
[16, 8, 42]
[16, 8, 57]
[16, 14, 24]
[16, 14, 31]
[16, 14, 32]
[16, 14, 39]
[16, 21, 6]
[16, 21, 8]
[16, 21, 55]
[16, 21, 57]
[16, 24, 14]
[16, 24, 31]
[16, 24, 32]
[16, 24, 49]
[16, 31, 14]
[16, 31, 24]
[16, 31, 39]
[16, 31, 49]
[16, 32, 14]
[16, 32, 24]
[16, 32, 39]
[16, 32, 49]
[16, 39, 14]
[16, 39, 31]
[16, 39, 32]
[16, 39, 49]
[16, 42, 6]
[16, 42, 8]
[16, 42, 55]
[16, 42, 57]
[16, 49, 24]
[16, 49, 31]
[16, 49,

[30, 1, 6]
[30, 1, 18]
[30, 1, 45]
[30, 1, 57]
[30, 3, 5]
[30, 3, 24]
[30, 3, 39]
[30, 3, 58]
[30, 5, 3]
[30, 5, 24]
[30, 5, 39]
[30, 5, 60]
[30, 6, 1]
[30, 6, 18]
[30, 6, 45]
[30, 6, 62]
[30, 18, 1]
[30, 18, 6]
[30, 18, 57]
[30, 18, 62]
[30, 24, 3]
[30, 24, 5]
[30, 24, 58]
[30, 24, 60]
[30, 39, 3]
[30, 39, 5]
[30, 39, 58]
[30, 39, 60]
[30, 45, 1]
[30, 45, 6]
[30, 45, 57]
[30, 45, 62]
[30, 57, 1]
[30, 57, 18]
[30, 57, 45]
[30, 57, 62]
[30, 58, 3]
[30, 58, 24]
[30, 58, 39]
[30, 58, 60]
[30, 60, 5]
[30, 60, 24]
[30, 60, 39]
[30, 60, 58]
[30, 62, 6]
[30, 62, 18]
[30, 62, 45]
[30, 62, 57]
[31, 13, 18]
[31, 13, 22]
[31, 13, 41]
[31, 13, 45]
[31, 14, 16]
[31, 14, 24]
[31, 14, 39]
[31, 14, 47]
[31, 16, 14]
[31, 16, 24]
[31, 16, 39]
[31, 16, 49]
[31, 18, 13]
[31, 18, 22]
[31, 18, 41]
[31, 18, 50]
[31, 22, 13]
[31, 22, 18]
[31, 22, 45]
[31, 22, 50]
[31, 24, 14]
[31, 24, 16]
[31, 24, 47]
[31, 24, 49]
[31, 39, 14]
[31, 39, 16]
[31, 39, 47]
[31, 39, 49]
[31, 41, 13]
[31, 41, 18]
[31, 41, 45]
[31, 

[45, 41, 13]
[45, 41, 31]
[45, 41, 32]
[45, 41, 50]
[45, 50, 22]
[45, 50, 31]
[45, 50, 32]
[45, 50, 41]
[45, 57, 1]
[45, 57, 30]
[45, 57, 33]
[45, 57, 62]
[45, 62, 6]
[45, 62, 30]
[45, 62, 33]
[45, 62, 57]
[46, 4, 11]
[46, 4, 19]
[46, 4, 44]
[46, 4, 52]
[46, 11, 4]
[46, 11, 19]
[46, 11, 44]
[46, 11, 59]
[46, 12, 26]
[46, 12, 28]
[46, 12, 35]
[46, 12, 37]
[46, 19, 4]
[46, 19, 11]
[46, 19, 52]
[46, 19, 59]
[46, 26, 12]
[46, 26, 28]
[46, 26, 35]
[46, 26, 51]
[46, 28, 12]
[46, 28, 26]
[46, 28, 37]
[46, 28, 51]
[46, 35, 12]
[46, 35, 26]
[46, 35, 37]
[46, 35, 51]
[46, 37, 12]
[46, 37, 28]
[46, 37, 35]
[46, 37, 51]
[46, 44, 4]
[46, 44, 11]
[46, 44, 52]
[46, 44, 59]
[46, 51, 26]
[46, 51, 28]
[46, 51, 35]
[46, 51, 37]
[46, 52, 4]
[46, 52, 19]
[46, 52, 44]
[46, 52, 59]
[46, 59, 11]
[46, 59, 19]
[46, 59, 44]
[46, 59, 52]
[47, 6, 8]
[47, 6, 21]
[47, 6, 42]
[47, 6, 55]
[47, 8, 6]
[47, 8, 21]
[47, 8, 42]
[47, 8, 57]
[47, 14, 24]
[47, 14, 31]
[47, 14, 32]
[47, 14, 39]
[47, 21, 6]
[47, 21, 8]
[47, 21,

[59, 25, 10]
[59, 25, 23]
[59, 25, 40]
[59, 25, 53]
[59, 38, 10]
[59, 38, 23]
[59, 38, 40]
[59, 38, 53]
[59, 40, 10]
[59, 40, 25]
[59, 40, 38]
[59, 40, 53]
[59, 44, 11]
[59, 44, 17]
[59, 44, 46]
[59, 44, 52]
[59, 46, 11]
[59, 46, 19]
[59, 46, 44]
[59, 46, 52]
[59, 52, 17]
[59, 52, 19]
[59, 52, 44]
[59, 52, 46]
[59, 53, 23]
[59, 53, 25]
[59, 53, 38]
[59, 53, 40]
[60, 5, 24]
[60, 5, 30]
[60, 5, 33]
[60, 5, 39]
[60, 9, 13]
[60, 9, 21]
[60, 9, 42]
[60, 9, 50]
[60, 13, 9]
[60, 13, 21]
[60, 13, 42]
[60, 13, 54]
[60, 21, 9]
[60, 21, 13]
[60, 21, 50]
[60, 21, 54]
[60, 24, 5]
[60, 24, 30]
[60, 24, 33]
[60, 24, 58]
[60, 30, 5]
[60, 30, 24]
[60, 30, 39]
[60, 30, 58]
[60, 33, 5]
[60, 33, 24]
[60, 33, 39]
[60, 33, 58]
[60, 39, 5]
[60, 39, 30]
[60, 39, 33]
[60, 39, 58]
[60, 42, 9]
[60, 42, 13]
[60, 42, 50]
[60, 42, 54]
[60, 50, 9]
[60, 50, 21]
[60, 50, 42]
[60, 50, 54]
[60, 54, 13]
[60, 54, 21]
[60, 54, 42]
[60, 54, 50]
[60, 58, 24]
[60, 58, 30]
[60, 58, 33]
[60, 58, 39]
[61, 7, 25]
[61, 7, 28]
[61,

3072

In [89]:
np.array(tricolor).size

24

In [93]:
h=0
for i in range(64):
    for j in range(64):
        for k in range(64):
            temp=12*samsams[i]+6*samsams[j]+3*samsams[k]+tricolor
            if np.size(np.unique(temp))==24:
                print(temp)
                h+=1
h

[22 20 18  3  8  4  6  2 14 12  7 10 13 16 15 11 23 21 19 17 24  9  5  1]
[22 20 15  3 11  4  6  2 17  9 10  7 16 13 18  8 23 21 19 14 24 12  5  1]
[19 23 18  6  8  1  3  5 14 12  7 10 13 16 15 11 20 24 22 17 21  9  2  4]
[19 23 15  6 11  1  3  5 17  9 10  7 16 13 18  8 20 24 22 14 21 12  2  4]
[22 20 18  6  2  7  3  8 14 12  4 10 13 19 15 11 17 24 16 23 21  9  5  1]
[22 20 15  6  2 10  3 11 17  9  4  7 16 19 18  8 14 24 13 23 21 12  5  1]
[19 23 18  3  5  7  6  8 14 12  1 10 13 22 15 11 17 21 16 20 24  9  2  4]
[19 23 15  3  5 10  6 11 17  9  1  7 16 22 18  8 14 21 13 20 24 12  2  4]
[22 17 21  9  2  4  3  5 14 12  7 10 13 16 15 11 20 24 19 23 18  6  8  1]
[22 14 21 12  2  4  3  5 17  9 10  7 16 13 18  8 20 24 19 23 15  6 11  1]
[19 17 24  9  5  1  6  2 14 12  7 10 13 16 15 11 23 21 22 20 18  3  8  4]
[19 14 24 12  5  1  6  2 17  9 10  7 16 13 18  8 23 21 22 20 15  3 11  4]
[22 17 21  3  5  7  9  2 14 12  4 10 13 19 15 11 23 18 16 20 24  6  8  1]
[22 14 21  3  5 10 12  2 17  9  4  7 1

[22 17  3 15 11  7  9 20  2  6  4 10 13 19 21 23  5 18 16 14 12 24  8  1]
[22 14  3 18  8 10 12 20  2  6  4  7 16 19 21 23  5 15 13 17  9 24 11  1]
[19 17  6 15 11  7  9 23  5  3  1 10 13 22 24 20  2 18 16 14 12 21  8  4]
[19 14  6 18  8 10 12 23  5  3  1  7 16 22 24 20  2 15 13 17  9 21 11  4]
[16 23  9 21  5  1  3 14  8 12 10  4 19 13 15 17 11 24 22 20  6 18  2  7]
[16 20  9 24  2  4  6 14  8 12 10  1 22 13 15 17 11 21 19 23  3 18  5  7]
[13 23 12 21  5  1  3 17 11  9  7  4 19 16 18 14  8 24 22 20  6 15  2 10]
[13 20 12 24  2  4  6 17 11  9  7  1 22 16 18 14  8 21 19 23  3 15  5 10]
[16 23  9 15 11  1  3 20  8  6  4 10 13 19 21 17  5 24 22 14 12 18  2  7]
[16 20  9 15 11  4  6 23  8  3  1 10 13 22 24 17  2 21 19 14 12 18  5  7]
[13 23 12 18  8  1  3 20 11  6  4  7 16 19 21 14  5 24 22 17  9 15  2 10]
[13 20 12 18  8  4  6 23 11  3  1  7 16 22 24 14  2 21 19 17  9 15  5 10]
[16 23  3 21  8  4  9 14  5 12 10  1 22 13 15 20 11 18 19 17  6 24  2  7]
[16 20  6 24  8  1  9 14  2 12 10  4 1

[13 17 12  9 23  1 21  5 11  3  7  4 19 16 24 14 20  6 22  2 18 15  8 10]
[13 17 12  9 20  4 24  2 11  6  7  1 22 16 21 14 23  3 19  5 18 15  8 10]
[22 20  3 12 14  4  6 17  2  9  7 13 10 16 18 23  8 21 19 11 15 24  5  1]
[22 20  3  9 17  4  6 14  2 12 10 16  7 13 15 23 11 21 19  8 18 24  5  1]
[19 23  6 12 14  1  3 17  5  9  7 13 10 16 18 20  8 24 22 11 15 21  2  4]
[19 23  6  9 17  1  3 14  5 12 10 16  7 13 15 20 11 24 22  8 18 21  2  4]
[22 20  3  6 17  7 12 14  2  9  4 13 10 19 18 23 11 15 16  8 21 24  5  1]
[22 20  3  6 14 10  9 17  2 12  4 16  7 19 15 23  8 18 13 11 21 24  5  1]
[19 23  6  3 17  7 12 14  5  9  1 13 10 22 18 20 11 15 16  8 24 21  2  4]
[19 23  6  3 14 10  9 17  5 12  1 16  7 22 15 20  8 18 13 11 24 21  2  4]
[22 17  3  9 20  4 12 14  2  6  7 13 10 16 21 23 11 15 19  5 18 24  8  1]
[22 14  3 12 20  4  9 17  2  6 10 16  7 13 21 23  8 18 19  5 15 24 11  1]
[19 17  6  9 23  1 12 14  5  3  7 13 10 16 24 20 11 15 22  2 18 21  8  4]
[19 14  6 12 23  1  9 17  5  3 10 16  

[22 14  3  9 17 10 12  5  2 21 19 16  7  4  6 23 20 15 13  8 18 24 11  1]
[19 17  6 12 14  7  9  2  5 24 22 13 10  1  3 20 23 18 16 11 15 21  8  4]
[19 14  6  9 17 10 12  2  5 24 22 16  7  1  3 20 23 15 13  8 18 21 11  4]
[22 17  3  6 20  7  9 11  2 15 13 19  4 10 12 23 14 18 16  5 21 24  8  1]
[22 14  3  6 20 10 12  8  2 18 16 19  4  7  9 23 17 15 13  5 21 24 11  1]
[19 17  6  3 23  7  9 11  5 15 13 22  1 10 12 20 14 18 16  2 24 21  8  4]
[19 14  6  3 23 10 12  8  5 18 16 22  1  7  9 20 17 15 13  2 24 21 11  4]
[22 17  6  3 20  7  9  2 11 15 19 13 10  4 12 14 23 18 16  5 24 21  8  1]
[22 14  6  3 20 10 12  2  8 18 19 16  7  4  9 17 23 15 13  5 24 21 11  1]
[19 17  3  6 23  7  9  5 11 15 22 13 10  1 12 14 20 18 16  2 21 24  8  4]
[19 14  3  6 23 10 12  5  8 18 22 16  7  1  9 17 20 15 13  2 21 24 11  4]
[16 23 12  9 14  1  3  8  5 21 13 19  4 10  6 20 17 24 22 11 18 15  2  7]
[16 20 12  9 14  4  6  8  2 24 13 22  1 10  3 23 17 21 19 11 18 15  5  7]
[13 23  9 12 17  1  3 11  5 21 16 19  

[13 17  9  6 11 19 12 23 20  3  1  7 16 22 24  5  2 15  4 14 21 18  8 10]
[13 17  9  3 11 22 12 20 23  6  4  7 16 19 21  2  5 15  1 14 24 18  8 10]
[16 14  6 12  8 19  9 20 23  3 10  1 22 13 24  2  5 18  4 17 15 21 11  7]
[16 14  3 12  8 22  9 23 20  6 10  4 19 13 21  5  2 18  1 17 15 24 11  7]
[13 17  6  9 11 19 12 20 23  3  7  1 22 16 24  2  5 15  4 14 18 21  8 10]
[13 17  3  9 11 22 12 23 20  6  7  4 19 16 21  5  2 15  1 14 18 24  8 10]
[22 20 12  6  2 13  3 14  8 18  4 16  7 19  9 17 11 24 10 23 21 15  5  1]
[22 20  9  6  2 16  3 17 11 15  4 13 10 19 12 14  8 24  7 23 21 18  5  1]
[19 23 12  3  5 13  6 14  8 18  1 16  7 22  9 17 11 21 10 20 24 15  2  4]
[19 23  9  3  5 16  6 17 11 15  1 13 10 22 12 14  8 21  7 20 24 18  2  4]
[22 20  3  6 11 13  9 17  2 15  4 16  7 19 12 23  8 18 10 14 21 24  5  1]
[22 20  3  6  8 16 12 14  2 18  4 13 10 19  9 23 11 15  7 17 21 24  5  1]
[19 23  6  3 11 13  9 17  5 15  1 16  7 22 12 20  8 18 10 14 24 21  2  4]
[19 23  6  3  8 16 12 14  5 18  1 13 1

[22  2 18 15 11  7 21  8  5  3  4 10 13 19 24 20 17  6 16 14 12  9 23  1]
[22  2 15 18  8 10 21 11  5  3  4  7 16 19 24 20 14  6 13 17  9 12 23  1]
[19  5 18 15 11  7 24  8  2  6  1 10 13 22 21 23 17  3 16 14 12  9 20  4]
[19  5 15 18  8 10 24 11  2  6  1  7 16 22 21 23 14  3 13 17  9 12 20  4]
[22  2 18 15  8 10 21  5 11  3  7  4 19 16 24 14 20  6 13 17 12  9 23  1]
[22  2 15 18 11  7 21  5  8  3 10  4 19 13 24 17 20  6 16 14  9 12 23  1]
[19  5 18 15  8 10 24  2 11  6  7  1 22 16 21 14 23  3 13 17 12  9 20  4]
[19  5 15 18 11  7 24  2  8  6 10  1 22 13 21 17 23  3 16 14  9 12 20  4]
[16  8 24 21  2  4 15 11  5  9  1 10 13 22 18 20 14 12 19 23  6  3 17  7]
[16  8 21 24  5  1 15 11  2  9  4 10 13 19 18 23 14 12 22 20  3  6 17  7]
[13 11 24 21  2  4 18  8  5 12  1  7 16 22 15 20 17  9 19 23  6  3 14 10]
[13 11 21 24  5  1 18  8  2 12  4  7 16 19 15 23 17  9 22 20  3  6 14 10]
[16  8 24 21  5  1 15  2 11  9 10  4 19 13 18 14 23 12 22 20  6  3 17  7]
[16  8 21 24  2  4 15  5 11  9 10  1 2

[16  8 15 24  2 10  6 11 20  9 19  1 22  4 18  5 14 21 13 23  3 12 17  7]
[16  8 15 21  5 10  3 11 23  9 22  4 19  1 18  2 14 24 13 20  6 12 17  7]
[13 11 18 24  2  7  6  8 20 12 19  1 22  4 15  5 17 21 16 23  3  9 14 10]
[13 11 18 21  5  7  3  8 23 12 22  4 19  1 15  2 17 24 16 20  6  9 14 10]
[16  5 24 21  8  1  9  2 14 12 19 10 13  4 15 11 23 18 22 17  6  3 20  7]
[16  2 21 24  8  4  9  5 14 12 22 10 13  1 15 11 20 18 19 17  3  6 23  7]
[13  5 24 21 11  1 12  2 17  9 19  7 16  4 18  8 23 15 22 14  6  3 20 10]
[13  2 21 24 11  4 12  5 17  9 22  7 16  1 18  8 20 15 19 14  3  6 23 10]
[16  5 15 21  8 10  9 11 23  3 19  1 22  4 24  2 14 18 13 17  6 12 20  7]
[16  2 15 24  8 10  9 11 20  6 22  4 19  1 21  5 14 18 13 17  3 12 23  7]
[13  5 18 21 11  7 12  8 23  3 19  1 22  4 24  2 17 15 16 14  6  9 20 10]
[13  2 18 24 11  7 12  8 20  6 22  4 19  1 21  5 17 15 16 14  3  9 23 10]
[22 11 21 15  2  4  3  5  8 18 13 16  7 10  9 17 20 24 19 23 12  6 14  1]
[22  8 21 18  2  4  3  5 11 15 16 13 1

[19 11 15  6 17  7  3  5 23  9 22 13 10  1 18  2 20 24 16  8 21 12 14  4]
[19  8 18  6 14 10  3  5 23 12 22 16  7  1 15  2 20 24 13 11 21  9 17  4]
[22  2 21 12 14  4  9  5 17  3 16 13 10  7 24  8 20 18 19 11 15  6 23  1]
[22  2 21  9 17  4 12  5 14  3 13 16  7 10 24 11 20 15 19  8 18  6 23  1]
[19  5 24 12 14  1  9  2 17  6 16 13 10  7 21  8 23 18 22 11 15  3 20  4]
[19  5 24  9 17  1 12  2 14  6 13 16  7 10 21 11 23 15 22  8 18  3 20  4]
[22  5 21  3 17  7 12  2 14  9 13 19  4 10 18 11 23 15 16  8 24  6 20  1]
[22  5 21  3 14 10  9  2 17 12 16 19  4  7 15  8 23 18 13 11 24  6 20  1]
[19  2 24  6 17  7 12  5 14  9 13 22  1 10 18 11 20 15 16  8 21  3 23  4]
[19  2 24  6 14 10  9  5 17 12 16 22  1  7 15  8 20 18 13 11 21  3 23  4]
[22  2 18 12 14  7  6  8 20  3 19 13 10  4 24  5 17 21 16 11 15  9 23  1]
[22  2 15  9 17 10  6 11 20  3 19 16  7  4 24  5 14 21 13  8 18 12 23  1]
[19  5 18 12 14  7  3  8 23  6 22 13 10  1 21  2 17 24 16 11 15  9 20  4]
[19  5 15  9 17 10  3 11 23  6 22 16  

[16  5 21  9 11 13 24  8  2 15  1 19  4 22 12 23 17  3 10 14 18  6 20  7]
[16  2 24  9 11 13 21  8  5 15  4 22  1 19 12 20 17  6 10 14 18  3 23  7]
[13  5 21 12  8 16 24 11  2 18  1 19  4 22  9 23 14  3  7 17 15  6 20 10]
[13  2 24 12  8 16 21 11  5 18  4 22  1 19  9 20 14  6  7 17 15  3 23 10]
[16  5 24  9  2 19 21  8 11 15  1 13 10 22 12 14 17  6  4 23 18  3 20  7]
[16  2 21  9  5 22 24  8 11 15  4 13 10 19 12 14 17  3  1 20 18  6 23  7]
[13  5 24 12  2 19 21 11  8 18  1 16  7 22  9 17 14  6  4 23 15  3 20 10]
[13  2 21 12  5 22 24 11  8 18  4 16  7 19  9 17 14  3  1 20 15  6 23 10]
[16  5 21  9  2 22 15  8 11 24 10 19  4 13  3 14 17 12  1 23 18  6 20  7]
[16  2 24  9  5 19 15  8 11 21 10 22  1 13  6 14 17 12  4 20 18  3 23  7]
[13  5 21 12  2 22 18 11  8 24  7 19  4 16  3 17 14  9  1 23 15  6 20 10]
[13  2 24 12  5 19 18 11  8 21  7 22  1 16  6 17 14  9  4 20 15  3 23 10]
[16  5 15  9 11 19 21  8  2 24 10 22  1 13  3 23 17  6  4 14 18 12 20  7]
[16  2 15  9 11 22 24  8  5 21 10 19  

[22 11  3 15 17  7 21  5  2  9 13  4 19 10 18 23 20  6 16  8 12 24 14  1]
[22  8  3 18 14 10 21  5  2 12 16  4 19  7 15 23 20  6 13 11  9 24 17  1]
[19 11  6 15 17  7 24  2  5  9 13  1 22 10 18 20 23  3 16  8 12 21 14  4]
[19  8  6 18 14 10 24  2  5 12 16  1 22  7 15 20 23  3 13 11  9 21 17  4]
[22  2 12 21 14  4 18  8  5  3 13  7 16 10 24 20 17  9 19 11  6 15 23  1]
[22  2  9 21 17  4 15 11  5  3 16 10 13  7 24 20 14 12 19  8  6 18 23  1]
[19  5 12 24 14  1 18  8  2  6 13  7 16 10 21 23 17  9 22 11  3 15 20  4]
[19  5  9 24 17  1 15 11  2  6 16 10 13  7 21 23 14 12 22  8  3 18 20  4]
[22  2 12 18 14  7 21  5  8  3 13  4 19 10 24 17 20  6 16 11  9 15 23  1]
[22  2  9 15 17 10 21  5 11  3 16  4 19  7 24 14 20  6 13  8 12 18 23  1]
[19  5 12 18 14  7 24  2  8  6 13  1 22 10 21 17 23  3 16 11  9 15 20  4]
[19  5  9 15 17 10 24  2 11  6 16  1 22  7 21 14 23  3 13  8 12 18 20  4]
[22  5  3 21 17  7 15 11  2  9 19 10 13  4 18 23 14 12 16  8  6 24 20  1]
[22  5  3 21 14 10 18  8  2 12 19  7 1

[16  8  6 24  2 19 15 20 11  9 10  1 22 13 18 14  5 12  4 23  3 21 17  7]
[16  8  3 21  5 22 15 23 11  9 10  4 19 13 18 14  2 12  1 20  6 24 17  7]
[13 11  6 24  2 19 18 20  8 12  7  1 22 16 15 17  5  9  4 23  3 21 14 10]
[13 11  3 21  5 22 18 23  8 12  7  4 19 16 15 17  2  9  1 20  6 24 14 10]
[16  8  6 15 11 19 24 20  2  9  1 10 13 22 18 23  5  3  4 14 12 21 17  7]
[16  8  3 15 11 22 21 23  5  9  4 10 13 19 18 20  2  6  1 14 12 24 17  7]
[13 11  6 18  8 19 24 20  2 12  1  7 16 22 15 23  5  3  4 17  9 21 14 10]
[13 11  3 18  8 22 21 23  5 12  4  7 16 19 15 20  2  6  1 17  9 24 14 10]
[16  5  9 24  2 19 21 14  8 12 10  1 22 13 15 17 11  6  4 23  3 18 20  7]
[16  2  9 21  5 22 24 14  8 12 10  4 19 13 15 17 11  3  1 20  6 18 23  7]
[13  5 12 24  2 19 21 17 11  9  7  1 22 16 18 14  8  6  4 23  3 15 20 10]
[13  2 12 21  5 22 24 17 11  9  7  4 19 16 18 14  8  3  1 20  6 15 23 10]
[16  5  9 15 11 19 21 23  8  3  1 10 13 22 24 17  2  6  4 14 12 18 20  7]
[16  2  9 15 11 22 24 20  8  6  4 10 1

[19  2  6 24 11 13  9 17  5 15 22 16  7  1 12 20  8 18 10 14  3 21 23  4]
[19  2  6 24  8 16 12 14  5 18 22 13 10  1  9 20 11 15  7 17  3 21 23  4]
[16 11  9 15  5 19  3 23  8 21 13 22  1 10  6 17  2 24  4 20 12 18 14  7]
[16 11  9 15  2 22  6 20  8 24 13 19  4 10  3 17  5 21  1 23 12 18 14  7]
[13  8 12 18  5 19  3 23 11 21 16 22  1  7  6 14  2 24  4 20  9 15 17 10]
[13  8 12 18  2 22  6 20 11 24 16 19  4  7  3 14  5 21  1 23  9 15 17 10]
[16 11  6 15  8 19  9 20  2 24 13 22  1 10  3 23  5 18  4 17 12 21 14  7]
[16 11  3 15  8 22  9 23  5 21 13 19  4 10  6 20  2 18  1 17 12 24 14  7]
[13  8  6 18 11 19 12 20  2 24 16 22  1  7  3 23  5 15  4 14  9 21 17 10]
[13  8  3 18 11 22 12 23  5 21 16 19  4  7  6 20  2 15  1 14  9 24 17 10]
[16  5 12 21  8 13  9 14  2 24 19 22  1  4  3 23 11 18 10 17  6 15 20  7]
[16  2 12 24  8 13  9 14  5 21 22 19  4  1  6 20 11 18 10 17  3 15 23  7]
[13  5  9 21 11 16 12 17  2 24 19 22  1  4  3 23  8 15  7 14  6 18 20 10]
[13  2  9 24 11 16 12 17  5 21 22 19  

[16  5  3  9 23 19 21  8 14 12 22 10 13  1 15 11 17  6  4  2 18 24 20  7]
[16  2  6  9 20 22 24  8 14 12 19 10 13  4 15 11 17  3  1  5 18 21 23  7]
[13  5  3 12 23 19 21 11 17  9 22  7 16  1 18  8 14  6  4  2 15 24 20 10]
[13  2  6 12 20 22 24 11 17  9 19  7 16  4 18  8 14  3  1  5 15 21 23 10]
[22 11  9  3 17 13 15  2  5 21 16 19  4  7  6 20 23 12 10  8 24 18 14  1]
[22  8 12  3 14 16 18  2  5 21 13 19  4 10  6 20 23  9  7 11 24 15 17  1]
[19 11  9  6 17 13 15  5  2 24 16 22  1  7  3 23 20 12 10  8 21 18 14  4]
[19  8 12  6 14 16 18  5  2 24 13 22  1 10  3 23 20  9  7 11 21 15 17  4]
[22 11  3  9 17 13 15  5  2 21 19 16  7  4  6 23 20 12 10  8 18 24 14  1]
[22  8  3 12 14 16 18  5  2 21 19 13 10  4  6 23 20  9  7 11 15 24 17  1]
[19 11  6  9 17 13 15  2  5 24 22 16  7  1  3 20 23 12 10  8 18 21 14  4]
[19  8  6 12 14 16 18  2  5 24 22 13 10  1  3 20 23  9  7 11 15 21 17  4]
[22 11  3  6 20 13 15  8  2 18 16 19  4  7  9 23 17 12 10  5 21 24 14  1]
[22  8  3  6 20 16 18 11  2 15 13 19  

[ 4 20 24 18  2  7 15 11  8 21  1 10 13 22  6 17 14 12 16 23  9  3  5 19]
[ 4 20 24 15  2 10 18  8 11 21  1  7 16 22  6 14 17  9 13 23 12  3  5 19]
[ 1 23 21 18  5  7 15 11  8 24  4 10 13 19  3 17 14 12 16 20  9  6  2 22]
[ 1 23 21 15  5 10 18  8 11 24  4  7 16 19  3 14 17  9 13 20 12  6  2 22]
[ 4 20 18 24  8  1 15 11  2 21  7 10 13 16  6 23 14 12 22 17  3  9  5 19]
[ 4 20 15 24 11  1 18  8  2 21 10  7 16 13  6 23 17  9 22 14  3 12  5 19]
[ 1 23 18 21  8  4 15 11  5 24  7 10 13 16  3 20 14 12 19 17  6  9  2 22]
[ 1 23 15 21 11  4 18  8  5 24 10  7 16 13  3 20 17  9 19 14  6 12  2 22]
[ 4 20 18 24  2  7 15  8 11 21 10  1 22 13  6 14 17 12 16 23  3  9  5 19]
[ 4 20 15 24  2 10 18 11  8 21  7  1 22 16  6 17 14  9 13 23  3 12  5 19]
[ 1 23 18 21  5  7 15  8 11 24 10  4 19 13  3 14 17 12 16 20  6  9  2 22]
[ 1 23 15 21  5 10 18 11  8 24  7  4 19 16  3 17 14  9 13 20  6 12  2 22]
[ 4 20 18 15 11  7 24  8  2 21  1 10 13 22  6 23 17  3 16 14 12  9  5 19]
[ 4 20 15 18  8 10 24 11  2 21  1  7 1

[10 14 24 21  5  1  9  2 17 15 16  4 19  7 12  8 23 18 22 20  6  3 11 13]
[10 14 21 24  2  4  9  5 17 15 16  1 22  7 12  8 20 18 19 23  3  6 11 13]
[ 7 17 24 21  5  1 12  2 14 18 13  4 19 10  9 11 23 15 22 20  6  3  8 16]
[ 7 17 21 24  2  4 12  5 14 18 13  1 22 10  9 11 20 15 19 23  3  6  8 16]
[10 14 24 18  8  1  6  2 20 15 19  7 16  4 12  5 23 21 22 17  9  3 11 13]
[10 14 21 18  8  4  3  5 23 15 22  7 16  1 12  2 20 24 19 17  9  6 11 13]
[ 7 17 24 15 11  1  6  2 20 18 19 10 13  4  9  5 23 21 22 14 12  3  8 16]
[ 7 17 21 15 11  4  3  5 23 18 22 10 13  1  9  2 20 24 19 14 12  6  8 16]
[10 17 15 24  2  7  9  5 14 21 19  1 22  4  6 11 20 18 16 23  3 12  8 13]
[10 17 15 21  5  7  9  2 14 24 22  4 19  1  3 11 23 18 16 20  6 12  8 13]
[ 7 14 18 24  2 10 12  5 17 21 19  1 22  4  6  8 20 15 13 23  3  9 11 16]
[ 7 14 18 21  5 10 12  2 17 24 22  4 19  1  3  8 23 15 13 20  6  9 11 16]
[10 14 18 24  2  7  6  8 20 15 19  1 22  4 12  5 17 21 16 23  3  9 11 13]
[10 14 18 21  5  7  3  8 23 15 22  4 1

[ 4 17 15  9 20 10 21 11  2 24  7 22  1 16  3 23 14  6 13  5 18 12  8 19]
[ 4 14 18 12 20  7 21  8  2 24 10 22  1 13  3 23 17  6 16  5 15  9 11 19]
[ 1 17 15  9 23 10 24 11  5 21  7 19  4 16  6 20 14  3 13  2 18 12  8 22]
[ 1 14 18 12 23  7 24  8  5 21 10 19  4 13  6 20 17  3 16  2 15  9 11 22]
[10 23 15  9 17  1  3 20 14  6  4 16  7 19 21 11  5 24 22  8 18 12  2 13]
[10 20 15  9 17  4  6 23 14  3  1 16  7 22 24 11  2 21 19  8 18 12  5 13]
[ 7 23 18 12 14  1  3 20 17  6  4 13 10 19 21  8  5 24 22 11 15  9  2 16]
[ 7 20 18 12 14  4  6 23 17  3  1 13 10 22 24  8  2 21 19 11 15  9  5 16]
[10 23 15  3 20  4  9 17 14  6  1 16  7 22 21 11  8 18 19  5 24 12  2 13]
[10 20 15  6 23  1  9 17 14  3  4 16  7 19 24 11  8 18 22  2 21 12  5 13]
[ 7 23 18  3 20  4 12 14 17  6  1 13 10 22 21  8 11 15 19  5 24  9  2 16]
[ 7 20 18  6 23  1 12 14 17  3  4 13 10 19 24  8 11 15 22  2 21  9  5 16]
[10 23 15  6 20  1  3 17 14  9  7 19  4 16 18 11  8 24 22  5 21 12  2 13]
[10 20 15  3 23  4  6 17 14  9  7 22  

[ 4 20 18 12  8 13 24  2 14 21  7  1 22 16  6 11 23  3 10 17 15  9  5 19]
[ 4 20 15  9 11 16 24  2 17 21 10  1 22 13  6  8 23  3  7 14 18 12  5 19]
[ 1 23 18 12  8 13 21  5 14 24  7  4 19 16  3 11 20  6 10 17 15  9  2 22]
[ 1 23 15  9 11 16 21  5 17 24 10  4 19 13  3  8 20  6  7 14 18 12  2 22]
[ 4 20 18  3  8 22 15 11 23 21  7 10 13 16  6  2 14 12  1 17 24  9  5 19]
[ 4 20 15  3 11 22 18  8 23 21 10  7 16 13  6  2 17  9  1 14 24 12  5 19]
[ 1 23 18  6  8 19 15 11 20 24  7 10 13 16  3  5 14 12  4 17 21  9  2 22]
[ 1 23 15  6 11 19 18  8 20 24 10  7 16 13  3  5 17  9  4 14 21 12  2 22]
[ 4 17 21  9 11 13 24  2 20 15  7  1 22 16 12  5 23  3 10 14 18  6  8 19]
[ 4 14 21 12  8 16 24  2 20 18 10  1 22 13  9  5 23  3  7 17 15  6 11 19]
[ 1 17 24  9 11 13 21  5 23 15  7  4 19 16 12  2 20  6 10 14 18  3  8 22]
[ 1 14 24 12  8 16 21  5 23 18 10  4 19 13  9  2 20  6  7 17 15  3 11 22]
[ 4 17 21  9  2 22 15 11 20 24  7 10 13 16  3  5 14 12  1 23 18  6  8 19]
[ 4 14 21 12  2 22 18  8 20 24 10  7 1

[10 17  9 21 14  4 15  2  5 24 22  7 16  1  3 20 23 12 19 11  6 18  8 13]
[ 7 14 12 24 17  1 18  5  2 21 19 10 13  4  6 23 20  9 22  8  3 15 11 16]
[ 7 14 12 21 17  4 18  2  5 24 22 10 13  1  3 20 23  9 19  8  6 15 11 16]
[10 14  6 24 20  1 18  8  2 15 19  7 16  4 12 23 17  9 22  5  3 21 11 13]
[10 14  3 21 23  4 18  8  5 15 22  7 16  1 12 20 17  9 19  2  6 24 11 13]
[ 7 17  6 24 20  1 15 11  2 18 19 10 13  4  9 23 14 12 22  5  3 21  8 16]
[ 7 17  3 21 23  4 15 11  5 18 22 10 13  1  9 20 14 12 19  2  6 24  8 16]
[10 14  6 18 20  7 24  2  8 15 19  1 22  4 12 17 23  3 16  5  9 21 11 13]
[10 14  3 18 23  7 21  5  8 15 22  4 19  1 12 17 20  6 16  2  9 24 11 13]
[ 7 17  6 15 20 10 24  2 11 18 19  1 22  4  9 14 23  3 13  5 12 21  8 16]
[ 7 17  3 15 23 10 21  5 11 18 22  4 19  1  9 14 20  6 13  2 12 24  8 16]
[ 4 20 12 24 14  1 18  8  2 21 13  7 16 10  6 23 17  9 22 11  3 15  5 19]
[ 4 20  9 24 17  1 15 11  2 21 16 10 13  7  6 23 14 12 22  8  3 18  5 19]
[ 1 23 12 21 14  4 18  8  5 24 13  7 1

[ 4 14  9 21 17 10 12 20  2 24 16 22  1  7  3 23  5 15 13  8  6 18 11 19]
[ 1 17 12 24 14  7  9 23  5 21 13 19  4 10  6 20  2 18 16 11  3 15  8 22]
[ 1 14  9 24 17 10 12 23  5 21 16 19  4  7  6 20  2 15 13  8  3 18 11 22]
[ 4 17  3 21 23  7  9 20 11 15 22 13 10  1 12 14  5 18 16  2  6 24  8 19]
[ 4 14  3 21 23 10 12 20  8 18 22 16  7  1  9 17  5 15 13  2  6 24 11 19]
[ 1 17  6 24 20  7  9 23 11 15 19 13 10  4 12 14  2 18 16  5  3 21  8 22]
[ 1 14  6 24 20 10 12 23  8 18 19 16  7  4  9 17  2 15 13  5  3 21 11 22]
[10 23  3 15  8 16 21 14  5 18  4  1 22 19  9 20 11  6  7 17 12 24  2 13]
[10 20  6 15  8 16 24 14  2 18  1  4 19 22  9 23 11  3  7 17 12 21  5 13]
[ 7 23  3 18 11 13 21 17  5 15  4  1 22 19 12 20  8  6 10 14  9 24  2 16]
[ 7 20  6 18 11 13 24 17  2 15  1  4 19 22 12 23  8  3 10 14  9 21  5 16]
[10 23  3 15  5 19 18 14  8 21  7  1 22 16  6 17 11  9  4 20 12 24  2 13]
[10 20  6 15  2 22 18 14  8 24  7  4 19 16  3 17 11  9  1 23 12 21  5 13]
[ 7 23  3 18  5 19 15 17 11 21 10  1 2

[ 4 23  3 12 20 13 21 17 14  9  7  1 22 16 18 11  8  6 10  5 15 24  2 19]
[ 4 23  3  9 20 16 21 14 17 12 10  1 22 13 15  8 11  6  7  5 18 24  2 19]
[ 1 20  6 12 23 13 24 17 14  9  7  4 19 16 18 11  8  3 10  2 15 21  5 22]
[ 1 20  6  9 23 16 24 14 17 12 10  4 19 13 15  8 11  3  7  2 18 21  5 22]
[ 4 17  9 12 20 13 21 23 14  3  1  7 16 22 24 11  2  6 10  5 15 18  8 19]
[ 4 14 12  9 20 16 21 23 17  3  1 10 13 22 24  8  2  6  7  5 18 15 11 19]
[ 1 17  9 12 23 13 24 20 14  6  4  7 16 19 21 11  5  3 10  2 15 18  8 22]
[ 1 14 12  9 23 16 24 20 17  6  4 10 13 19 21  8  5  3  7  2 18 15 11 22]
[ 4 17 12  9 20 13 21 14 23  3  7  1 22 16 24  2 11  6 10  5 18 15  8 19]
[ 4 14  9 12 20 16 21 17 23  3 10  1 22 13 24  2  8  6  7  5 15 18 11 19]
[ 1 17 12  9 23 13 24 14 20  6  7  4 19 16 21  5 11  3 10  2 18 15  8 22]
[ 1 14  9 12 23 16 24 17 20  6 10  4 19 13 21  5  8  3  7  2 15 18 11 22]
[ 4 17  9  3 20 22 21 14 23 12 10  7 16 13 15  2 11  6  1  5 24 18  8 19]
[ 4 14 12  3 20 22 21 17 23  9  7 10 1

[10 14  9  6 17 19  3 23 20 15 16 22  1  7 12  5  2 24  4  8 21 18 11 13]
[10 14  9  3 17 22  6 20 23 15 16 19  4  7 12  2  5 21  1  8 24 18 11 13]
[ 7 17 12  6 14 19  3 23 20 18 13 22  1 10  9  5  2 24  4 11 21 15  8 16]
[ 7 17 12  3 14 22  6 20 23 18 13 19  4 10  9  2  5 21  1 11 24 15  8 16]
[10 14  6  9 20 16  3 23 17 15 19 22  1  4 12  8  2 24  7  5 18 21 11 13]
[10 14  3  9 23 16  6 20 17 15 22 19  4  1 12  8  5 21  7  2 18 24 11 13]
[ 7 17  6 12 20 13  3 23 14 18 19 22  1  4  9 11  2 24 10  5 15 21  8 16]
[ 7 17  3 12 23 13  6 20 14 18 22 19  4  1  9 11  5 21 10  2 15 24  8 16]
[10 14  6  9 17 19  3 20 23 15 22 16  7  1 12  2  5 24  4  8 18 21 11 13]
[10 14  3  9 17 22  6 23 20 15 19 16  7  4 12  5  2 21  1  8 18 24 11 13]
[ 7 17  6 12 14 19  3 20 23 18 22 13 10  1  9  2  5 24  4 11 15 21  8 16]
[ 7 17  3 12 14 22  6 23 20 18 19 13 10  4  9  5  2 21  1 11 15 24  8 16]
[10 14  6  3 23 19  9 20 17 15 16 22  1  7 12  8  5 18  4  2 24 21 11 13]
[10 14  3  6 20 22  9 23 17 15 16 19  

[ 4  2 18 24 20  7 21  8 14 12 22 10 13  1 15 11 17  6 16  5  3  9 23 19]
[ 4  2 15 24 20 10 21 11 17  9 22  7 16  1 18  8 14  6 13  5  3 12 23 19]
[ 1  5 18 21 23  7 24  8 14 12 19 10 13  4 15 11 17  3 16  2  6  9 20 22]
[ 1  5 15 21 23 10 24 11 17  9 19  7 16  4 18  8 14  3 13  2  6 12 20 22]
[10  8 24 18 14  1 15  2  5 21 16 19  4  7  6 20 23 12 22 11  9  3 17 13]
[10  8 21 18 14  4 15  5  2 24 16 22  1  7  3 23 20 12 19 11  9  6 17 13]
[ 7 11 24 15 17  1 18  2  5 21 13 19  4 10  6 20 23  9 22  8 12  3 14 16]
[ 7 11 21 15 17  4 18  5  2 24 13 22  1 10  3 23 20  9 19  8 12  6 14 16]
[10  8 18 24 14  1 15  5  2 21 19 16  7  4  6 23 20 12 22 11  3  9 17 13]
[10  8 18 21 14  4 15  2  5 24 22 16  7  1  3 20 23 12 19 11  6  9 17 13]
[ 7 11 15 24 17  1 18  5  2 21 19 13 10  4  6 23 20  9 22  8  3 12 14 16]
[ 7 11 15 21 17  4 18  2  5 24 22 13 10  1  3 20 23  9 19  8  6 12 14 16]
[10  5 21 24 14  1 15  8  2 18 16 19  4  7  9 23 17 12 22 11  3  6 20 13]
[10  2 24 21 14  4 15  8  5 18 16 22  

[ 4  8 21 15 11 16 18 23 20  3  1 10 13 22 24  5  2  9  7 14 12  6 17 19]
[ 1 11 24 18  8 13 15 20 23  6  4  7 16 19 21  2  5 12 10 17  9  3 14 22]
[ 1  8 24 15 11 16 18 20 23  6  4 10 13 19 21  2  5  9  7 14 12  3 17 22]
[ 4 11 18 21  8 13 15 20 23  3  7  1 22 16 24  2  5 12 10 17  6  9 14 19]
[ 4  8 15 21 11 16 18 20 23  3 10  1 22 13 24  2  5  9  7 14  6 12 17 19]
[ 1 11 18 24  8 13 15 23 20  6  7  4 19 16 21  5  2 12 10 17  3  9 14 22]
[ 1  8 15 24 11 16 18 23 20  6 10  4 19 13 21  5  2  9  7 14  3 12 17 22]
[ 4  2 21 18  8 22 24 14 20 12 10  7 16 13 15  5 11  3  1 17  9  6 23 19]
[ 4  2 21 15 11 22 24 17 20  9  7 10 13 16 18  5  8  3  1 14 12  6 23 19]
[ 1  5 24 18  8 19 21 14 23 12 10  7 16 13 15  2 11  6  4 17  9  3 20 22]
[ 1  5 24 15 11 19 21 17 23  9  7 10 13 16 18  2  8  6  4 14 12  3 20 22]
[ 4  2 18 21  8 22 24 20 14 12  7 10 13 16 15 11  5  3  1 17  6  9 23 19]
[ 4  2 15 21 11 22 24 20 17  9 10  7 16 13 18  8  5  3  1 14  6 12 23 19]
[ 1  5 18 24  8 19 21 23 14 12  7 10 1

[10  5 21 15  2 22  9 14 17 24 16 19  4  7  3  8 11 18  1 23 12  6 20 13]
[10  2 24 15  5 19  9 14 17 21 16 22  1  7  6  8 11 18  4 20 12  3 23 13]
[ 7  5 21 18  2 22 12 17 14 24 13 19  4 10  3 11  8 15  1 23  9  6 20 16]
[ 7  2 24 18  5 19 12 17 14 21 13 22  1 10  6 11  8 15  4 20  9  3 23 16]
[10  5 15 21  8 16  3 23 14 18 19 22  1  4  9 11  2 24  7 17  6 12 20 13]
[10  2 15 24  8 16  6 20 14 18 22 19  4  1  9 11  5 21  7 17  3 12 23 13]
[ 7  5 18 21 11 13  3 23 17 15 19 22  1  4 12  8  2 24 10 14  6  9 20 16]
[ 7  2 18 24 11 13  6 20 17 15 22 19  4  1 12  8  5 21 10 14  3  9 23 16]
[10  5 15 21  2 22  9 17 14 24 19 16  7  4  3 11  8 18  1 23  6 12 20 13]
[10  2 15 24  5 19  9 17 14 21 22 16  7  1  6 11  8 18  4 20  3 12 23 13]
[ 7  5 18 21  2 22 12 14 17 24 19 13 10  4  3  8 11 15  1 23  6  9 20 16]
[ 7  2 18 24  5 19 12 14 17 21 22 13 10  1  6  8 11 15  4 20  3  9 23 16]
[ 4 11 21 15  8 16  3 23 20 18 13 22  1 10  9  5  2 24  7 17 12  6 14 19]
[ 4  8 21 18 11 13  3 23 20 15 16 22  

[ 1  5 21  9 23 16 24 11 17 15 13 19  4 10 12  8 14  3  7  2 18  6 20 22]
[ 4  2 21 12 14 22 24  8 20 18 16 13 10  7  9  5 17  3  1 11 15  6 23 19]
[ 4  2 21  9 17 22 24 11 20 15 13 16  7 10 12  5 14  3  1  8 18  6 23 19]
[ 1  5 24 12 14 19 21  8 23 18 16 13 10  7  9  2 17  6  4 11 15  3 20 22]
[ 1  5 24  9 17 19 21 11 23 15 13 16  7 10 12  2 14  6  4  8 18  3 20 22]
[10  8  6 15 20 16 18 14 23  3 19  1 22  4 24  2 11  9  7  5 12 21 17 13]
[10  8  3 15 23 16 18 14 20  6 22  4 19  1 21  5 11  9  7  2 12 24 17 13]
[ 7 11  6 18 20 13 15 17 23  3 19  1 22  4 24  2  8 12 10  5  9 21 14 16]
[ 7 11  3 18 23 13 15 17 20  6 22  4 19  1 21  5  8 12 10  2  9 24 14 16]
[10  8  6 18 14 19 15 20 23  3 16  1 22  7 24  2  5 12  4 11  9 21 17 13]
[10  8  3 18 14 22 15 23 20  6 16  4 19  7 21  5  2 12  1 11  9 24 17 13]
[ 7 11  6 15 17 19 18 20 23  3 13  1 22 10 24  2  5  9  4  8 12 21 14 16]
[ 7 11  3 15 17 22 18 23 20  6 13  4 19 10 21  5  2  9  1  8 12 24 14 16]
[10  5  9 21 14 16 15 17 23  3 19  1 2

3072

In [95]:
3072*6//1152

16

In [96]:
3072*6//1152*4

64

In [103]:
np.sum(coordmat*np.transpose(np.array([22, 20, 18,  3,  8,  4,  6,  2, 14, 12,  7, 10, 13, 16, 15, 11, 23, 21, 19, 17, 24,  9,  5,  1])),axis=1)

array([75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75,
       75, 75, 75, 75, 75, 75, 75])