## order 5 magic triangles

# background

In [ ]:
#This enumeration does not count the corner swap, which means swapping between a corner triangle and an edge-adjacent triangle.

In [3]:
#             o
#            /w\ 
#           o-- o
#          /b\w/b\ 
#        o-- o-- o
#       /e\ / \ /e\ 
#      o-- o-- o-- o
#     /b\ / \a/ \ /b\ 
#    o---o---o-- o-- o
#   /w\w/b\ /e\ /b\c/c\ 
#  o---o---o---o-- o-- o

#1~25 are used. sum of 25 numbers are 25*13=325

In [4]:
#(1)
#             o
#            / \ 
#           o-- o
#          /1\ /1\ 
#        o-- o-- o
#       /2\1/2\1/2\ 
#      o-- o-- o-- o
#     /1\1/2\ /2\1/1\ 
#    o---o---o-- o-- o
#   / \ /1\1/2\1/1\ / \ 
#  o---o---o---o-- o-- o
# total sum: 6*sum

#(2)
#             o
#            /1\ 
#           o-- o
#          /1\1/1\ 
#        o-- o-- o
#       / \1/1\1/ \ 
#      o-- o-- o-- o
#     /1\1/1\3/1\1/1\ 
#    o---o---o-- o-- o
#   /1\1/1\1/ \1/1\1/1\ 
#  o---o---o---o-- o-- o
# total sum: 6*sum

#(3)
#             o
#            /1\ 
#           o-- o
#          /1\1/1\ 
#        o-- o-- o
#       /1\1/1\1/1\ 
#      o-- o-- o-- o
#     /1\1/1\1/1\1/1\ 
#    o---o---o-- o-- o
#   /1\1/1\1/1\1/1\1/1\ 
#  o---o---o---o-- o-- o
# total sum: 25*13=325

#(2)-(3)
#$ means -1

#             o
#            / \ 
#           o-- o
#          / \ / \ 
#        o-- o-- o
#       /$\ / \ /$\ 
#      o-- o-- o-- o
#     / \ / \2/ \ / \ 
#    o---o---o-- o-- o
#   / \ / \ /$\ / \ / \ 
#  o---o---o---o-- o-- o
# total sum: 6*sum-25*13

#(2)-(3)+(1)
#$ means -1

#             o
#            / \ 
#           o-- o
#          /1\ /1\ 
#        o-- o-- o
#       /1\1/2\1/1\ 
#      o-- o-- o-- o
#     /1\1/2\2/2\1/1\ 
#    o---o---o-- o-- o
#   / \ /1\1/1\1/1\ / \ 
#  o---o---o---o-- o-- o
# total sum: 12*sum-25*13

# (4): if we subtract central 2x2 subtriangle from (2)-(3)+(1):

#             o
#            / \ 
#           o-- o
#          /1\ /1\ 
#        o-- o-- o
#       /1\1/1\1/1\ 
#      o-- o-- o-- o
#     /1\1/1\1/1\1/1\ 
#    o---o---o-- o-- o
#   / \ /1\1/1\1/1\ / \ 
#  o---o---o---o-- o-- o
# total sum: 11*sum-25*13

#(3)-(4)

#             o
#            /1\ 
#           o-- o
#          / \1/ \ 
#        o-- o-- o
#       / \ / \ / \ 
#      o-- o-- o-- o
#     / \ / \/ \ / \ 
#    o---o---o-- o-- o
#   /1\1/ \ / \ / \1/1\ 
#  o---o---o---o-- o-- o
# total sum: 26*25-11*sum

# (5) sum of corner subtriangles
#             o
#            /1\ 
#           o-- o
#          /1\1/1\ 
#        o-- o-- o
#       / \ / \ / \ 
#      o-- o-- o-- o
#     /1\ / \ / \ /1\ 
#    o---o---o-- o-- o
#   /1\1/1\ / \ /1\1/1\ 
#  o---o---o---o-- o-- o
#total sum: 3*sum

#(5)-(3)+(4)
#             o
#            / \ 
#           o-- o
#          /1\ /1\ 
#        o-- o-- o
#       / \ / \ / \ 
#      o-- o-- o-- o
#     /1\ / \ / \ /1\ 
#    o---o---o-- o-- o
#   / \ /1\ / \ /1\ / \ 
#  o---o---o---o-- o-- o
#total sum = 14*sum-26*25

#sum of six numbers in 1~25 should be in sums(1 to 6) ~ sums(20 ~ 25)
# magic sum should be 48 to 56
#WLOG, finding solutions for 52,53,54,55, 56 is enough


In [5]:

#2a-3e=sum*6-25*13
#6b=14*sum-26*25

In [6]:
import itertools
import numpy as np

# sum 56

In [8]:
#             o
#            / \ 
#           o-- o
#          /1\ /1\ 
#        o-- o-- o
#       / \ / \ / \ 
#      o-- o-- o-- o
#     /1\ / \ / \ /1\ 
#    o---o---o-- o-- o
#   / \ /1\ / \ /1\ / \ 
#  o---o---o---o-- o-- o
#total sum = 14*sum-26*25=134

#$ means -1

#             o
#            / \ 
#           o-- o
#          / \ / \ 
#        o-- o-- o
#       /$\ / \ /$\ 
#      o-- o-- o-- o
#     / \ / \2/ \ / \ 
#    o---o---o-- o-- o
#   / \ / \ /$\ / \ / \ 
#  o---o---o---o-- o-- o
# total sum: 6*sum-25*13 = 11

In [9]:
#np.random.permutation(range(1,26))

In [10]:
sum=56

In [11]:
#             o
#            / \ 
#           o-- o
#          /b\ /b\ 
#        o-- o-- o
#       /a\ / \ /a\ 
#      o-- o-- o-- o
#     /b\ / \a/ \ /b\ 
#    o---o---o-- o-- o
#   / \ /b\ /a\ /b\ / \ 
#  o---o---o---o-- o-- o

In [12]:
i=0
for A in itertools.permutations(range(1,26), 4):
    if A[0]*2==A[1]+A[2]+A[3]+11 and A[1]>A[2] and A[2]>A[3]:
        #print(A)
        i+=1
print(i)
i56=i

566


In [13]:
As=np.zeros([i56,4],dtype=int)
i=0
for A in itertools.permutations(range(1,26), 4):
    if A[0]*2==A[1]+A[2]+A[3]+11 and A[1]>A[2] and A[2]>A[3]:
        #print(A)
        As[i,:]=A
        i+=1
print(i)

566


In [14]:
j=0
for B in itertools.combinations(range(1,26), 6):
    if np.sum(B)==134:
        j+=1
print(j)
j56=j

1


In [15]:
Bs=np.zeros([j56,6],dtype=int)
j=0
for B in itertools.combinations(range(1,26), 6):
    if np.sum(B)==134:
        Bs[j,:]=B
        j+=1
print(j)
j56=j

1


In [16]:
z=0
for x in range(i56):
    for y in range(j56):
        if len(set(As[x,:]) | set(Bs[y,:]))==10:
            #print(x,y)
            z+=1
print(z)
z56=z

188


In [17]:
Zs=np.zeros([z56,2],dtype=int)
Zlist=np.zeros([z56,10],dtype=int)
z=0
for x in range(i56):
    for y in range(j56):
        if len(set(As[x,:]) | set(Bs[y,:]))==10:
            Zlist[z,0:4]=As[x,:]
            Zlist[z,4:10]=Bs[y,:]
            Zs[z,:]=[x,y]
            z+=1
print(z)

188


In [18]:
Zlist

array([[ 9,  4,  2, ..., 23, 24, 25],
       [10,  4,  3, ..., 23, 24, 25],
       [10,  5,  3, ..., 23, 24, 25],
       ...,
       [20, 18,  8, ..., 23, 24, 25],
       [20, 18,  9, ..., 23, 24, 25],
       [20, 18, 10, ..., 23, 24, 25]])

In [19]:
sum=56
i=0
for x in range(z56):
    temp=set(range(1,26))-set(Zlist[x,:])
    X=Zlist[x,0:4]
    for Y in itertools.permutations(Zlist[x,4:10], 6):
        for C1 in temp:
            C0=sum-X[1]-Y[0]-C1
            C2=sum-Y[1]-X[2]-C1
            if C0+C1+C2+X[0]==sum:
                if C0>0 and C0 <=25 and C2>0 and C2<= 25 and len(set([C0, C1, C2])|set(X)|set(Y))==13:
                    temp2=temp-set([C0, C1, C2])
                    for C4 in temp2:
                        C3=sum-X[2]-Y[2]-C4
                        C5=sum-Y[3]-X[3]-C4
                        if C3+C4+C5+X[0]==sum:
                            
                            if C3>0 and C3 <=25 and C5>0 and C5<=25 and len(set([C0, C1, C2, C3, C4, C5])|set(X)|set(Y))==16:
                                C7=sum-C1-C4-X[0]
                                C6=sum-X[3]-Y[4]-C7
                                C8=sum-X[1]-Y[5]-C7
                                if C6+C7+C8+X[0]==sum:
                                    if C7>0 and C7 <=25 and C6>0 and C6<= 25 and C8>0 and C8<= 25 and len(set([C0, C1, C2, C3, C4, C5, C6, C7, C8])|set(X)|set(Y))==19:
                                        elses=set(range(1,26))-(set([C0, C1, C2, C3, C4, C5, C6, C7, C8])|set(X)|set(Y))
                                        for W in itertools.permutations(elses, 6):
                                            if W[0]+W[1]== sum-Y[0]-Y[1] and W[0]>W[1]:
                                                if W[2]+W[3]== sum-Y[2]-Y[3] and W[2]>W[3]:
                                                    if W[4]+W[5]==sum-Y[4]-Y[5] and W[4]>W[5]:
                                                        print(X,Y,[C0, C1, C2, C3, C4, C5, C6, C7, C8],elses,W)
                                                        i+=1
print(i)
n56=i

[11  5  4  2] (24, 21, 22, 19, 25, 23) [14, 13, 18, 10, 20, 15, 17, 12, 16] {1, 3, 6, 7, 8, 9} (8, 3, 9, 6, 7, 1)
[11  6  3  2] (22, 24, 21, 23, 19, 25) [16, 12, 17, 14, 18, 13, 20, 15, 10] {1, 4, 5, 7, 8, 9} (9, 1, 7, 5, 8, 4)
[11  6  3  2] (22, 24, 21, 23, 19, 25) [16, 12, 17, 14, 18, 13, 20, 15, 10] {1, 4, 5, 7, 8, 9} (9, 1, 8, 4, 7, 5)
[11  6  3  2] (25, 21, 24, 23, 19, 22) [13, 12, 20, 14, 15, 16, 17, 18, 10] {1, 4, 5, 7, 8, 9} (9, 1, 5, 4, 8, 7)
[11  6  4  1] (22, 25, 19, 23, 24, 21) [18, 10, 17, 13, 20, 12, 16, 15, 14] {2, 3, 5, 7, 8, 9} (7, 2, 9, 5, 8, 3)
[11  8  2  1] (19, 21, 22, 24, 25, 23) [12, 17, 16, 14, 18, 13, 20, 10, 15] {3, 4, 5, 6, 7, 9} (9, 7, 6, 4, 5, 3)
[11  8  2  1] (21, 19, 25, 24, 22, 23) [10, 17, 18, 14, 15, 16, 20, 13, 12] {3, 4, 5, 6, 7, 9} (9, 7, 4, 3, 6, 5)
[11  8  2  1] (23, 19, 25, 22, 24, 21) [10, 15, 20, 12, 17, 16, 18, 13, 14] {3, 4, 5, 6, 7, 9} (9, 5, 6, 3, 7, 4)
[12  7  5  1] (23, 22, 24, 25, 19, 21) [15, 11, 18, 14, 13, 17, 16, 20, 8] {2, 3, 4, 6, 

In [20]:
# I will not give all examples for other magic sums. If you want to get all magic triangles or order 5, you can easily rerun.

In [21]:
del X, Y, [C0, C1, C2, C3, C4, C5, C6, C7, C8],elses,W

# sum 55

In [23]:
#             o
#            / \ 
#           o-- o
#          /1\ /1\ 
#        o-- o-- o
#       / \ / \ / \ 
#      o-- o-- o-- o
#     /1\ / \ / \ /1\ 
#    o---o---o-- o-- o
#   / \ /1\ / \ /1\ / \ 
#  o---o---o---o-- o-- o
#total sum = 14*sum-26*25=120

#$ means -1

#             o
#            / \ 
#           o-- o
#          / \ / \ 
#        o-- o-- o
#       /$\ / \ /$\ 
#      o-- o-- o-- o
#     / \ / \2/ \ / \ 
#    o---o---o-- o-- o
#   / \ / \ /$\ / \ / \ 
#  o---o---o---o-- o-- o
# total sum: 6*sum-25*13 = 5

In [24]:
sum=55
#             o
#            / \ 
#           o-- o
#          /b\ /b\ 
#        o-- o-- o
#       /a\ / \ /a\ 
#      o-- o-- o-- o
#     /b\ / \a/ \ /b\ 
#    o---o---o-- o-- o
#   / \ /b\ /a\ /b\ / \ 
#  o---o---o---o-- o-- o

In [25]:
i=0
for A in itertools.permutations(range(1,26), 4):
    if A[0]*2==A[1]+A[2]+A[3]+5 and A[1]>A[2] and A[2]>A[3]:
        #print(A)
        i+=1
print(i)
i55=i

724


In [26]:
As=np.zeros([i55,4],dtype=int)
i=0
for A in itertools.permutations(range(1,26), 4):
    if A[0]*2==A[1]+A[2]+A[3]+5 and A[1]>A[2] and A[2]>A[3]:
        #print(A)
        As[i,:]=A
        i+=1
print(i)

724


In [27]:
j=0
for B in itertools.combinations(range(1,26), 6):
    if np.sum(B)==120:
        j+=1
print(j)
j55=j

110


In [28]:
Bs=np.zeros([j55,6],dtype=int)
j=0
for B in itertools.combinations(range(1,26), 6):
    if np.sum(B)==120:
        Bs[j,:]=B
        j+=1
print(j)

110


In [29]:
z=0
for x in range(i55):
    for y in range(j55):
        if len(set(As[x,:]) | set(Bs[y,:]))==10:
            #print(x,y)
            z+=1
print(z)
z55=z

24959


In [30]:
Zs=np.zeros([z55,2],dtype=int)
Zlist=np.zeros([z55,10],dtype=int)
z=0
for x in range(i55):
    for y in range(j55):
        if len(set(As[x,:]) | set(Bs[y,:]))==10:
            Zlist[z,0:4]=As[x,:]
            Zlist[z,4:10]=Bs[y,:]
            Zs[z,:]=[x,y]
            z+=1
print(z)

24959


In [31]:
Zlist

array([[ 6,  4,  2, ..., 23, 24, 25],
       [ 6,  4,  2, ..., 23, 24, 25],
       [ 6,  4,  2, ..., 23, 24, 25],
       ...,
       [25, 24, 18, ..., 21, 22, 23],
       [25, 24, 19, ..., 21, 22, 23],
       [25, 24, 20, ..., 21, 22, 23]])

In [32]:
sum=55
i=0
for x in range(z55):
    temp=set(range(1,26))-set(Zlist[x,:])
    X=Zlist[x,0:4]
    for Y in itertools.permutations(Zlist[x,4:10], 6):
        for C1 in temp:
            C0=sum-X[1]-Y[0]-C1
            C2=sum-Y[1]-X[2]-C1
            if C0+C1+C2+X[0]==sum:
                if C0>0 and C0 <=25 and C2>0 and C2<= 25 and len(set([C0, C1, C2])|set(X)|set(Y))==13:
                    temp2=temp-set([C0, C1, C2])
                    for C4 in temp2:
                        C3=sum-X[2]-Y[2]-C4
                        C5=sum-Y[3]-X[3]-C4
                        if C3+C4+C5+X[0]==sum:
                            
                            if C3>0 and C3 <=25 and C5>0 and C5<=25 and len(set([C0, C1, C2, C3, C4, C5])|set(X)|set(Y))==16:
                                C7=sum-C1-C4-X[0]
                                C6=sum-X[3]-Y[4]-C7
                                C8=sum-X[1]-Y[5]-C7
                                if C6+C7+C8+X[0]==sum:
                                    if C7>0 and C7 <=25 and C6>0 and C6<= 25 and C8>0 and C8<= 25 and len(set([C0, C1, C2, C3, C4, C5, C6, C7, C8])|set(X)|set(Y))==19:
                                        elses=set(range(1,26))-(set([C0, C1, C2, C3, C4, C5, C6, C7, C8])|set(X)|set(Y))
                                        for W in itertools.permutations(elses, 6):
                                            if W[0]+W[1]== sum-Y[0]-Y[1] and W[0]>W[1]:
                                                if W[2]+W[3]== sum-Y[2]-Y[3] and W[2]>W[3]:
                                                    if W[4]+W[5]==sum-Y[4]-Y[5] and W[4]>W[5]:
                                                        if i==0:
                                                            print(X,Y,[C0, C1, C2, C3, C4, C5, C6, C7, C8],elses,W)
                                                        i+=1
print(i)
n55=i

[6 4 2 1] (24, 15, 21, 23, 25, 12) [11, 16, 22, 18, 14, 17, 10, 19, 20] {3, 5, 7, 8, 9, 13} (9, 7, 8, 3, 13, 5)
1295


In [33]:
del X, Y, [C0, C1, C2, C3, C4, C5, C6, C7, C8],elses,W

# sum 54

In [35]:
#             o
#            / \ 
#           o-- o
#          /1\ /1\ 
#        o-- o-- o
#       / \ / \ / \ 
#      o-- o-- o-- o
#     /1\ / \ / \ /1\ 
#    o---o---o-- o-- o
#   / \ /1\ / \ /1\ / \ 
#  o---o---o---o-- o-- o
#total sum = 14*sum-26*25=106

#$ means -1

#             o
#            / \ 
#           o-- o
#          / \ / \ 
#        o-- o-- o
#       /$\ / \ /$\ 
#      o-- o-- o-- o
#     / \ / \2/ \ / \ 
#    o---o---o-- o-- o
#   / \ / \ /$\ / \ / \ 
#  o---o---o---o-- o-- o
# total sum: 6*sum-25*13 = -1

In [36]:
sum=54
#             o
#            / \ 
#           o-- o
#          /b\ /b\ 
#        o-- o-- o
#       /a\ / \ /a\ 
#      o-- o-- o-- o
#     /b\ / \a/ \ /b\ 
#    o---o---o-- o-- o
#   / \ /b\ /a\ /b\ / \ 
#  o---o---o---o-- o-- o

In [37]:
i=0
for A in itertools.permutations(range(1,26), 4):
    if A[0]*2==A[1]+A[2]+A[3]-1 and A[1]>A[2] and A[2]>A[3]:
        #print(A)
        i+=1
print(i)
i54=i

846


In [38]:
As=np.zeros([i54,4],dtype=int)
i=0
for A in itertools.permutations(range(1,26), 4):
    if A[0]*2==A[1]+A[2]+A[3]-1 and A[1]>A[2] and A[2]>A[3]:
        #print(A)
        As[i,:]=A
        i+=1
print(i)

846


In [39]:
j=0
for B in itertools.combinations(range(1,26), 6):
    if np.sum(B)==106:
        j+=1
print(j)
j54=j

974


In [40]:
Bs=np.zeros([j54,6],dtype=int)
j=0
for B in itertools.combinations(range(1,26), 6):
    if np.sum(B)==106:
        Bs[j,:]=B
        j+=1
print(j)

974


In [41]:
z=0
for x in range(i54):
    for y in range(j54):
        if len(set(As[x,:]) | set(Bs[y,:]))==10:
            #print(x,y)
            z+=1
print(z)
z54=z

249756


In [42]:
Zs=np.zeros([z54,2],dtype=int)
Zlist=np.zeros([z54,10],dtype=int)
z=0
for x in range(i54):
    for y in range(j54):
        if len(set(As[x,:]) | set(Bs[y,:]))==10:
            Zlist[z,0:4]=As[x,:]
            Zlist[z,4:10]=Bs[y,:]
            Zs[z,:]=[x,y]
            z+=1
print(z)

249756


In [43]:
Zlist

array([[ 3,  4,  2, ..., 23, 24, 25],
       [ 3,  4,  2, ..., 23, 24, 25],
       [ 3,  4,  2, ..., 23, 24, 25],
       ...,
       [25, 24, 23, ..., 18, 19, 22],
       [25, 24, 23, ..., 18, 20, 21],
       [25, 24, 23, ..., 18, 19, 21]])

In [44]:
sum=54
i=0
for x in range(z54):
    temp=set(range(1,26))-set(Zlist[x,:])
    X=Zlist[x,0:4]
    for Y in itertools.permutations(Zlist[x,4:10], 6):
        for C1 in temp:
            C0=sum-X[1]-Y[0]-C1
            C2=sum-Y[1]-X[2]-C1
            if C0+C1+C2+X[0]==sum:
                if C0>0 and C0 <=25 and C2>0 and C2<= 25 and len(set([C0, C1, C2])|set(X)|set(Y))==13:
                    temp2=temp-set([C0, C1, C2])
                    for C4 in temp2:
                        C3=sum-X[2]-Y[2]-C4
                        C5=sum-Y[3]-X[3]-C4
                        if C3+C4+C5+X[0]==sum:
                            
                            if C3>0 and C3 <=25 and C5>0 and C5<=25 and len(set([C0, C1, C2, C3, C4, C5])|set(X)|set(Y))==16:
                                C7=sum-C1-C4-X[0]
                                C6=sum-X[3]-Y[4]-C7
                                C8=sum-X[1]-Y[5]-C7
                                if C6+C7+C8+X[0]==sum:
                                    if C7>0 and C7 <=25 and C6>0 and C6<= 25 and C8>0 and C8<= 25 and len(set([C0, C1, C2, C3, C4, C5, C6, C7, C8])|set(X)|set(Y))==19:
                                        elses=set(range(1,26))-(set([C0, C1, C2, C3, C4, C5, C6, C7, C8])|set(X)|set(Y))
                                        for W in itertools.permutations(elses, 6):
                                            if W[0]+W[1]== sum-Y[0]-Y[1] and W[0]>W[1]:
                                                if W[2]+W[3]== sum-Y[2]-Y[3] and W[2]>W[3]:
                                                    if W[4]+W[5]==sum-Y[4]-Y[5] and W[4]>W[5]:
                                                        if i==0:
                                                            print(X,Y,[C0, C1, C2, C3, C4, C5, C6, C7, C8],elses,W)
                                                        i+=1
print(i)
n54=i

[3 4 2 1] (7, 25, 21, 18, 13, 22) [24, 19, 8, 16, 15, 20, 23, 17, 11] {5, 6, 9, 10, 12, 14} (12, 10, 9, 6, 14, 5)
6911


In [45]:
del X, Y, [C0, C1, C2, C3, C4, C5, C6, C7, C8],elses,W

# sum 53

In [47]:
#             o
#            / \ 
#           o-- o
#          /1\ /1\ 
#        o-- o-- o
#       / \ / \ / \ 
#      o-- o-- o-- o
#     /1\ / \ / \ /1\ 
#    o---o---o-- o-- o
#   / \ /1\ / \ /1\ / \ 
#  o---o---o---o-- o-- o
#total sum = 14*sum-26*25=92

#$ means -1

#             o
#            / \ 
#           o-- o
#          / \ / \ 
#        o-- o-- o
#       /$\ / \ /$\ 
#      o-- o-- o-- o
#     / \ / \2/ \ / \ 
#    o---o---o-- o-- o
#   / \ / \ /$\ / \ / \ 
#  o---o---o---o-- o-- o
# total sum: 6*sum-25*13 = -7

In [48]:
sum=53
#             o
#            / \ 
#           o-- o
#          /b\ /b\ 
#        o-- o-- o
#       /a\ / \ /a\ 
#      o-- o-- o-- o
#     /b\ / \a/ \ /b\ 
#    o---o---o-- o-- o
#   / \ /b\ /a\ /b\ / \ 
#  o---o---o---o-- o-- o

In [49]:
i=0
for A in itertools.permutations(range(1,26), 4):
    if A[0]*2==A[1]+A[2]+A[3]-7 and A[1]>A[2] and A[2]>A[3]:
        #print(A)
        i+=1
print(i)
i53=i

891


In [50]:
As=np.zeros([i53,4],dtype=int)
i=0
for A in itertools.permutations(range(1,26), 4):
    if A[0]*2==A[1]+A[2]+A[3]-7 and A[1]>A[2] and A[2]>A[3]:
        #print(A)
        As[i,:]=A
        i+=1
print(i)

891


In [51]:
j=0
for B in itertools.combinations(range(1,26), 6):
    if np.sum(B)==92:
        j+=1
print(j)
j53=j

3048


In [52]:
Bs=np.zeros([j53,6],dtype=int)
j=0
for B in itertools.combinations(range(1,26), 6):
    if np.sum(B)==92:
        Bs[j,:]=B
        j+=1
print(j)

3048


In [53]:
z=0
for x in range(i53):
    for y in range(j53):
        if len(set(As[x,:]) | set(Bs[y,:]))==10:
            #print(x,y)
            z+=1
print(z)
z53=z

814585


In [54]:
Zs=np.zeros([z53,2],dtype=int)
Zlist=np.zeros([z53,10],dtype=int)
z=0
for x in range(i53):
    for y in range(j53):
        if len(set(As[x,:]) | set(Bs[y,:]))==10:
            Zlist[z,0:4]=As[x,:]
            Zlist[z,4:10]=Bs[y,:]
            Zs[z,:]=[x,y]
            z+=1
print(z)

814585


In [55]:
Zlist

array([[ 1,  4,  3, ..., 23, 24, 25],
       [ 1,  4,  3, ..., 22, 24, 25],
       [ 1,  4,  3, ..., 21, 24, 25],
       ...,
       [25, 24, 23, ..., 16, 18, 19],
       [25, 24, 23, ..., 16, 17, 19],
       [25, 24, 23, ..., 16, 17, 18]])

In [56]:
sum=53
i=0
for x in range(z53):
    temp=set(range(1,26))-set(Zlist[x,:])
    X=Zlist[x,0:4]
    for Y in itertools.permutations(Zlist[x,4:10], 6):
        for C1 in temp:
            C0=sum-X[1]-Y[0]-C1
            C2=sum-Y[1]-X[2]-C1
            if C0+C1+C2+X[0]==sum:
                if C0>0 and C0 <=25 and C2>0 and C2<= 25 and len(set([C0, C1, C2])|set(X)|set(Y))==13:
                    temp2=temp-set([C0, C1, C2])
                    for C4 in temp2:
                        C3=sum-X[2]-Y[2]-C4
                        C5=sum-Y[3]-X[3]-C4
                        if C3+C4+C5+X[0]==sum:
                            
                            if C3>0 and C3 <=25 and C5>0 and C5<=25 and len(set([C0, C1, C2, C3, C4, C5])|set(X)|set(Y))==16:
                                C7=sum-C1-C4-X[0]
                                C6=sum-X[3]-Y[4]-C7
                                C8=sum-X[1]-Y[5]-C7
                                if C6+C7+C8+X[0]==sum:
                                    if C7>0 and C7 <=25 and C6>0 and C6<= 25 and C8>0 and C8<= 25 and len(set([C0, C1, C2, C3, C4, C5, C6, C7, C8])|set(X)|set(Y))==19:
                                        elses=set(range(1,26))-(set([C0, C1, C2, C3, C4, C5, C6, C7, C8])|set(X)|set(Y))
                                        for W in itertools.permutations(elses, 6):
                                            if W[0]+W[1]== sum-Y[0]-Y[1] and W[0]>W[1]:
                                                if W[2]+W[3]== sum-Y[2]-Y[3] and W[2]>W[3]:
                                                    if W[4]+W[5]==sum-Y[4]-Y[5] and W[4]>W[5]:
                                                        if i==0:
                                                            print(X,Y,[C0, C1, C2, C3, C4, C5, C6, C7, C8],elses,W)
                                                        i+=1
print(i)
n53=i

[1 4 3 2] (22, 7, 19, 16, 23, 5) [9, 18, 25, 17, 14, 21, 8, 20, 24] {6, 10, 11, 12, 13, 15} (13, 11, 12, 6, 15, 10)
13482


In [57]:
del X, Y, [C0, C1, C2, C3, C4, C5, C6, C7, C8],elses,W

# sum 52

In [59]:
#             o
#            / \ 
#           o-- o
#          /1\ /1\ 
#        o-- o-- o
#       / \ / \ / \ 
#      o-- o-- o-- o
#     /1\ / \ / \ /1\ 
#    o---o---o-- o-- o
#   / \ /1\ / \ /1\ / \ 
#  o---o---o---o-- o-- o
#total sum = 14*sum-26*25=78

#$ means -1

#             o
#            / \ 
#           o-- o
#          / \ / \ 
#        o-- o-- o
#       /$\ / \ /$\ 
#      o-- o-- o-- o
#     / \ / \2/ \ / \ 
#    o---o---o-- o-- o
#   / \ / \ /$\ / \ / \ 
#  o---o---o---o-- o-- o
# total sum: 6*sum-25*13 = -13

In [60]:
sum=52
#             o
#            / \ 
#           o-- o
#          /b\ /b\ 
#        o-- o-- o
#       /a\ / \ /a\ 
#      o-- o-- o-- o
#     /b\ / \a/ \ /b\ 
#    o---o---o-- o-- o
#   / \ /b\ /a\ /b\ / \ 
#  o---o---o---o-- o-- o

In [61]:
i=0
for A in itertools.permutations(range(1,26), 4):
    if A[0]*2==A[1]+A[2]+A[3]-13 and A[1]>A[2] and A[2]>A[3]:
        #print(A)
        i+=1
print(i)
i52=i

906


In [62]:
As=np.zeros([i52,4],dtype=int)
i=0
for A in itertools.permutations(range(1,26), 4):
    if A[0]*2==A[1]+A[2]+A[3]-13 and A[1]>A[2] and A[2]>A[3]:
        #print(A)
        As[i,:]=A
        i+=1
print(i)

906


In [65]:
j=0
for B in itertools.combinations(range(1,26), 6):
    if np.sum(B)==78:
        j+=1
print(j)
j52=j

4370


In [67]:
Bs=np.zeros([j52,6],dtype=int)
j=0
for B in itertools.combinations(range(1,26), 6):
    if np.sum(B)==78:
        Bs[j,:]=B
        j+=1
print(j)

4370


In [69]:
z=0
for x in range(i52):
    for y in range(j52):
        if len(set(As[x,:]) | set(Bs[y,:]))==10:
            #print(x,y)
            z+=1
print(z)
z52=z

1185928


In [71]:
Zs=np.zeros([z52,2],dtype=int)
Zlist=np.zeros([z52,10],dtype=int)
z=0
for x in range(i52):
    for y in range(j52):
        if len(set(As[x,:]) | set(Bs[y,:]))==10:
            Zlist[z,0:4]=As[x,:]
            Zlist[z,4:10]=Bs[y,:]
            Zs[z,:]=[x,y]
            z+=1
print(z)

1185928


In [73]:
Zlist

array([[ 1,  6,  5, ..., 17, 24, 25],
       [ 1,  6,  5, ..., 18, 23, 25],
       [ 1,  6,  5, ..., 19, 22, 25],
       ...,
       [25, 24, 23, ..., 14, 15, 17],
       [25, 24, 23, ..., 13, 14, 18],
       [25, 24, 23, ..., 13, 15, 17]])

In [75]:
sum=52
i=0
for x in range(z52):
    temp=set(range(1,26))-set(Zlist[x,:])
    X=Zlist[x,0:4]
    for Y in itertools.permutations(Zlist[x,4:10], 6):
        for C1 in temp:
            C0=sum-X[1]-Y[0]-C1
            C2=sum-Y[1]-X[2]-C1
            if C0+C1+C2+X[0]==sum:
                if C0>0 and C0 <=25 and C2>0 and C2<= 25 and len(set([C0, C1, C2])|set(X)|set(Y))==13:
                    temp2=temp-set([C0, C1, C2])
                    for C4 in temp2:
                        C3=sum-X[2]-Y[2]-C4
                        C5=sum-Y[3]-X[3]-C4
                        if C3+C4+C5+X[0]==sum:
                            
                            if C3>0 and C3 <=25 and C5>0 and C5<=25 and len(set([C0, C1, C2, C3, C4, C5])|set(X)|set(Y))==16:
                                C7=sum-C1-C4-X[0]
                                C6=sum-X[3]-Y[4]-C7
                                C8=sum-X[1]-Y[5]-C7
                                if C6+C7+C8+X[0]==sum:
                                    if C7>0 and C7 <=25 and C6>0 and C6<= 25 and C8>0 and C8<= 25 and len(set([C0, C1, C2, C3, C4, C5, C6, C7, C8])|set(X)|set(Y))==19:
                                        elses=set(range(1,26))-(set([C0, C1, C2, C3, C4, C5, C6, C7, C8])|set(X)|set(Y))
                                        for W in itertools.permutations(elses, 6):
                                            if W[0]+W[1]== sum-Y[0]-Y[1] and W[0]>W[1]:
                                                if W[2]+W[3]== sum-Y[2]-Y[3] and W[2]>W[3]:
                                                    if W[4]+W[5]==sum-Y[4]-Y[5] and W[4]>W[5]:
                                                        if i==0:
                                                            print(X,Y,[C0, C1, C2, C3, C4, C5, C6, C7, C8],elses,W)
                                                        i+=1
print(i)
n52=i

[1 6 5 4] (2, 19, 10, 22, 17, 8) [23, 21, 7, 25, 12, 14, 13, 18, 20] {3, 9, 11, 15, 16, 24} (16, 15, 11, 9, 24, 3)
23994


In [77]:
del X, Y, [C0, C1, C2, C3, C4, C5, C6, C7, C8],elses,W

# total number

In [79]:
print("total number for order 5 magic triangle:", n52+(n53+n54+n55+n56)*2)
n48=n56
n49=n55
n50=n54
n51=n53

total number for order 5 magic triangle: 67488


In [81]:
print("sum 48:", n48)
print("sum 49:", n49)
print("sum 51:", n51)
print("sum 52:", n52)
print("sum 53:", n53)
print("sum 54:", n54)
print("sum 55:", n55)
print("sum 56:", n56)
print("total:", n52+(n53+n54+n55+n56)*2)

sum 48: 59
sum 49: 1295
sum 51: 13482
sum 52: 23994
sum 53: 13482
sum 54: 6911
sum 55: 1295
sum 56: 59
total: 67488


In [85]:
#If we think that swapping between a corner triangle and an edge-adjacent triangle generate different examples, the counts should be eight times as large.

In [87]:
total=n52+(n53+n54+n55+n56)*2

In [89]:
print("total(including corner swap):", total*8)

total(including corner swap): 539904
