In [1]:
import itertools
import numpy as np

In [2]:
np.random.permutation(range(1,26))

array([14,  5,  4, 23,  7, 13, 10, 25,  6, 16,  8, 21, 24, 12, 20,  3, 18,
       22,  1,  2,  9, 11, 19, 17, 15])

In [3]:
sum=56

In [4]:
56*6-25*13

11

In [5]:
i=0
for A in itertools.permutations(range(1,26), 4):
    if A[0]*2==A[1]+A[2]+A[3]+11 and A[1]>A[2] and A[2]>A[3]:
        print(A)
        i+=1
print(i)

(9, 4, 2, 1)
(10, 4, 3, 2)
(10, 5, 3, 1)
(10, 6, 2, 1)
(11, 5, 4, 2)
(11, 6, 3, 2)
(11, 6, 4, 1)
(11, 7, 3, 1)
(11, 8, 2, 1)
(12, 6, 4, 3)
(12, 6, 5, 2)
(12, 7, 4, 2)
(12, 7, 5, 1)
(12, 8, 3, 2)
(12, 8, 4, 1)
(12, 9, 3, 1)
(12, 10, 2, 1)
(13, 6, 5, 4)
(13, 7, 5, 3)
(13, 7, 6, 2)
(13, 8, 4, 3)
(13, 8, 5, 2)
(13, 8, 6, 1)
(13, 9, 4, 2)
(13, 9, 5, 1)
(13, 10, 3, 2)
(13, 10, 4, 1)
(13, 11, 3, 1)
(13, 12, 2, 1)
(14, 7, 6, 4)
(14, 8, 5, 4)
(14, 8, 6, 3)
(14, 8, 7, 2)
(14, 9, 5, 3)
(14, 9, 6, 2)
(14, 9, 7, 1)
(14, 10, 4, 3)
(14, 10, 5, 2)
(14, 10, 6, 1)
(14, 11, 4, 2)
(14, 11, 5, 1)
(14, 12, 3, 2)
(14, 12, 4, 1)
(14, 13, 3, 1)
(15, 8, 6, 5)
(15, 8, 7, 4)
(15, 9, 6, 4)
(15, 9, 7, 3)
(15, 9, 8, 2)
(15, 10, 5, 4)
(15, 10, 6, 3)
(15, 10, 7, 2)
(15, 10, 8, 1)
(15, 11, 5, 3)
(15, 11, 6, 2)
(15, 11, 7, 1)
(15, 12, 4, 3)
(15, 12, 5, 2)
(15, 12, 6, 1)
(15, 13, 4, 2)
(15, 13, 5, 1)
(15, 14, 3, 2)
(15, 14, 4, 1)
(15, 16, 2, 1)
(16, 8, 7, 6)
(16, 9, 7, 5)
(16, 9, 8, 4)
(16, 10, 6, 5)
(16, 10, 7, 4)
(16, 

In [6]:
As=np.zeros([566,4],dtype=int)

In [7]:
i=0
for A in itertools.permutations(range(1,26), 4):
    if A[0]*2==A[1]+A[2]+A[3]+11 and A[1]>A[2] and A[2]>A[3]:
        print(A)
        As[i,:]=A
        i+=1
print(i)

(9, 4, 2, 1)
(10, 4, 3, 2)
(10, 5, 3, 1)
(10, 6, 2, 1)
(11, 5, 4, 2)
(11, 6, 3, 2)
(11, 6, 4, 1)
(11, 7, 3, 1)
(11, 8, 2, 1)
(12, 6, 4, 3)
(12, 6, 5, 2)
(12, 7, 4, 2)
(12, 7, 5, 1)
(12, 8, 3, 2)
(12, 8, 4, 1)
(12, 9, 3, 1)
(12, 10, 2, 1)
(13, 6, 5, 4)
(13, 7, 5, 3)
(13, 7, 6, 2)
(13, 8, 4, 3)
(13, 8, 5, 2)
(13, 8, 6, 1)
(13, 9, 4, 2)
(13, 9, 5, 1)
(13, 10, 3, 2)
(13, 10, 4, 1)
(13, 11, 3, 1)
(13, 12, 2, 1)
(14, 7, 6, 4)
(14, 8, 5, 4)
(14, 8, 6, 3)
(14, 8, 7, 2)
(14, 9, 5, 3)
(14, 9, 6, 2)
(14, 9, 7, 1)
(14, 10, 4, 3)
(14, 10, 5, 2)
(14, 10, 6, 1)
(14, 11, 4, 2)
(14, 11, 5, 1)
(14, 12, 3, 2)
(14, 12, 4, 1)
(14, 13, 3, 1)
(15, 8, 6, 5)
(15, 8, 7, 4)
(15, 9, 6, 4)
(15, 9, 7, 3)
(15, 9, 8, 2)
(15, 10, 5, 4)
(15, 10, 6, 3)
(15, 10, 7, 2)
(15, 10, 8, 1)
(15, 11, 5, 3)
(15, 11, 6, 2)
(15, 11, 7, 1)
(15, 12, 4, 3)
(15, 12, 5, 2)
(15, 12, 6, 1)
(15, 13, 4, 2)
(15, 13, 5, 1)
(15, 14, 3, 2)
(15, 14, 4, 1)
(15, 16, 2, 1)
(16, 8, 7, 6)
(16, 9, 7, 5)
(16, 9, 8, 4)
(16, 10, 6, 5)
(16, 10, 7, 4)
(16, 

In [8]:
j=0
for B in itertools.combinations(range(1,26), 6):
    if np.sum(B)==134:
        j+=1
print(j)

1


In [9]:
Bs=np.zeros([1,6],dtype=int)

In [11]:
j=0
for B in itertools.combinations(range(1,26), 6):
    if np.sum(B)==134:
        Bs[j,:]=B
        j+=1
print(j)

1


In [12]:
z=0
for x in range(566):
    for y in range(1):
        if len(set(As[x,:]) | set(Bs[y,:]))==10:
            #print(x,y)
            z+=1
print(z)

188


In [13]:
Zs=np.zeros([188,2],dtype=int)
Zlist=np.zeros([188,10],dtype=int)

In [14]:
z=0
for x in range(566):
    for y in range(1):
        if len(set(As[x,:]) | set(Bs[y,:]))==10:
            Zlist[z,0:4]=As[x,:]
            Zlist[z,4:10]=Bs[y,:]
            Zs[z,:]=[x,y]
            z+=1
print(z)

188


In [15]:
Zlist

array([[ 9,  4,  2, ..., 23, 24, 25],
       [10,  4,  3, ..., 23, 24, 25],
       [10,  5,  3, ..., 23, 24, 25],
       ...,
       [20, 18,  8, ..., 23, 24, 25],
       [20, 18,  9, ..., 23, 24, 25],
       [20, 18, 10, ..., 23, 24, 25]])

In [16]:
sum=56
i=0
for x in range(188):
    temp=set(range(1,26))-set(Zlist[x,:])
    X=Zlist[x,0:4]
    for Y in itertools.permutations(Zlist[x,4:10], 6):
        for C1 in temp:
            C0=sum-X[1]-Y[0]-C1
            C2=sum-Y[1]-X[2]-C1
            if C0+C1+C2+X[0]==sum:
                if C0>0 and C0 <=25 and C2>0 and C2<= 25 and len(set([C0, C1, C2])|set(X)|set(Y))==13:
                    temp2=temp-set([C0, C1, C2])
                    for C4 in temp2:
                        C3=sum-X[2]-Y[2]-C4
                        C5=sum-Y[3]-X[3]-C4
                        if C3+C4+C5+X[0]==sum:
                            
                            if C3>0 and C3 <=25 and C5>0 and C5<=25 and len(set([C0, C1, C2, C3, C4, C5])|set(X)|set(Y))==16:
                                C7=sum-C1-C4-X[0]
                                C6=sum-X[3]-Y[4]-C7
                                C8=sum-X[1]-Y[5]-C7
                                if C6+C7+C8+X[0]==sum:
                                    if C7>0 and C7 <=25 and C6>0 and C6<= 25 and C8>0 and C8<= 25 and len(set([C0, C1, C2, C3, C4, C5, C6, C7, C8])|set(X)|set(Y))==19:
                                        elses=set(range(1,26))-(set([C0, C1, C2, C3, C4, C5, C6, C7, C8])|set(X)|set(Y))
                                        for W in itertools.permutations(elses, 6):
                                            if W[0]+W[1]== sum-Y[0]-Y[1] and W[0]>W[1]:
                                                if W[2]+W[3]== sum-Y[2]-Y[3] and W[2]>W[3]:
                                                    if W[4]+W[5]==sum-Y[4]-Y[5] and W[4]>W[5]:
                                                        print(X,Y,[C0, C1, C2, C3, C4, C5, C6, C7, C8],elses,W)
                                                        i+=1
print(i)
                


[11  5  4  2] (24, 21, 22, 19, 25, 23) [14, 13, 18, 10, 20, 15, 17, 12, 16] {1, 3, 6, 7, 8, 9} (8, 3, 9, 6, 7, 1)
[11  6  3  2] (22, 24, 21, 23, 19, 25) [16, 12, 17, 14, 18, 13, 20, 15, 10] {1, 4, 5, 7, 8, 9} (9, 1, 7, 5, 8, 4)
[11  6  3  2] (22, 24, 21, 23, 19, 25) [16, 12, 17, 14, 18, 13, 20, 15, 10] {1, 4, 5, 7, 8, 9} (9, 1, 8, 4, 7, 5)
[11  6  3  2] (25, 21, 24, 23, 19, 22) [13, 12, 20, 14, 15, 16, 17, 18, 10] {1, 4, 5, 7, 8, 9} (9, 1, 5, 4, 8, 7)
[11  6  4  1] (22, 25, 19, 23, 24, 21) [18, 10, 17, 13, 20, 12, 16, 15, 14] {2, 3, 5, 7, 8, 9} (7, 2, 9, 5, 8, 3)
[11  8  2  1] (19, 21, 22, 24, 25, 23) [12, 17, 16, 14, 18, 13, 20, 10, 15] {3, 4, 5, 6, 7, 9} (9, 7, 6, 4, 5, 3)
[11  8  2  1] (21, 19, 25, 24, 22, 23) [10, 17, 18, 14, 15, 16, 20, 13, 12] {3, 4, 5, 6, 7, 9} (9, 7, 4, 3, 6, 5)
[11  8  2  1] (23, 19, 25, 22, 24, 21) [10, 15, 20, 12, 17, 16, 18, 13, 14] {3, 4, 5, 6, 7, 9} (9, 5, 6, 3, 7, 4)
[12  7  5  1] (23, 22, 24, 25, 19, 21) [15, 11, 18, 14, 13, 17, 16, 20, 8] {2, 3, 4, 6, 

KeyboardInterrupt: 

In [163]:
W

(8, 9, 12, 17, 6, 7)

In [169]:
for W in itertools.permutations(range(1,7), 6):
    print(W)

(1, 2, 3, 4, 5, 6)
(1, 2, 3, 4, 6, 5)
(1, 2, 3, 5, 4, 6)
(1, 2, 3, 5, 6, 4)
(1, 2, 3, 6, 4, 5)
(1, 2, 3, 6, 5, 4)
(1, 2, 4, 3, 5, 6)
(1, 2, 4, 3, 6, 5)
(1, 2, 4, 5, 3, 6)
(1, 2, 4, 5, 6, 3)
(1, 2, 4, 6, 3, 5)
(1, 2, 4, 6, 5, 3)
(1, 2, 5, 3, 4, 6)
(1, 2, 5, 3, 6, 4)
(1, 2, 5, 4, 3, 6)
(1, 2, 5, 4, 6, 3)
(1, 2, 5, 6, 3, 4)
(1, 2, 5, 6, 4, 3)
(1, 2, 6, 3, 4, 5)
(1, 2, 6, 3, 5, 4)
(1, 2, 6, 4, 3, 5)
(1, 2, 6, 4, 5, 3)
(1, 2, 6, 5, 3, 4)
(1, 2, 6, 5, 4, 3)
(1, 3, 2, 4, 5, 6)
(1, 3, 2, 4, 6, 5)
(1, 3, 2, 5, 4, 6)
(1, 3, 2, 5, 6, 4)
(1, 3, 2, 6, 4, 5)
(1, 3, 2, 6, 5, 4)
(1, 3, 4, 2, 5, 6)
(1, 3, 4, 2, 6, 5)
(1, 3, 4, 5, 2, 6)
(1, 3, 4, 5, 6, 2)
(1, 3, 4, 6, 2, 5)
(1, 3, 4, 6, 5, 2)
(1, 3, 5, 2, 4, 6)
(1, 3, 5, 2, 6, 4)
(1, 3, 5, 4, 2, 6)
(1, 3, 5, 4, 6, 2)
(1, 3, 5, 6, 2, 4)
(1, 3, 5, 6, 4, 2)
(1, 3, 6, 2, 4, 5)
(1, 3, 6, 2, 5, 4)
(1, 3, 6, 4, 2, 5)
(1, 3, 6, 4, 5, 2)
(1, 3, 6, 5, 2, 4)
(1, 3, 6, 5, 4, 2)
(1, 4, 2, 3, 5, 6)
(1, 4, 2, 3, 6, 5)
(1, 4, 2, 5, 3, 6)
(1, 4, 2, 5, 6, 3)
(1, 4, 2, 6,