## order 4 magic triangles

In [2]:
import itertools


In [3]:
#we will use 1~16 and partition the 4x4 triangles into four 2x2 subtriangles.
#Then, we will assign four integers to each subtriangle without regarding internal order.
#Firstly, we will neglect equivalent figures due to rotation and reflection and corner swap, 
# which is a swapping between a corner triangle and an edge-adjacent triangle 

In [4]:
#             o
#            / \ 
#           o-- o
#          / \ / \ 
#        o-- o-- o
#       / \ / \ / \ 
#      o-- o-- o-- o
#     / \ / \ / \ / \ 
#    o---o---o-- o-- o

In [5]:
#             o
#            /b\ 
#           o-- o
#          /b\b/b\ 
#        o-- o-- o
#       /d\a/a\a/c\ 
#      o-- o-- o-- o
#     /d\d/d\a/c\c/c\ 
#    o---o---o-- o-- o

In [6]:
i=0
for A in itertools.permutations(range(1,17), 4):
    if A[0]+A[1]+A[2]+A[3]==34:
        #print(A,34)
        i+=1
print(i)

2064


In [7]:
# Firstly, we will find the number of ways to sellect four numbers from 1~16 which sum is 34.

In [8]:

i=0
for A in itertools.combinations(range(1,17), 4):
    if A[0]+A[1]+A[2]+A[3]==34:
        #print(A,34)
        i+=1
print(i)
group4=i

86


In [9]:
#There are 86 ways. we will save the results and 
#find the number of ways to sellect find the number of ways to sellect 8 numbers from 1~16 which are partioned into two groups and group sums are 34.
#intra-group order is ignored but inter-group order is not ignored.


In [10]:
pow(86,4)

54700816

In [11]:
import numpy as np
XX=np.zeros([group4,4],dtype=int)

In [12]:
XX=np.zeros([group4,4],dtype=int)
i=0
for A in itertools.combinations(range(1,17), 4):
    if A[0]+A[1]+A[2]+A[3]==34:
        XX[i]=A
        i+=1
print(i)

86


In [13]:
k=0
for i in range(group4):
    for j in range(group4):
        if len(set(list(XX[i])+list(XX[j])))==8:
            #print(i,j)
            k+=1
print(k)
group8=k

2150


In [14]:
AAA8=np.zeros([group8,8],dtype=int)
AAA2=np.zeros([group8,2],dtype=int)
k=0
for i in range(group4):
    for j in range(group4):
        if len(set(list(XX[i])+list(XX[j])))==8:
            AAA2[k,:]=np.array([i,j],dtype=int)
            AAA8[k,0:4]=XX[i]
            AAA8[k,4:8]=XX[j]
            k+=1
print(k)

2150


In [15]:
XX[j]

array([ 7,  8,  9, 10])

In [16]:
AAA8

array([[ 1,  2, 15, ...,  4, 13, 14],
       [ 1,  2, 15, ...,  5, 12, 14],
       [ 1,  2, 15, ...,  6, 11, 14],
       ...,
       [ 7,  8,  9, ...,  5, 12, 13],
       [ 7,  8,  9, ...,  6, 11, 13],
       [ 7,  8,  9, ...,  6, 11, 12]])

In [17]:
#find the number of ways to sellect find the number of ways to sellect 16 numbers from 1~16 which are partioned into 4 groups and group sums are 34.
#intra-group order is ignored but inter-group order is not ignored.


In [18]:

k=0
for i in range(group8):
    for j in range(group8):
        if len(set(list(AAA8[i])+list(AAA8[j])))==16:
            k+=1
print(k)
group16=k

9408


In [19]:
AAA2

array([[ 0, 40],
       [ 0, 43],
       [ 0, 46],
       ...,
       [85, 59],
       [85, 63],
       [85, 75]])

In [20]:
group16*pow(12,3)*4

65028096

In [21]:
#for first group, we can pick the central number and other numbers in the group are fixed by  disregarding rotation and reflection, 
#for other groups, they are fixed in corner swap, 
# which is a swapping between a corner triangle and an edge-adjacent triangle 

In [22]:
k=0
AAAA=np.zeros([group16,16],dtype=int)
AAAA4=np.zeros([group16,4],dtype=int)
for i in range(group8):
    for j in range(group8):
        if len(set(list(AAA8[i])+list(AAA8[j])))==16:
            AAAA4[k,0:2]=AAA2[i]
            AAAA4[k,2:4]=AAA2[j]
            AAAA[k,0:8]=AAA8[i]
            AAAA[k,8:16]=AAA8[j]
            k+=1
print(k)

9408


In [23]:

permute1=np.zeros([24,4],dtype=int)
i=0
for j in itertools.permutations(range(4), 4):
    permute1[i,:]=j
    i+=1

In [24]:
#making more efficient iterator by disregarding corner swap
permute0=permute1[range(0,24,2)]

In [25]:
permute0

array([[0, 1, 2, 3],
       [0, 2, 1, 3],
       [0, 3, 1, 2],
       [1, 0, 2, 3],
       [1, 2, 0, 3],
       [1, 3, 0, 2],
       [2, 0, 1, 3],
       [2, 1, 0, 3],
       [2, 3, 0, 1],
       [3, 0, 1, 2],
       [3, 1, 0, 2],
       [3, 2, 0, 1]])

In [26]:
#making more efficient iterator by disregarding ratation and reflection

In [27]:
permute4=permute1[range(0,24,6)]

In [28]:
permute4

array([[0, 1, 2, 3],
       [1, 0, 2, 3],
       [2, 0, 1, 3],
       [3, 0, 1, 2]])

In [29]:
#for central triangle, there are 4 ways to arrange numbers to neglect equivalent figures due to rotation and reflection
#for other triangle, there are 12 ways to arrange numbers to neglect equivalent figures due to corner swap.

In [30]:
#group number
#             o
#            /1\ 
#           o-- o
#          /1\1/1\ 
#        x-- o-- y
#       /3\0/0\0/2\ 
#      o-- o-- o-- o
#     /3\3/3\0/2\2/2\ 
#    o---o---z-- o-- o

In [31]:
# internal number
#             1
#            / \ 
#           o-- o
#          /0\ /1\ 
#        x-- o-- y
#       /1\2/0\3/0\ 
#      o-- o-- o-- o
#     / \ /0\1/1\ / \ 
#    3---o---z-- o-- 2

In [32]:
lens=0
for i in range(len(AAAA)):
    for j in range(4):
        temp0=AAAA[i,0:4][permute4[j]]
        for k in range(12):
            temp1=AAAA[i,4:8][permute0[k]]
            for l in range(12):
                temp2=AAAA[i,8:12][permute0[l]]
                for m in range(12):
                    temp3=AAAA[i,12:16][permute0[m]]
                    x=temp0[0]+temp0[2]+temp1[0]+temp3[1]
                    y=temp0[0]+temp0[3]+temp2[0]+temp1[1]
                    z=temp0[0]+temp0[1]+temp3[0]+temp2[1]
                    if x == 34 and y == 34 and z == 34:
                        if lens==0:
                            print(temp0,temp1,temp2,temp3)
                        lens+=1
print(lens)

[16  1  4 13] [ 6  2 11 15] [ 3 10  9 12] [ 7  8  5 14]
4792


In [33]:
print("total number for order 4 magic triangle(disregarding corner swap):", lens)

total number for order 4 magic triangle(disregarding corner swap): 4792


In [34]:
#If we think that swapping between a corner triangle and an edge-adjacent triangle generate different examples, the counts should be eight times as large.

In [35]:
print("total number for order 4 magic triangle(regarding corner swap):", lens*8)

total number for order 4 magic triangle(regarding corner swap): 38336
