tetrad-magic triangle

In [3]:
import itertools


In [10]:
i=0
for A in itertools.permutations(range(9), 9):
    m=A[0]+A[1]+A[2]+A[3]
    n=A[1]+A[4]+A[5]+A[6]
    o=A[3]+A[6]+A[7]+A[8]
    if m==n and n == o:
        print(A,m)
        i+=1
print(i)

(0, 1, 8, 6, 5, 7, 2, 3, 4) 15
(0, 1, 8, 6, 5, 7, 2, 4, 3) 15
(0, 1, 8, 6, 7, 5, 2, 3, 4) 15
(0, 1, 8, 6, 7, 5, 2, 4, 3) 15
(0, 1, 8, 7, 5, 6, 4, 2, 3) 16
(0, 1, 8, 7, 5, 6, 4, 3, 2) 16
(0, 1, 8, 7, 6, 5, 4, 2, 3) 16
(0, 1, 8, 7, 6, 5, 4, 3, 2) 16
(0, 2, 7, 6, 4, 8, 1, 3, 5) 15
(0, 2, 7, 6, 4, 8, 1, 5, 3) 15
(0, 2, 7, 6, 8, 4, 1, 3, 5) 15
(0, 2, 7, 6, 8, 4, 1, 5, 3) 15
(0, 2, 7, 8, 4, 6, 5, 1, 3) 17
(0, 2, 7, 8, 4, 6, 5, 3, 1) 17
(0, 2, 7, 8, 6, 4, 5, 1, 3) 17
(0, 2, 7, 8, 6, 4, 5, 3, 1) 17
(0, 2, 8, 6, 3, 7, 4, 1, 5) 16
(0, 2, 8, 6, 3, 7, 4, 5, 1) 16
(0, 2, 8, 6, 7, 3, 4, 1, 5) 16
(0, 2, 8, 6, 7, 3, 4, 5, 1) 16
(0, 2, 8, 7, 4, 5, 6, 1, 3) 17
(0, 2, 8, 7, 4, 5, 6, 3, 1) 17
(0, 2, 8, 7, 5, 4, 6, 1, 3) 17
(0, 2, 8, 7, 5, 4, 6, 3, 1) 17
(0, 3, 8, 5, 2, 7, 4, 1, 6) 16
(0, 3, 8, 5, 2, 7, 4, 6, 1) 16
(0, 3, 8, 5, 7, 2, 4, 1, 6) 16
(0, 3, 8, 5, 7, 2, 4, 6, 1) 16
(0, 4, 5, 7, 3, 8, 1, 2, 6) 16
(0, 4, 5, 7, 3, 8, 1, 6, 2) 16
(0, 4, 5, 7, 8, 3, 1, 2, 6) 16
(0, 4, 5, 7, 8, 3, 1, 6, 2) 16
(0, 4, 7

(7, 2, 3, 5, 1, 6, 8, 4, 0) 17
(7, 2, 3, 5, 6, 1, 8, 0, 4) 17
(7, 2, 3, 5, 6, 1, 8, 4, 0) 17
(7, 2, 5, 1, 3, 4, 6, 0, 8) 15
(7, 2, 5, 1, 3, 4, 6, 8, 0) 15
(7, 2, 5, 1, 4, 3, 6, 0, 8) 15
(7, 2, 5, 1, 4, 3, 6, 8, 0) 15
(7, 3, 2, 4, 0, 8, 5, 1, 6) 16
(7, 3, 2, 4, 0, 8, 5, 6, 1) 16
(7, 3, 2, 4, 8, 0, 5, 1, 6) 16
(7, 3, 2, 4, 8, 0, 5, 6, 1) 16
(7, 3, 5, 0, 2, 4, 6, 1, 8) 15
(7, 3, 5, 0, 2, 4, 6, 8, 1) 15
(7, 3, 5, 0, 4, 2, 6, 1, 8) 15
(7, 3, 5, 0, 4, 2, 6, 8, 1) 15
(7, 4, 0, 5, 1, 8, 3, 2, 6) 16
(7, 4, 0, 5, 1, 8, 3, 6, 2) 16
(7, 4, 0, 5, 8, 1, 3, 2, 6) 16
(7, 4, 0, 5, 8, 1, 3, 6, 2) 16
(7, 4, 2, 3, 1, 6, 5, 0, 8) 16
(7, 4, 2, 3, 1, 6, 5, 8, 0) 16
(7, 4, 2, 3, 6, 1, 5, 0, 8) 16
(7, 4, 2, 3, 6, 1, 5, 8, 0) 16
(7, 4, 3, 2, 1, 5, 6, 0, 8) 16
(7, 4, 3, 2, 1, 5, 6, 8, 0) 16
(7, 4, 3, 2, 5, 1, 6, 0, 8) 16
(7, 4, 3, 2, 5, 1, 6, 8, 0) 16
(7, 4, 5, 0, 1, 3, 8, 2, 6) 16
(7, 4, 5, 0, 1, 3, 8, 6, 2) 16
(7, 4, 5, 0, 3, 1, 8, 2, 6) 16
(7, 4, 5, 0, 3, 1, 8, 6, 2) 16
(7, 5, 0, 4, 2, 6, 3, 1, 8) 16
(7, 5, 0

In [13]:
i=0
for A in itertools.permutations(range(16), 16):
    if A[0]+A[1]+A[2]+A[3]==30:
        if A[4]+A[9]+A[10]+A[11]==30:
            if A[8]+A[13]+A[14]+A[15]==30:
                if A[1]+A[4]+A[5]+A[6]==30:
                    if A[3]+A[6]+A[7]+A[8]==30:
                        if A[6]+A[11]+A[12]+A[13]==30:
                            print(A,m)
                            i+=1
print(i)

KeyboardInterrupt: 

In [22]:
i=0
for A in itertools.permutations(range(16), 4):
    if A[0]+A[1]+A[2]+A[3]==30:
        print(A,30)
        i+=1
print(i)

(0, 1, 14, 15) 30
(0, 1, 15, 14) 30
(0, 2, 13, 15) 30
(0, 2, 15, 13) 30
(0, 3, 12, 15) 30
(0, 3, 13, 14) 30
(0, 3, 14, 13) 30
(0, 3, 15, 12) 30
(0, 4, 11, 15) 30
(0, 4, 12, 14) 30
(0, 4, 14, 12) 30
(0, 4, 15, 11) 30
(0, 5, 10, 15) 30
(0, 5, 11, 14) 30
(0, 5, 12, 13) 30
(0, 5, 13, 12) 30
(0, 5, 14, 11) 30
(0, 5, 15, 10) 30
(0, 6, 9, 15) 30
(0, 6, 10, 14) 30
(0, 6, 11, 13) 30
(0, 6, 13, 11) 30
(0, 6, 14, 10) 30
(0, 6, 15, 9) 30
(0, 7, 8, 15) 30
(0, 7, 9, 14) 30
(0, 7, 10, 13) 30
(0, 7, 11, 12) 30
(0, 7, 12, 11) 30
(0, 7, 13, 10) 30
(0, 7, 14, 9) 30
(0, 7, 15, 8) 30
(0, 8, 7, 15) 30
(0, 8, 9, 13) 30
(0, 8, 10, 12) 30
(0, 8, 12, 10) 30
(0, 8, 13, 9) 30
(0, 8, 15, 7) 30
(0, 9, 6, 15) 30
(0, 9, 7, 14) 30
(0, 9, 8, 13) 30
(0, 9, 10, 11) 30
(0, 9, 11, 10) 30
(0, 9, 13, 8) 30
(0, 9, 14, 7) 30
(0, 9, 15, 6) 30
(0, 10, 5, 15) 30
(0, 10, 6, 14) 30
(0, 10, 7, 13) 30
(0, 10, 8, 12) 30
(0, 10, 9, 11) 30
(0, 10, 11, 9) 30
(0, 10, 12, 8) 30
(0, 10, 13, 7) 30
(0, 10, 14, 6) 30
(0, 10, 15, 5) 30
(0, 11, 

(15, 4, 1, 10) 30
(15, 4, 2, 9) 30
(15, 4, 3, 8) 30
(15, 4, 5, 6) 30
(15, 4, 6, 5) 30
(15, 4, 8, 3) 30
(15, 4, 9, 2) 30
(15, 4, 10, 1) 30
(15, 4, 11, 0) 30
(15, 5, 0, 10) 30
(15, 5, 1, 9) 30
(15, 5, 2, 8) 30
(15, 5, 3, 7) 30
(15, 5, 4, 6) 30
(15, 5, 6, 4) 30
(15, 5, 7, 3) 30
(15, 5, 8, 2) 30
(15, 5, 9, 1) 30
(15, 5, 10, 0) 30
(15, 6, 0, 9) 30
(15, 6, 1, 8) 30
(15, 6, 2, 7) 30
(15, 6, 4, 5) 30
(15, 6, 5, 4) 30
(15, 6, 7, 2) 30
(15, 6, 8, 1) 30
(15, 6, 9, 0) 30
(15, 7, 0, 8) 30
(15, 7, 2, 6) 30
(15, 7, 3, 5) 30
(15, 7, 5, 3) 30
(15, 7, 6, 2) 30
(15, 7, 8, 0) 30
(15, 8, 0, 7) 30
(15, 8, 1, 6) 30
(15, 8, 2, 5) 30
(15, 8, 3, 4) 30
(15, 8, 4, 3) 30
(15, 8, 5, 2) 30
(15, 8, 6, 1) 30
(15, 8, 7, 0) 30
(15, 9, 0, 6) 30
(15, 9, 1, 5) 30
(15, 9, 2, 4) 30
(15, 9, 4, 2) 30
(15, 9, 5, 1) 30
(15, 9, 6, 0) 30
(15, 10, 0, 5) 30
(15, 10, 1, 4) 30
(15, 10, 2, 3) 30
(15, 10, 3, 2) 30
(15, 10, 4, 1) 30
(15, 10, 5, 0) 30
(15, 11, 0, 4) 30
(15, 11, 1, 3) 30
(15, 11, 3, 1) 30
(15, 11, 4, 0) 30
(15, 12, 0, 3) 3

In [18]:
pow(4128,4)

290374686867456

In [21]:

i=0
for A in itertools.combinations(range(16), 4):
    if A[0]+A[1]+A[2]+A[3]==30:
        print(A,30)
        i+=1
print(i)

(0, 1, 14, 15) 30
(0, 2, 13, 15) 30
(0, 3, 12, 15) 30
(0, 3, 13, 14) 30
(0, 4, 11, 15) 30
(0, 4, 12, 14) 30
(0, 5, 10, 15) 30
(0, 5, 11, 14) 30
(0, 5, 12, 13) 30
(0, 6, 9, 15) 30
(0, 6, 10, 14) 30
(0, 6, 11, 13) 30
(0, 7, 8, 15) 30
(0, 7, 9, 14) 30
(0, 7, 10, 13) 30
(0, 7, 11, 12) 30
(0, 8, 9, 13) 30
(0, 8, 10, 12) 30
(0, 9, 10, 11) 30
(1, 2, 12, 15) 30
(1, 2, 13, 14) 30
(1, 3, 11, 15) 30
(1, 3, 12, 14) 30
(1, 4, 10, 15) 30
(1, 4, 11, 14) 30
(1, 4, 12, 13) 30
(1, 5, 9, 15) 30
(1, 5, 10, 14) 30
(1, 5, 11, 13) 30
(1, 6, 8, 15) 30
(1, 6, 9, 14) 30
(1, 6, 10, 13) 30
(1, 6, 11, 12) 30
(1, 7, 8, 14) 30
(1, 7, 9, 13) 30
(1, 7, 10, 12) 30
(1, 8, 9, 12) 30
(1, 8, 10, 11) 30
(2, 3, 10, 15) 30
(2, 3, 11, 14) 30
(2, 3, 12, 13) 30
(2, 4, 9, 15) 30
(2, 4, 10, 14) 30
(2, 4, 11, 13) 30
(2, 5, 8, 15) 30
(2, 5, 9, 14) 30
(2, 5, 10, 13) 30
(2, 5, 11, 12) 30
(2, 6, 7, 15) 30
(2, 6, 8, 14) 30
(2, 6, 9, 13) 30
(2, 6, 10, 12) 30
(2, 7, 8, 13) 30
(2, 7, 9, 12) 30
(2, 7, 10, 11) 30
(2, 8, 9, 11) 30
(3, 4, 8, 1

In [26]:
pow(86,4)

54700816

In [27]:
import numpy as np
XX=np.zeros([86,4],dtype=int)

In [29]:
XX=np.zeros([86,4],dtype=int)
i=0
for A in itertools.combinations(range(16), 4):
    if A[0]+A[1]+A[2]+A[3]==30:
        XX[i]=A
        i+=1
print(i)

86


In [34]:
k=0
for i in range(86):
    for j in range(86):
        if len(set(list(XX[i])+list(XX[j])))==8:
            print(i,j)
            k+=1
print(k)

0 40
0 43
0 46
0 47
0 50
0 51
0 52
0 53
0 54
0 55
0 58
0 59
0 62
0 63
0 65
0 66
0 67
0 68
0 69
0 70
0 73
0 74
0 75
0 76
0 77
0 78
0 79
0 80
0 81
0 82
0 83
0 84
0 85
1 22
1 24
1 27
1 30
1 32
1 33
1 35
1 36
1 37
1 57
1 59
1 61
1 63
1 64
1 66
1 67
1 68
1 69
1 70
1 72
1 74
1 75
1 77
1 78
1 79
1 80
1 81
1 82
1 83
1 84
1 85
2 20
2 24
2 27
2 28
2 30
2 31
2 33
2 34
2 37
2 42
2 43
2 45
2 46
2 49
2 50
2 52
2 54
2 55
2 72
2 73
2 75
2 76
2 78
2 79
2 80
2 82
2 83
2 84
2 85
3 19
3 23
3 26
3 29
3 32
3 35
3 36
3 37
3 41
3 44
3 47
3 48
3 51
3 53
3 54
3 55
3 71
3 74
3 75
3 77
3 78
3 79
3 80
3 81
3 82
3 83
3 84
3 85
4 20
4 22
4 27
4 30
4 31
4 33
4 34
4 35
4 36
4 40
4 45
4 46
4 49
4 50
4 51
4 52
4 53
4 61
4 62
4 63
4 64
4 65
4 66
4 68
4 70
4 81
4 83
4 84
4 85
5 21
5 26
5 28
5 29
5 31
5 34
5 37
5 38
5 44
5 46
5 48
5 50
5 52
5 54
5 55
5 60
5 62
5 65
5 67
5 69
5 70
5 82
5 83
5 84
5 85
6 20
6 22
6 24
6 25
6 30
6 32
6 33
6 34
6 36
6 39
6 40
6 43
6 49
6 50
6 52
6 53
6 55
6 57
6 59
6 64
6 65
6 66
6 68
6 69
6 76


70 71
70 72
70 76
70 81
71 3
71 13
71 14
71 15
71 16
71 17
71 18
71 20
71 22
71 33
71 34
71 35
71 36
71 37
71 39
71 40
71 52
71 53
71 54
71 55
71 68
71 69
71 70
72 1
72 2
72 9
72 11
72 16
72 17
72 18
72 19
72 21
72 29
72 31
72 32
72 36
72 37
72 38
72 40
72 50
72 51
72 55
72 65
72 66
72 67
72 70
73 0
73 2
73 9
73 10
73 13
73 15
73 18
73 19
73 21
73 22
73 30
73 32
73 35
73 38
73 39
73 48
73 51
73 53
73 54
73 64
73 66
73 67
73 69
74 0
74 1
74 3
74 10
74 11
74 12
74 14
74 20
74 21
74 29
74 31
74 33
74 37
74 38
74 39
74 48
74 49
74 52
74 54
74 64
74 65
74 67
75 0
75 1
75 2
75 3
75 9
75 12
75 13
75 16
75 19
75 20
75 22
75 29
75 30
75 33
75 34
75 36
75 40
75 48
75 49
75 50
75 52
75 53
75 64
75 65
75 66
75 68
75 85
76 0
76 2
76 6
76 7
76 17
76 18
76 19
76 21
76 22
76 26
76 27
76 36
76 37
76 38
76 39
76 44
76 45
76 47
76 55
76 61
76 63
76 70
77 0
77 1
77 3
77 6
77 7
77 13
77 14
77 18
77 20
77 21
77 26
77 27
77 28
77 34
77 38
77 39
77 45
77 46
77 54
77 60
77 62
77 69
78 0
78 1
78 2
78 3
78 6
78 

In [44]:
AAA8=np.zeros([2150,8],dtype=int)
AAA2=np.zeros([2150,2],dtype=int)
k=0
for i in range(86):
    for j in range(86):
        if len(set(list(XX[i])+list(XX[j])))==8:
            AAA2[k,:]=np.array([i,j],dtype=int)
            AAA8[k,0:4]=XX[i]
            AAA8[k,4:8]=XX[j]
            k+=1
print(k)

2150


In [36]:
XX[j]

array([ 2,  3, 12, 13])

In [38]:
AAA8

array([[ 0,  1, 14, ...,  3, 12, 13],
       [ 0,  1, 14, ...,  4, 11, 13],
       [ 0,  1, 14, ...,  5, 10, 13],
       ...,
       [ 6,  7,  8, ...,  4, 11, 12],
       [ 6,  7,  8, ...,  5, 10, 12],
       [ 6,  7,  8, ...,  5, 10, 11]])

In [39]:

k=0
for i in range(2150):
    for j in range(2150):
        if len(set(list(AAA8[i])+list(AAA8[j])))==16:
            k+=1
print(k)

9408


In [45]:
AAA2

array([[ 0, 40],
       [ 0, 43],
       [ 0, 46],
       ...,
       [85, 59],
       [85, 63],
       [85, 75]])

In [42]:
9408*pow(24,3)*4

520224768

In [51]:
9408*pow(12,3)*4

65028096

In [46]:
k=0
AAAA=np.zeros([9408,16],dtype=int)
AAAA4=np.zeros([9408,4],dtype=int)
for i in range(2150):
    for j in range(2150):
        if len(set(list(AAA8[i])+list(AAA8[j])))==16:
            AAAA4[k,0:2]=AAA2[i]
            AAAA4[k,2:4]=AAA2[j]
            AAAA[k,0:8]=AAA8[i]
            AAAA[k,8:16]=AAA8[j]
            k+=1
print(k)

9408


In [50]:
for i in len(AAAA):
    for j in itertools.permutations(range(4), 2):
        for k in itertools.permutations(range(4), 2):
            for l in itertools.permutations(range(4), 2):
                for m in itertools.permutations(range(4), 1):

array([[ 0,  1, 14, ...,  7,  8,  9],
       [ 0,  1, 14, ...,  7,  8, 10],
       [ 0,  1, 14, ...,  6,  9, 10],
       ...,
       [ 6,  7,  8, ...,  3, 12, 15],
       [ 6,  7,  8, ...,  2, 13, 15],
       [ 6,  7,  8, ...,  1, 14, 15]])

In [58]:
permute1=np.zeros([24,4],dtype=int)
i=0
for j in itertools.permutations(range(4), 4):
    permute1[i,:]=j
    i+=1

In [61]:
permute0=permute1[range(0,24,2)]

In [62]:
permute0

array([[0, 1, 2, 3],
       [0, 2, 1, 3],
       [0, 3, 1, 2],
       [1, 0, 2, 3],
       [1, 2, 0, 3],
       [1, 3, 0, 2],
       [2, 0, 1, 3],
       [2, 1, 0, 3],
       [2, 3, 0, 1],
       [3, 0, 1, 2],
       [3, 1, 0, 2],
       [3, 2, 0, 1]])

In [64]:
permute4=permute1[range(0,24,6)]

In [65]:
permute4

array([[0, 1, 2, 3],
       [1, 0, 2, 3],
       [2, 0, 1, 3],
       [3, 0, 1, 2]])

In [78]:
lens=0
for i in range(len(AAAA)):
    for j in range(4):
        temp0=AAAA[i,0:4][permute4[j]]
        for k in range(12):
            temp1=AAAA[i,4:8][permute0[k]]
            for l in range(12):
                temp2=AAAA[i,8:12][permute0[l]]
                for m in range(12):
                    temp3=AAAA[i,12:16][permute0[m]]
                    x=temp0[0]+temp0[2]+temp1[0]+temp3[1]
                    y=temp0[0]+temp0[3]+temp2[0]+temp1[1]
                    z=temp0[0]+temp0[1]+temp3[0]+temp2[1]
                    if x == 30 and y == 30 and z == 30:
                        print(temp0,temp1,temp2,temp3)
                        lens+=1
print(lens)

[15  0  3 12] [ 5  1 10 14] [ 2  9  8 11] [ 6  7  4 13]
[15  0  3 12] [ 5  1 10 14] [ 2 11  8  9] [ 4  7  6 13]
[12  0  3 15] [ 5  1 11 13] [ 2 14  6  8] [ 4 10  7  9]
[12  0  3 15] [11  1  5 13] [ 2  8  6 14] [10  4  7  9]
[15  0  3 12] [ 5  1 11 13] [ 2  6  8 14] [ 9  7  4 10]
[12  0  3 15] [10  1  6 13] [ 2 11  8  9] [ 7  5  4 14]
[12  0  3 15] [ 9  1  7 13] [ 2 10  4 14] [ 8  6  5 11]
[15  0  3 12] [ 7  1  9 13] [ 2  4 10 14] [11  5  6  8]
[ 0  3 12 15] [11 10  1  8] [ 5 14  2  9] [13  7  4  6]
[ 3  0 12 15] [ 8 10  1 11] [ 2 14  5  9] [13  7  4  6]
[ 3  0 12 15] [11 10  1  8] [ 2 14  5  9] [13  4  6  7]
[12  0  3 15] [ 8  1 10 11] [ 2  5  9 14] [13  7  4  6]
[12  0  3 15] [ 8  1 10 11] [ 2 14  5  9] [ 4  7  6 13]
[12  0  3 15] [11  1  8 10] [ 2  5  9 14] [13  4  6  7]
[15  0  3 12] [ 8  1 10 11] [ 2  9  5 14] [ 6  4  7 13]
[ 3  0 12 15] [ 8 10  1 11] [ 2 13  6  9] [14  7  4  5]
[ 3  0 12 15] [11 10  1  8] [ 2 13  6  9] [14  4  5  7]
[12  0  3 15] [ 8  1 10 11] [ 2 13  6  9] [ 5  7

[ 4  0 11 15] [13  6  1 10] [ 5 14  3  8] [12  2  7  9]
[ 0  4 11 15] [ 9  7  1 13] [ 8 14  2  6] [12 10  3  5]
[ 0  4 11 15] [ 9 13  1  7] [ 2 14  6  8] [12 10  3  5]
[ 4  0 11 15] [ 7  1  9 13] [10 12  2  6] [14  8  3  5]
[ 4  0 11 15] [ 7  9  1 13] [ 2 12  6 10] [14  8  3  5]
[ 0  4 11 15] [ 9  7  1 13] [ 8 14  3  5] [12 10  2  6]
[ 0  4 11 15] [13  7  1  9] [ 8 14  3  5] [12  6  2 10]
[15  0  4 11] [ 9  1  7 13] [ 3  5  8 14] [10  2  6 12]
[ 4  0 11 15] [ 7  1  9 13] [10 12  3  5] [14  8  2  6]
[ 4  0 11 15] [ 9  1  7 13] [10 12  3  5] [14  6  2  8]
[ 4  0 11 15] [13  1  7  9] [10 12  3  5] [14  2  6  8]
[11  0  4 15] [ 7  1  9 13] [ 3  5 10 12] [14  8  2  6]
[11  0  4 15] [ 9  1  7 13] [ 3  5 10 12] [14  6  2  8]
[11  0  4 15] [13  1  7  9] [ 3  5 10 12] [14  2  6  8]
[11  0  4 15] [ 7  1 10 12] [ 3  5  9 13] [14  8  2  6]
[11  0  4 15] [ 7  1 10 12] [ 3 13  5  9] [ 6  8  2 14]
[11  0  4 15] [ 8  3  5 14] [ 1 10  6 13] [ 9  7  2 12]
[11  0  4 15] [ 5  3  8 14] [ 1  7  9 13] [12 10

[ 5  0 11 14] [12  8  1  9] [ 3 10  4 13] [15  2  6  7]
[11  0  5 14] [12  1  8  9] [ 4 13  3 10] [ 6  2  7 15]
[14  0  5 11] [ 9  1  8 12] [ 4 10  3 13] [ 6  2  7 15]
[14  0  5 11] [ 8  1  9 12] [ 4  6  7 13] [10  3  2 15]
[14  0  5 11] [ 9  1  8 12] [ 4  6  7 13] [10  2  3 15]
[14  0  5 11] [ 9  1  8 12] [ 4 13  6  7] [ 3  2 10 15]
[ 5  0 11 14] [10  2  3 15] [ 9 13  1  7] [12  4  6  8]
[ 5  0 11 14] [10  2  3 15] [ 9 12  1  8] [13  4  6  7]
[ 5  0 11 14] [10  3  2 15] [ 8 12  1  9] [13  4  6  7]
[ 0  5 11 14] [13 12  2  3] [ 4 10  7  9] [15  6  1  8]
[ 5  0 11 14] [13  2  3 12] [ 9 10  4  7] [15  1  6  8]
[14  0  5 11] [ 4  2  9 15] [ 3  6  8 13] [10  7  1 12]
[ 0  5 11 14] [15  7  2  6] [ 9 12  1  8] [13  4  3 10]
[ 5  0 11 14] [ 6  7  2 15] [ 4 13  3 10] [12  8  1  9]
[11  0  5 14] [ 6  2  7 15] [ 3 10  4 13] [ 9  8  1 12]
[11  0  5 14] [13  2  7  8] [ 3  9  6 12] [10  1  4 15]
[14  0  5 11] [ 7  2  8 13] [ 3  6  9 12] [10  4  1 15]
[14  0  5 11] [ 7  2  9 12] [ 3  6  8 13] [10  4

[15  0  6  9] [ 7  5  8 10] [ 1  4 12 13] [11  2  3 14]
[15  0  6  9] [ 7  5  8 10] [ 1 12  4 13] [ 3  2 11 14]
[14  0  6 10] [ 2  1 12 15] [ 5  9  3 13] [ 7  8  4 11]
[14  0  6 10] [ 1  2 12 15] [ 4  5  8 13] [11  9  3  7]
[14  0  6 10] [ 1  2 12 15] [ 4 13  5  8] [ 3  9  7 11]
[ 0  6 10 14] [15 12  1  2] [ 4 11  7  8] [13  5  3  9]
[10  0  6 14] [ 1  2 12 15] [ 4 11  7  8] [ 9 13  3  5]
[14  0  6 10] [ 1  2 12 15] [ 4 11  7  8] [ 5  9  3 13]
[14  0  6 10] [ 3  1 11 15] [ 5  4  8 13] [12  7  2  9]
[14  0  6 10] [ 1  4 12 13] [ 2  5  8 15] [11  9  3  7]
[ 0  6 10 14] [12 13  1  4] [ 3 15  5  7] [ 9  8  2 11]
[ 0  6 10 14] [12 13  1  4] [ 3  9  7 11] [15  8  2  5]
[14  0  6 10] [ 7  1  9 13] [ 5 12  2 11] [ 4  3  8 15]
[10  0  6 14] [12  1  8  9] [ 5  7  3 15] [13  2  4 11]
[14  0  6 10] [ 8  1  9 12] [ 5  3  7 15] [13  2  4 11]
[10  0  6 14] [13  2  3 12] [ 4 11  7  8] [ 9  1  5 15]
[ 0  6 10 14] [13  4  2 11] [12  9  1  8] [15  7  3  5]
[ 6  0 10 14] [11  2  4 13] [ 8  9  1 12] [15  3

[ 8  0  7 15] [12  2  6 10] [ 5 13  1 11] [ 9  3  4 14]
[ 8  0  7 15] [12  6  2 10] [ 1 13  5 11] [ 9  3  4 14]
[ 7  0  8 15] [ 9  3  4 14] [ 5 11  1 13] [12  6  2 10]
[ 7  0  8 15] [ 9  3  4 14] [ 5 13  1 11] [10  6  2 12]
[ 8  0  7 15] [ 9  3  5 13] [ 4 10  2 14] [12  6  1 11]
[ 8  0  7 15] [ 9  5  3 13] [ 2 10  4 14] [12  6  1 11]
[ 7  0  8 15] [ 3  6 10 11] [ 2 14  1 13] [ 9 12  4  5]
[ 7  0  8 15] [10  6  3 11] [ 2 14  1 13] [ 9  5  4 12]
[ 7  0  8 15] [11  6  3 10] [ 2 14  1 13] [ 9  4  5 12]
[ 8  0  7 15] [ 3  6 10 11] [ 1 13  2 14] [ 9 12  4  5]
[ 8  0  7 15] [10  6  3 11] [ 1 13  2 14] [ 9  5  4 12]
[ 8  0  7 15] [11  6  3 10] [ 1 13  2 14] [ 9  4  5 12]
[ 8  0  7 15] [10  3  6 11] [ 4 13  1 12] [ 9  5  2 14]
[ 8  0  7 15] [10  6  3 11] [ 1 13  4 12] [ 9  5  2 14]
[15  0  7  8] [ 3  6 10 11] [ 1 13  4 12] [ 2  5  9 14]
[15  0  7  8] [ 6  3 10 11] [ 4  1 12 13] [14  2  5  9]
[15  0  7  8] [ 5  6  9 10] [ 1  4 12 13] [11  3  2 14]
[15  0  7  8] [ 5  6  9 10] [ 1 13  4 12] [ 2  3

[ 7  0 10 13] [12  8  4  6] [ 2 14  3 11] [ 9  1  5 15]
[10  0  7 13] [ 8  4  6 12] [ 3 11  2 14] [ 9  5  1 15]
[10  0  7 13] [12  4  6  8] [ 3 11  2 14] [ 9  1  5 15]
[10  0  7 13] [11  4  6  9] [ 3 12  1 14] [ 8  2  5 15]
[10  0  7 13] [11  6  4  9] [ 1 12  3 14] [ 8  2  5 15]
[10  0  7 13] [11  4  6  9] [ 3  5  8 14] [15  2  1 12]
[10  0  7 13] [11  4  6  9] [ 3  8  5 14] [12  2  1 15]
[13  0  7 10] [ 9  4  6 11] [ 3  5  8 14] [12  1  2 15]
[12  0  7 11] [ 1  2 13 14] [ 5 15  4  6] [ 3 10  8  9]
[12  0  7 11] [ 2  1 13 14] [ 6 15  4  5] [ 3  9  8 10]
[11  0  7 12] [10  4  1 15] [ 3  5  9 13] [14  2  6  8]
[11  0  7 12] [10  4  1 15] [ 3 13  5  9] [ 6  2  8 14]
[11  0  7 12] [ 9  5  1 15] [ 2  6  8 14] [13  3  4 10]
[12  0  7 11] [ 1  5  9 15] [ 2 14  6  8] [ 4 10  3 13]
[ 0  7 11 12] [ 5 15  1  9] [ 3 13  6  8] [10 14  2  4]
[12  0  7 11] [ 9  1  5 15] [ 6  8  3 13] [10  2  4 14]
[ 0  7 11 12] [10  5  1 14] [13  8  3  6] [15  9  2  4]
[ 7  0 11 12] [10  5  1 14] [ 6  8  3 13] [15  2

[11  0  9 10] [ 3  1 12 14] [ 8  4  5 13] [15  7  2  6]
[11  0  9 10] [ 3  1 12 14] [ 8 13  4  5] [ 6  7  2 15]
[11  0  9 10] [ 4  1 12 13] [ 8  5  2 15] [14  6  3  7]
[ 0  9 10 11] [12  4  1 13] [15  7  2  6] [14  8  3  5]
[ 0  9 10 11] [12 13  1  4] [ 6  7  2 15] [14  8  3  5]
[ 0  9 10 11] [12  4  1 13] [15  7  3  5] [14  8  2  6]
[10  0  9 11] [ 4  1 12 13] [ 8  5  3 14] [15  7  2  6]
[10  0  9 11] [ 4  1 12 13] [ 8 14  3  5] [ 6  7  2 15]
[11  0  9 10] [ 2  3 12 13] [ 6  5  4 15] [14  8  1  7]
[10  0  9 11] [ 3  2 12 13] [ 7  5  4 14] [15  8  1  6]
[10  0  9 11] [ 3  2 12 13] [ 7 14  4  5] [ 6  8  1 15]
[10  0  9 11] [ 5  8  2 15] [ 1 13  4 12] [ 7  6  3 14]
[10  0  9 11] [ 8  5  2 15] [ 4 13  1 12] [ 7  3  6 14]
[ 0  9 10 11] [ 8 15  2  5] [ 4  7  6 13] [14 12  1  3]
[10  0  9 11] [ 8  2  5 15] [ 7  6  4 13] [14  3  1 12]
[10  0  9 11] [ 8  5  2 15] [ 4  6  7 13] [14  3  1 12]
[10  0  9 11] [ 7  6  2 15] [ 3 12  1 14] [ 8  4  5 13]
[11  0  9 10] [ 2  6  7 15] [ 3 14  1 12] [ 5  8

[ 1  2 12 15] [ 8 11  5  6] [ 3 13  4 10] [14  9  0  7]
[ 2  1 12 15] [ 5 10  7  8] [ 3 14  4  9] [13 11  0  6]
[ 1  2 12 15] [7 9 6 8] [ 5 14  0 11] [13 10  3  4]
[ 2  1 12 15] [6 8 7 9] [ 5 14  0 11] [13 10  3  4]
[14  1  2 13] [10  0  5 15] [ 3  7  9 11] [ 8  4  6 12]
[14  1  2 13] [10  0  5 15] [ 3  9  7 11] [ 6  4  8 12]
[13  1  2 14] [11  0  7 12] [ 3 10  8  9] [ 6  4  5 15]
[14  1  2 13] [ 8  0 10 12] [ 3 11  7  9] [ 4  6  5 15]
[14  1  2 13] [10  0  8 12] [ 3  9  7 11] [ 6  4  5 15]
[ 1  2 13 14] [ 9 11  0 10] [ 4 15  3  8] [12  7  5  6]
[ 1  2 13 14] [10 11  0  9] [ 4 15  3  8] [12  6  5  7]
[ 2  1 13 14] [ 9 10  0 11] [ 4 15  3  8] [12  6  5  7]
[ 2  1 13 14] [ 9 11  0 10] [ 3 15  4  8] [12  6  5  7]
[ 2  1 13 14] [10 11  0  9] [ 3 15  4  8] [12  5  6  7]
[13  1  2 14] [ 9  0 10 11] [ 3  4  8 15] [12  6  5  7]
[13  1  2 14] [10  0  9 11] [ 3  4  8 15] [12  5  6  7]
[14  1  2 13] [ 9  0 10 11] [ 3  8  4 15] [ 7  5  6 12]
[ 2  1 13 14] [ 9 11  0 10] [ 3 15  5  7] [12  6  4  8]


[14  1  3 12] [11  0  9 10] [ 4  8  5 13] [ 7  2  6 15]
[14  1  3 12] [11  0  9 10] [ 4  7  6 13] [ 8  2  5 15]
[14  1  3 12] [ 2  4  9 15] [ 0  7 10 13] [ 8 11  5  6]
[14  1  3 12] [ 2  4  9 15] [ 0 10  7 13] [ 5 11  6  8]
[14  1  3 12] [ 5  4  6 15] [ 0 13  7 10] [ 2  8  9 11]
[14  1  3 12] [ 6  4  5 15] [ 0 13  8  9] [ 2  7 10 11]
[ 3  1 12 14] [ 5  4  8 13] [ 9 15  0  6] [11 10  2  7]
[ 3  1 12 14] [ 5 13  4  8] [ 0 15  6  9] [11 10  2  7]
[ 3  1 12 14] [ 8  4  5 13] [ 9 15  0  6] [11  7  2 10]
[ 3  1 12 14] [ 8 13  4  5] [ 0 15  6  9] [11  7  2 10]
[ 3  1 12 14] [13  4  5  8] [ 9 15  0  6] [11  2  7 10]
[12  1  3 14] [ 5  4  8 13] [ 0  6  9 15] [11 10  2  7]
[12  1  3 14] [ 5  4  8 13] [ 0 15  6  9] [ 2 10  7 11]
[12  1  3 14] [ 8  4  5 13] [ 0  6  9 15] [11  7  2 10]
[12  1  3 14] [ 8  4  5 13] [ 0 15  6  9] [ 2  7 10 11]
[12  1  3 14] [13  4  5  8] [ 0  6  9 15] [11  2  7 10]
[ 3  1 12 14] [ 8  4  5 13] [ 9 11  0 10] [15  7  2  6]
[ 3  1 12 14] [ 8 13  4  5] [ 0 11  9 10] [15  7

[14  1  4 11] [10  5  3 12] [ 0  8  9 13] [ 7  2  6 15]
[14  1  4 11] [10  5  3 12] [ 0  9  8 13] [ 6  2  7 15]
[14  1  4 11] [12  3  5 10] [ 2  6  7 15] [ 9  0  8 13]
[14  1  4 11] [12  3  5 10] [ 2  7  6 15] [ 8  0  9 13]
[14  1  4 11] [12  3  6  9] [ 2  5  8 15] [10  0  7 13]
[14  1  4 11] [12  3  6  9] [ 2  8  5 15] [ 7  0 10 13]
[ 4  1 11 14] [ 8 10  3  9] [ 2 13  0 15] [12  7  5  6]
[ 4  1 11 14] [ 9 10  3  8] [ 2 13  0 15] [12  6  5  7]
[11  1  4 14] [ 8  3  9 10] [ 2 13  0 15] [ 5  7  6 12]
[11  1  4 14] [ 9  3  8 10] [ 2 13  0 15] [ 5  6  7 12]
[11  1  4 14] [10  3  8  9] [ 2  6  7 15] [12  5  0 13]
[ 1  4 11 14] [ 3  8  9 10] [ 7 12  5  6] [13 15  0  2]
[ 1  4 11 14] [ 3  9  8 10] [ 6 12  5  7] [13 15  0  2]
[ 1  4 11 14] [ 3 10  8  9] [ 5 12  6  7] [13 15  0  2]
[ 4  1 11 14] [ 6 12  5  7] [ 0 15  2 13] [10  9  3  8]
[ 4  1 11 14] [ 7 12  5  6] [ 0 15  2 13] [10  8  3  9]
[11  1  4 14] [ 6  5  7 12] [ 0 15  2 13] [ 3  9  8 10]
[11  1  4 14] [ 7  5  6 12] [ 0 15  2 13] [ 3  8

KeyboardInterrupt: 

In [79]:
lens

1435

In [82]:
lens=0
for i in range(len(AAAA)):
    for j in range(4):
        temp0=AAAA[i,0:4][permute4[j]]
        for k in range(12):
            temp1=AAAA[i,4:8][permute0[k]]
            for l in range(12):
                temp2=AAAA[i,8:12][permute0[l]]
                for m in range(12):
                    temp3=AAAA[i,12:16][permute0[m]]
                    x=temp0[0]+temp0[2]+temp1[0]+temp3[1]
                    y=temp0[0]+temp0[3]+temp2[0]+temp1[1]
                    z=temp0[0]+temp0[1]+temp3[0]+temp2[1]
                    if x == 30 and y == 30 and z == 30:
                        print(temp0,temp1,temp2,temp3)
                        lens+=1
print(lens)

[15  0  3 12] [ 5  1 10 14] [ 2  9  8 11] [ 6  7  4 13]
[15  0  3 12] [ 5  1 10 14] [ 2 11  8  9] [ 4  7  6 13]
[12  0  3 15] [ 5  1 11 13] [ 2 14  6  8] [ 4 10  7  9]
[12  0  3 15] [11  1  5 13] [ 2  8  6 14] [10  4  7  9]
[15  0  3 12] [ 5  1 11 13] [ 2  6  8 14] [ 9  7  4 10]
[12  0  3 15] [10  1  6 13] [ 2 11  8  9] [ 7  5  4 14]
[12  0  3 15] [ 9  1  7 13] [ 2 10  4 14] [ 8  6  5 11]
[15  0  3 12] [ 7  1  9 13] [ 2  4 10 14] [11  5  6  8]
[ 0  3 12 15] [11 10  1  8] [ 5 14  2  9] [13  7  4  6]
[ 3  0 12 15] [ 8 10  1 11] [ 2 14  5  9] [13  7  4  6]
[ 3  0 12 15] [11 10  1  8] [ 2 14  5  9] [13  4  6  7]
[12  0  3 15] [ 8  1 10 11] [ 2  5  9 14] [13  7  4  6]
[12  0  3 15] [ 8  1 10 11] [ 2 14  5  9] [ 4  7  6 13]
[12  0  3 15] [11  1  8 10] [ 2  5  9 14] [13  4  6  7]
[15  0  3 12] [ 8  1 10 11] [ 2  9  5 14] [ 6  4  7 13]
[ 3  0 12 15] [ 8 10  1 11] [ 2 13  6  9] [14  7  4  5]
[ 3  0 12 15] [11 10  1  8] [ 2 13  6  9] [14  4  5  7]
[12  0  3 15] [ 8  1 10 11] [ 2 13  6  9] [ 5  7

[ 4  0 11 15] [13  6  1 10] [ 5 14  3  8] [12  2  7  9]
[ 0  4 11 15] [ 9  7  1 13] [ 8 14  2  6] [12 10  3  5]
[ 0  4 11 15] [ 9 13  1  7] [ 2 14  6  8] [12 10  3  5]
[ 4  0 11 15] [ 7  1  9 13] [10 12  2  6] [14  8  3  5]
[ 4  0 11 15] [ 7  9  1 13] [ 2 12  6 10] [14  8  3  5]
[ 0  4 11 15] [ 9  7  1 13] [ 8 14  3  5] [12 10  2  6]
[ 0  4 11 15] [13  7  1  9] [ 8 14  3  5] [12  6  2 10]
[15  0  4 11] [ 9  1  7 13] [ 3  5  8 14] [10  2  6 12]
[ 4  0 11 15] [ 7  1  9 13] [10 12  3  5] [14  8  2  6]
[ 4  0 11 15] [ 9  1  7 13] [10 12  3  5] [14  6  2  8]
[ 4  0 11 15] [13  1  7  9] [10 12  3  5] [14  2  6  8]
[11  0  4 15] [ 7  1  9 13] [ 3  5 10 12] [14  8  2  6]
[11  0  4 15] [ 9  1  7 13] [ 3  5 10 12] [14  6  2  8]
[11  0  4 15] [13  1  7  9] [ 3  5 10 12] [14  2  6  8]
[11  0  4 15] [ 7  1 10 12] [ 3  5  9 13] [14  8  2  6]
[11  0  4 15] [ 7  1 10 12] [ 3 13  5  9] [ 6  8  2 14]
[11  0  4 15] [ 8  3  5 14] [ 1 10  6 13] [ 9  7  2 12]
[11  0  4 15] [ 5  3  8 14] [ 1  7  9 13] [12 10

[ 5  0 11 14] [12  8  1  9] [ 3 10  4 13] [15  2  6  7]
[11  0  5 14] [12  1  8  9] [ 4 13  3 10] [ 6  2  7 15]
[14  0  5 11] [ 9  1  8 12] [ 4 10  3 13] [ 6  2  7 15]
[14  0  5 11] [ 8  1  9 12] [ 4  6  7 13] [10  3  2 15]
[14  0  5 11] [ 9  1  8 12] [ 4  6  7 13] [10  2  3 15]
[14  0  5 11] [ 9  1  8 12] [ 4 13  6  7] [ 3  2 10 15]
[ 5  0 11 14] [10  2  3 15] [ 9 13  1  7] [12  4  6  8]
[ 5  0 11 14] [10  2  3 15] [ 9 12  1  8] [13  4  6  7]
[ 5  0 11 14] [10  3  2 15] [ 8 12  1  9] [13  4  6  7]
[ 0  5 11 14] [13 12  2  3] [ 4 10  7  9] [15  6  1  8]
[ 5  0 11 14] [13  2  3 12] [ 9 10  4  7] [15  1  6  8]
[14  0  5 11] [ 4  2  9 15] [ 3  6  8 13] [10  7  1 12]
[ 0  5 11 14] [15  7  2  6] [ 9 12  1  8] [13  4  3 10]
[ 5  0 11 14] [ 6  7  2 15] [ 4 13  3 10] [12  8  1  9]
[11  0  5 14] [ 6  2  7 15] [ 3 10  4 13] [ 9  8  1 12]
[11  0  5 14] [13  2  7  8] [ 3  9  6 12] [10  1  4 15]
[14  0  5 11] [ 7  2  8 13] [ 3  6  9 12] [10  4  1 15]
[14  0  5 11] [ 7  2  9 12] [ 3  6  8 13] [10  4

[15  0  6  9] [ 7  5  8 10] [ 1  4 12 13] [11  2  3 14]
[15  0  6  9] [ 7  5  8 10] [ 1 12  4 13] [ 3  2 11 14]
[14  0  6 10] [ 2  1 12 15] [ 5  9  3 13] [ 7  8  4 11]
[14  0  6 10] [ 1  2 12 15] [ 4  5  8 13] [11  9  3  7]
[14  0  6 10] [ 1  2 12 15] [ 4 13  5  8] [ 3  9  7 11]
[ 0  6 10 14] [15 12  1  2] [ 4 11  7  8] [13  5  3  9]
[10  0  6 14] [ 1  2 12 15] [ 4 11  7  8] [ 9 13  3  5]
[14  0  6 10] [ 1  2 12 15] [ 4 11  7  8] [ 5  9  3 13]
[14  0  6 10] [ 3  1 11 15] [ 5  4  8 13] [12  7  2  9]
[14  0  6 10] [ 1  4 12 13] [ 2  5  8 15] [11  9  3  7]
[ 0  6 10 14] [12 13  1  4] [ 3 15  5  7] [ 9  8  2 11]
[ 0  6 10 14] [12 13  1  4] [ 3  9  7 11] [15  8  2  5]
[14  0  6 10] [ 7  1  9 13] [ 5 12  2 11] [ 4  3  8 15]
[10  0  6 14] [12  1  8  9] [ 5  7  3 15] [13  2  4 11]
[14  0  6 10] [ 8  1  9 12] [ 5  3  7 15] [13  2  4 11]
[10  0  6 14] [13  2  3 12] [ 4 11  7  8] [ 9  1  5 15]
[ 0  6 10 14] [13  4  2 11] [12  9  1  8] [15  7  3  5]
[ 6  0 10 14] [11  2  4 13] [ 8  9  1 12] [15  3

[ 8  0  7 15] [12  2  6 10] [ 5 13  1 11] [ 9  3  4 14]
[ 8  0  7 15] [12  6  2 10] [ 1 13  5 11] [ 9  3  4 14]
[ 7  0  8 15] [ 9  3  4 14] [ 5 11  1 13] [12  6  2 10]
[ 7  0  8 15] [ 9  3  4 14] [ 5 13  1 11] [10  6  2 12]
[ 8  0  7 15] [ 9  3  5 13] [ 4 10  2 14] [12  6  1 11]
[ 8  0  7 15] [ 9  5  3 13] [ 2 10  4 14] [12  6  1 11]
[ 7  0  8 15] [ 3  6 10 11] [ 2 14  1 13] [ 9 12  4  5]
[ 7  0  8 15] [10  6  3 11] [ 2 14  1 13] [ 9  5  4 12]
[ 7  0  8 15] [11  6  3 10] [ 2 14  1 13] [ 9  4  5 12]
[ 8  0  7 15] [ 3  6 10 11] [ 1 13  2 14] [ 9 12  4  5]
[ 8  0  7 15] [10  6  3 11] [ 1 13  2 14] [ 9  5  4 12]
[ 8  0  7 15] [11  6  3 10] [ 1 13  2 14] [ 9  4  5 12]
[ 8  0  7 15] [10  3  6 11] [ 4 13  1 12] [ 9  5  2 14]
[ 8  0  7 15] [10  6  3 11] [ 1 13  4 12] [ 9  5  2 14]
[15  0  7  8] [ 3  6 10 11] [ 1 13  4 12] [ 2  5  9 14]
[15  0  7  8] [ 6  3 10 11] [ 4  1 12 13] [14  2  5  9]
[15  0  7  8] [ 5  6  9 10] [ 1  4 12 13] [11  3  2 14]
[15  0  7  8] [ 5  6  9 10] [ 1 13  4 12] [ 2  3

[ 7  0 10 13] [12  8  4  6] [ 2 14  3 11] [ 9  1  5 15]
[10  0  7 13] [ 8  4  6 12] [ 3 11  2 14] [ 9  5  1 15]
[10  0  7 13] [12  4  6  8] [ 3 11  2 14] [ 9  1  5 15]
[10  0  7 13] [11  4  6  9] [ 3 12  1 14] [ 8  2  5 15]
[10  0  7 13] [11  6  4  9] [ 1 12  3 14] [ 8  2  5 15]
[10  0  7 13] [11  4  6  9] [ 3  5  8 14] [15  2  1 12]
[10  0  7 13] [11  4  6  9] [ 3  8  5 14] [12  2  1 15]
[13  0  7 10] [ 9  4  6 11] [ 3  5  8 14] [12  1  2 15]
[12  0  7 11] [ 1  2 13 14] [ 5 15  4  6] [ 3 10  8  9]
[12  0  7 11] [ 2  1 13 14] [ 6 15  4  5] [ 3  9  8 10]
[11  0  7 12] [10  4  1 15] [ 3  5  9 13] [14  2  6  8]
[11  0  7 12] [10  4  1 15] [ 3 13  5  9] [ 6  2  8 14]
[11  0  7 12] [ 9  5  1 15] [ 2  6  8 14] [13  3  4 10]
[12  0  7 11] [ 1  5  9 15] [ 2 14  6  8] [ 4 10  3 13]
[ 0  7 11 12] [ 5 15  1  9] [ 3 13  6  8] [10 14  2  4]
[12  0  7 11] [ 9  1  5 15] [ 6  8  3 13] [10  2  4 14]
[ 0  7 11 12] [10  5  1 14] [13  8  3  6] [15  9  2  4]
[ 7  0 11 12] [10  5  1 14] [ 6  8  3 13] [15  2

[11  0  9 10] [ 3  1 12 14] [ 8 15  2  5] [ 4  7  6 13]
[11  0  9 10] [ 3  1 12 14] [ 8  4  5 13] [15  7  2  6]
[11  0  9 10] [ 3  1 12 14] [ 8 13  4  5] [ 6  7  2 15]
[11  0  9 10] [ 4  1 12 13] [ 8  5  2 15] [14  6  3  7]
[ 0  9 10 11] [12  4  1 13] [15  7  2  6] [14  8  3  5]
[ 0  9 10 11] [12 13  1  4] [ 6  7  2 15] [14  8  3  5]
[ 0  9 10 11] [12  4  1 13] [15  7  3  5] [14  8  2  6]
[10  0  9 11] [ 4  1 12 13] [ 8  5  3 14] [15  7  2  6]
[10  0  9 11] [ 4  1 12 13] [ 8 14  3  5] [ 6  7  2 15]
[11  0  9 10] [ 2  3 12 13] [ 6  5  4 15] [14  8  1  7]
[10  0  9 11] [ 3  2 12 13] [ 7  5  4 14] [15  8  1  6]
[10  0  9 11] [ 3  2 12 13] [ 7 14  4  5] [ 6  8  1 15]
[10  0  9 11] [ 5  8  2 15] [ 1 13  4 12] [ 7  6  3 14]
[10  0  9 11] [ 8  5  2 15] [ 4 13  1 12] [ 7  3  6 14]
[ 0  9 10 11] [ 8 15  2  5] [ 4  7  6 13] [14 12  1  3]
[10  0  9 11] [ 8  2  5 15] [ 7  6  4 13] [14  3  1 12]
[10  0  9 11] [ 8  5  2 15] [ 4  6  7 13] [14  3  1 12]
[10  0  9 11] [ 7  6  2 15] [ 3 12  1 14] [ 8  4

[ 1  2 12 15] [ 8 11  5  6] [ 3 13  4 10] [14  9  0  7]
[ 2  1 12 15] [ 5 10  7  8] [ 3 14  4  9] [13 11  0  6]
[ 1  2 12 15] [7 9 6 8] [ 5 14  0 11] [13 10  3  4]
[ 2  1 12 15] [6 8 7 9] [ 5 14  0 11] [13 10  3  4]
[14  1  2 13] [10  0  5 15] [ 3  7  9 11] [ 8  4  6 12]
[14  1  2 13] [10  0  5 15] [ 3  9  7 11] [ 6  4  8 12]
[13  1  2 14] [11  0  7 12] [ 3 10  8  9] [ 6  4  5 15]
[14  1  2 13] [ 8  0 10 12] [ 3 11  7  9] [ 4  6  5 15]
[14  1  2 13] [10  0  8 12] [ 3  9  7 11] [ 6  4  5 15]
[ 1  2 13 14] [ 9 11  0 10] [ 4 15  3  8] [12  7  5  6]
[ 1  2 13 14] [10 11  0  9] [ 4 15  3  8] [12  6  5  7]
[ 2  1 13 14] [ 9 10  0 11] [ 4 15  3  8] [12  6  5  7]
[ 2  1 13 14] [ 9 11  0 10] [ 3 15  4  8] [12  6  5  7]
[ 2  1 13 14] [10 11  0  9] [ 3 15  4  8] [12  5  6  7]
[13  1  2 14] [ 9  0 10 11] [ 3  4  8 15] [12  6  5  7]
[13  1  2 14] [10  0  9 11] [ 3  4  8 15] [12  5  6  7]
[14  1  2 13] [ 9  0 10 11] [ 3  8  4 15] [ 7  5  6 12]
[ 2  1 13 14] [ 9 11  0 10] [ 3 15  5  7] [12  6  4  8]


[14  1  3 12] [11  0  9 10] [ 4  7  6 13] [ 8  2  5 15]
[14  1  3 12] [ 2  4  9 15] [ 0  7 10 13] [ 8 11  5  6]
[14  1  3 12] [ 2  4  9 15] [ 0 10  7 13] [ 5 11  6  8]
[14  1  3 12] [ 5  4  6 15] [ 0 13  7 10] [ 2  8  9 11]
[14  1  3 12] [ 6  4  5 15] [ 0 13  8  9] [ 2  7 10 11]
[ 3  1 12 14] [ 5  4  8 13] [ 9 15  0  6] [11 10  2  7]
[ 3  1 12 14] [ 5 13  4  8] [ 0 15  6  9] [11 10  2  7]
[ 3  1 12 14] [ 8  4  5 13] [ 9 15  0  6] [11  7  2 10]
[ 3  1 12 14] [ 8 13  4  5] [ 0 15  6  9] [11  7  2 10]
[ 3  1 12 14] [13  4  5  8] [ 9 15  0  6] [11  2  7 10]
[12  1  3 14] [ 5  4  8 13] [ 0  6  9 15] [11 10  2  7]
[12  1  3 14] [ 5  4  8 13] [ 0 15  6  9] [ 2 10  7 11]
[12  1  3 14] [ 8  4  5 13] [ 0  6  9 15] [11  7  2 10]
[12  1  3 14] [ 8  4  5 13] [ 0 15  6  9] [ 2  7 10 11]
[12  1  3 14] [13  4  5  8] [ 0  6  9 15] [11  2  7 10]
[ 3  1 12 14] [ 8  4  5 13] [ 9 11  0 10] [15  7  2  6]
[ 3  1 12 14] [ 8 13  4  5] [ 0 11  9 10] [15  7  2  6]
[ 3  1 12 14] [13  4  5  8] [ 9 11  0 10] [15  2

[14  1  4 11] [10  5  3 12] [ 0  8  9 13] [ 7  2  6 15]
[14  1  4 11] [10  5  3 12] [ 0  9  8 13] [ 6  2  7 15]
[14  1  4 11] [12  3  5 10] [ 2  6  7 15] [ 9  0  8 13]
[14  1  4 11] [12  3  5 10] [ 2  7  6 15] [ 8  0  9 13]
[14  1  4 11] [12  3  6  9] [ 2  5  8 15] [10  0  7 13]
[14  1  4 11] [12  3  6  9] [ 2  8  5 15] [ 7  0 10 13]
[ 4  1 11 14] [ 8 10  3  9] [ 2 13  0 15] [12  7  5  6]
[ 4  1 11 14] [ 9 10  3  8] [ 2 13  0 15] [12  6  5  7]
[11  1  4 14] [ 8  3  9 10] [ 2 13  0 15] [ 5  7  6 12]
[11  1  4 14] [ 9  3  8 10] [ 2 13  0 15] [ 5  6  7 12]
[11  1  4 14] [10  3  8  9] [ 2  6  7 15] [12  5  0 13]
[ 1  4 11 14] [ 3  8  9 10] [ 7 12  5  6] [13 15  0  2]
[ 1  4 11 14] [ 3  9  8 10] [ 6 12  5  7] [13 15  0  2]
[ 1  4 11 14] [ 3 10  8  9] [ 5 12  6  7] [13 15  0  2]
[ 4  1 11 14] [ 6 12  5  7] [ 0 15  2 13] [10  9  3  8]
[ 4  1 11 14] [ 7 12  5  6] [ 0 15  2 13] [10  8  3  9]
[11  1  4 14] [ 6  5  7 12] [ 0 15  2 13] [ 3  9  8 10]
[11  1  4 14] [ 7  5  6 12] [ 0 15  2 13] [ 3  8

[ 5  1 10 14] [ 9  7  2 12] [ 4 11  0 15] [13  6  3  8]
[ 5  1 10 14] [12  7  2  9] [ 4 11  0 15] [13  3  6  8]
[10  1  5 14] [ 9  2  7 12] [ 4 11  0 15] [ 8  6  3 13]
[10  1  5 14] [12  2  7  9] [ 4 11  0 15] [ 8  3  6 13]
[10  1  5 14] [ 9  2  7 12] [ 4  8  3 15] [11  6  0 13]
[14  1  5 10] [ 3  4 11 12] [ 2  6  7 15] [ 9  8  0 13]
[14  1  5 10] [ 3  4 11 12] [ 2 15  6  7] [ 0  8  9 13]
[14  1  5 10] [11  4  3 12] [ 2  6  7 15] [ 9  0  8 13]
[14  1  5 10] [11  4  3 12] [ 2  7  6 15] [ 8  0  9 13]
[ 1  5 10 14] [ 8  3  6 13] [12  9  2  7] [15 11  0  4]
[ 1  5 10 14] [ 8 13  3  6] [ 2  9  7 12] [15 11  0  4]
[ 1  5 10 14] [ 7  4  6 13] [11  9  2  8] [15 12  0  3]
[ 1  5 10 14] [ 7 13  4  6] [ 2  9  8 11] [15 12  0  3]
[ 1  5 10 14] [ 4  6  8 12] [ 9 11  3  7] [13 15  0  2]
[ 1  5 10 14] [ 4  8  6 12] [ 7 11  3  9] [13 15  0  2]
[ 1  5 10 14] [ 4 12  6  8] [ 3 11  7  9] [13 15  0  2]
[ 1  5 10 14] [ 6  4  8 12] [11  9  3  7] [15 13  0  2]
[ 1  5 10 14] [ 6  8  4 12] [ 7  9  3 11] [15 13

[15  1  6  8] [ 4  7  9 10] [ 0  3 13 14] [11  5  2 12]
[ 1  6  8 15] [ 7  9  4 10] [ 5 12  0 13] [11 14  2  3]
[15  1  6  8] [ 9  4  7 10] [ 3  2 11 14] [12  0  5 13]
[14  1  6  9] [ 0  3 12 15] [ 4  8  5 13] [ 7 10  2 11]
[14  1  6  9] [ 0  3 12 15] [ 4 13  5  8] [ 2 10  7 11]
[ 1  6  9 14] [13  5  0 12] [10 15  2  3] [ 8  7  4 11]
[ 1  6  9 14] [13 12  0  5] [ 3 15  2 10] [ 8  7  4 11]
[ 1  6  9 14] [ 7 12  0 11] [ 3 15  2 10] [ 8 13  4  5]
[ 1  6  9 14] [12  0  7 11] [15 10  2  3] [13  8  4  5]
[ 6  1  9 14] [11  0  7 12] [10 15  2  3] [ 8  4  5 13]
[ 6  1  9 14] [11  7  0 12] [ 3 10  2 15] [13  4  5  8]
[ 6  1  9 14] [11  7  0 12] [ 3 15  2 10] [ 8  4  5 13]
[ 9  1  6 14] [ 3  2 10 15] [ 5 13  4  8] [ 7 12  0 11]
[ 9  1  6 14] [15  2  3 10] [ 5  8  4 13] [12  0  7 11]
[ 9  1  6 14] [15  2  3 10] [ 5 13  4  8] [ 7  0 11 12]
[ 9  1  6 14] [15  3  2 10] [ 4  8  5 13] [12  0  7 11]
[ 9  1  6 14] [15  3  2 10] [ 4 13  5  8] [ 7  0 11 12]
[14  1  6  9] [ 3  2 10 15] [ 5  4  8 13] [11  7

[ 8  1  7 14] [13  5  0 12] [ 3  6 10 11] [15  2  4  9]
[14  1  7  8] [ 0  5 12 13] [ 3 11  6 10] [ 4  9  2 15]
[ 7  1  8 14] [11  6  0 13] [ 3 10  2 15] [12  4  5  9]
[14  1  7  8] [ 0  6 11 13] [ 2  3 10 15] [12  9  4  5]
[14  1  7  8] [ 0  6 11 13] [ 2 10  3 15] [ 5  9  4 12]
[ 1  7  8 14] [ 6 11  0 13] [ 4 12  5  9] [10 15  2  3]
[ 7  1  8 14] [13  0  6 11] [ 9 12  4  5] [10  2  3 15]
[ 1  7  8 14] [10  3  2 15] [12 13  0  5] [ 9 11  4  6]
[ 1  7  8 14] [10 15  2  3] [ 0 13  5 12] [ 9 11  4  6]
[ 1  7  8 14] [15  3  2 10] [12 13  0  5] [ 9  6  4 11]
[ 1  7  8 14] [15 10  2  3] [ 5 13  0 12] [ 9  6  4 11]
[ 7  1  8 14] [10  3  2 15] [ 6 13  0 11] [ 9  5  4 12]
[ 1  7  8 14] [10  3  2 15] [12  9  4  5] [13 11  0  6]
[ 1  7  8 14] [15  3  2 10] [12  9  4  5] [13  6  0 11]
[ 1  7  8 14] [15 10  2  3] [ 5  9  4 12] [13  6  0 11]
[ 7  1  8 14] [10  3  2 15] [ 6  9  4 11] [13  5  0 12]
[ 7  1  8 14] [15  3  2 10] [ 6  9  4 11] [13  0  5 12]
[ 8  1  7 14] [10  2  3 15] [ 6  9  4 11] [12  5

[12  1  7 10] [11  2  8  9] [ 6  4  5 15] [13  0  3 14]
[ 1  7 10 12] [ 8  3  4 15] [14  9  2  5] [13 11  0  6]
[ 1  7 10 12] [ 8 15  3  4] [ 2  9  5 14] [13 11  0  6]
[12  1  7 10] [ 5  8  3 14] [ 0 13  2 15] [ 4  6  9 11]
[12  1  7 10] [ 5  8  3 14] [ 0  4 11 15] [13  6  2  9]
[12  1  7 10] [ 5  8  3 14] [ 0 15  4 11] [ 2  6  9 13]
[12  1  7 10] [ 6  8  3 13] [ 0 15  4 11] [ 2  5  9 14]
[ 1  7 10 12] [ 6 15  4  5] [ 2 14  3 11] [ 8 13  0  9]
[10  1  7 12] [ 4  5  6 15] [ 3 11  2 14] [ 8  9  0 13]
[10  1  7 12] [ 4  6  5 15] [ 2 11  3 14] [ 8  9  0 13]
[ 1  7 10 12] [ 5  6  4 15] [11  9  2  8] [13 14  0  3]
[ 1  7 10 12] [ 5 15  4  6] [ 2  9  8 11] [13 14  0  3]
[ 1  7 10 12] [ 6 15  4  5] [ 2  8  9 11] [14 13  0  3]
[12  1  7 10] [ 8  6  5 11] [ 2 13  0 15] [ 4  3  9 14]
[ 7  1 10 12] [11  8  5  6] [ 3 13  0 14] [ 9  2  4 15]
[12  1  7 10] [ 8  6  5 11] [ 2  4  9 15] [13  3  0 14]
[12  1  7 10] [11  6  5  8] [ 2  4  9 15] [13  0  3 14]
[ 7  1 10 12] [11  8  5  6] [ 3  9  4 14] [13  2

[ 2  3 10 15] [14  6  1  9] [ 7 12  0 11] [13  4  5  8]
[ 3  2 10 15] [ 9  1  6 14] [11 12  0  7] [13  8  4  5]
[15  2  3 10] [12  1  6 11] [ 4  5  7 14] [ 8  0  9 13]
[ 2  3 10 15] [14  7  1  8] [ 6 13  0 11] [12  4  5  9]
[ 3  2 10 15] [ 8  1  7 14] [11 13  0  6] [12  9  4  5]
[ 2  3 10 15] [ 7  8  1 14] [ 5 12  4  9] [13 11  0  6]
[ 2  3 10 15] [13  1  7  9] [12 14  0  4] [11  5  6  8]
[ 2  3 10 15] [13  9  1  7] [ 4 14  0 12] [11  5  6  8]
[10  2  3 15] [ 9  1  7 13] [ 4 12  0 14] [ 6  8  5 11]
[ 3  2 10 15] [13  7  1  9] [ 5 11  6  8] [14  4  0 12]
[ 2  3 10 15] [12  8  1  9] [ 5 14  4  7] [11  6  0 13]
[ 2  3 10 15] [12  9  1  8] [ 4 14  5  7] [11  6  0 13]
[15  2  3 10] [12  1  8  9] [ 4  7  5 14] [ 6  0 11 13]
[10  2  3 15] [12  1  8  9] [ 4  7  6 13] [11  5  0 14]
[ 2  3 10 15] [ 7  4  5 14] [ 9 13  0  8] [12 11  1  6]
[ 2  3 10 15] [ 7  5  4 14] [ 8 13  0  9] [12 11  1  6]
[ 2  3 10 15] [ 7  4  5 14] [ 9 12  1  8] [13 11  0  6]
[ 2  3 10 15] [ 7  5  4 14] [ 8 12  1  9] [13 11

[13  2  3 12] [ 8  4  7 11] [ 1  5  9 15] [10  6  0 14]
[13  2  3 12] [ 8  4  7 11] [ 1 15  5  9] [ 0  6 10 14]
[13  2  3 12] [ 9  4  7 10] [ 1 15  6  8] [ 0  5 11 14]
[15  2  4  9] [ 3  0 13 14] [ 6 12  5  7] [ 1  8 10 11]
[ 2  4  9 15] [13  5  0 12] [ 8 14  1  7] [10  6  3 11]
[ 2  4  9 15] [13 12  0  5] [ 1 14  7  8] [10  6  3 11]
[15  2  4  9] [ 0  5 12 13] [ 1  7  8 14] [ 6 11  3 10]
[ 2  4  9 15] [12  5  0 13] [ 8 10  1 11] [14  7  3  6]
[ 2  4  9 15] [13  5  0 12] [ 8 10  1 11] [14  6  3  7]
[ 2  4  9 15] [13 12  0  5] [ 1 10  8 11] [14  6  3  7]
[ 2  4  9 15] [11  6  0 13] [ 7 10  1 12] [14  8  3  5]
[ 2  4  9 15] [11  0  7 12] [13 10  1  6] [14  8  3  5]
[ 2  4  9 15] [11  7  0 12] [ 6 10  1 13] [14  8  3  5]
[ 2  4  9 15] [11 12  0  7] [ 1 10  6 13] [14  8  3  5]
[ 2  4  9 15] [14  3  1 12] [10 13  0  7] [11  5  6  8]
[ 4  2  9 15] [12  1  3 14] [10 13  0  7] [11  5  6  8]
[ 4  2  9 15] [10  5  1 14] [ 6 13  3  8] [11  7  0 12]
[ 2  4  9 15] [13  1  5 11] [12 10  0  8] [14  6

[ 4  2 11 13] [ 7  3  6 14] [10 15  0  5] [ 9  8  1 12]
[ 4  2 11 13] [14  3  6  7] [10 15  0  5] [ 9  1  8 12]
[11  2  4 13] [ 7  6  3 14] [ 0  5 10 15] [12  8  1  9]
[11  2  4 13] [14  6  3  7] [ 0  5 10 15] [12  1  8  9]
[11  2  4 13] [14  6  3  7] [ 0  8 10 12] [ 9  1  5 15]
[11  2  4 13] [14  6  3  7] [ 0 12  8 10] [ 5  1  9 15]
[ 2  4 11 13] [ 7  3  6 14] [12  9  1  8] [15 10  0  5]
[ 2  4 11 13] [ 7 14  3  6] [ 1  9  8 12] [15 10  0  5]
[ 4  2 11 13] [ 5 12  6  7] [ 1 15  0 14] [ 9 10  3  8]
[ 4  2 11 13] [ 6 12  5  7] [ 1 14  0 15] [10  9  3  8]
[ 4  2 11 13] [ 7 12  5  6] [ 1 14  0 15] [10  8  3  9]
[ 4  2 11 13] [ 7 12  5  6] [ 1 15  0 14] [ 9  8  3 10]
[11  2  4 13] [ 5  6  7 12] [ 0 14  1 15] [ 3 10  8  9]
[11  2  4 13] [ 6  5  7 12] [ 1 14  0 15] [ 3  9  8 10]
[11  2  4 13] [ 7  5  6 12] [ 1 14  0 15] [ 3  8  9 10]
[11  2  4 13] [ 7  6  5 12] [ 0 14  1 15] [ 3  8  9 10]
[ 2  5  8 15] [14  3  0 13] [10 12  1  7] [11  6  4  9]
[ 5  2  8 15] [13  0  3 14] [10 12  1  7] [11  4

[ 2  5 10 13] [ 3  6  7 14] [ 9 12  1  8] [11 15  0  4]
[ 2  5 10 13] [ 3  7  6 14] [ 8 12  1  9] [11 15  0  4]
[ 2  5 10 13] [ 3 14  6  7] [ 1 12  8  9] [11 15  0  4]
[ 2  5 10 13] [ 7  3  6 14] [12  8  1  9] [15 11  0  4]
[ 2  5 10 13] [ 7  6  3 14] [ 9  8  1 12] [15 11  0  4]
[ 2  5 10 13] [ 7 14  3  6] [ 1  8  9 12] [15 11  0  4]
[ 2  5 10 13] [14  3  6  7] [12  8  1  9] [15  4  0 11]
[ 2  5 10 13] [14  6  3  7] [ 9  8  1 12] [15  4  0 11]
[ 2  5 10 13] [14  6  3  7] [ 9 12  1  8] [11  4  0 15]
[ 2  5 10 13] [14  7  3  6] [ 8 12  1  9] [11  4  0 15]
[ 5  2 10 13] [ 3 11  7  9] [ 1 15  0 14] [ 8 12  4  6]
[ 5  2 10 13] [ 9 11  3  7] [ 1 15  0 14] [ 8  6  4 12]
[10  2  5 13] [ 3  7  9 11] [ 0 14  1 15] [ 4 12  6  8]
[10  2  5 13] [ 9  7  3 11] [ 0 14  1 15] [ 4  6  8 12]
[10  2  5 13] [ 7  3  9 11] [ 4 12  0 14] [ 6  8  1 15]
[13  2  5 10] [11  3  7  9] [ 4  0 12 14] [15  1  6  8]
[ 5  2 10 13] [ 4 12  6  8] [ 0 14  1 15] [ 9 11  3  7]
[ 5  2 10 13] [ 8 12  4  6] [ 0 14  1 15] [ 9  7

[ 2  6  8 14] [ 9  4  5 12] [10  7  0 13] [15 11  1  3]
[ 8  2  6 14] [ 4  7  9 10] [ 1 15  3 11] [ 5 12  0 13]
[ 8  2  6 14] [ 4  7  9 10] [ 1  5 11 13] [15 12  0  3]
[14  2  6  8] [10  7  4  9] [ 1 11  5 13] [ 3  0 12 15]
[13  2  6  9] [ 0  3 12 15] [ 5  7  4 14] [ 8 11  1 10]
[13  2  6  9] [ 0  3 12 15] [ 5 14  4  7] [ 1 11  8 10]
[13  2  6  9] [ 4  0 11 15] [ 8  3  5 14] [12  7  1 10]
[13  2  6  9] [ 4  0 11 15] [ 8  5  3 14] [10  7  1 12]
[13  2  6  9] [ 4  0 11 15] [ 8 14  3  5] [ 1  7 10 12]
[ 2  6  9 13] [14  4  0 12] [11 15  1  3] [ 7  5  8 10]
[ 2  6  9 13] [14 12  0  4] [ 3 15  1 11] [ 7  5  8 10]
[13  2  6  9] [ 4  0 12 14] [ 8 10  1 11] [ 5  7  3 15]
[ 2  6  9 13] [11  0  5 14] [15 10  1  4] [12  8  3  7]
[ 2  6  9 13] [11  5  0 14] [10 15  1  4] [ 7  8  3 12]
[ 2  6  9 13] [11 14  0  5] [ 1 10  4 15] [12  8  3  7]
[ 2  6  9 13] [11 14  0  5] [ 1 15  4 10] [ 7  8  3 12]
[ 2  6  9 13] [11  5  0 14] [10  7  1 12] [15  8  3  4]
[ 2  6  9 13] [11 14  0  5] [ 1  7 10 12] [15  8

[ 2  6 10 12] [ 3 11  7  9] [ 5  8  4 13] [14 15  0  1]
[12  2  6 10] [ 4  7  5 14] [ 1  3 11 15] [13  8  0  9]
[10  2  6 12] [ 5  8  4 13] [ 0 15  1 14] [ 3  9  7 11]
[10  2  6 12] [13  8  4  5] [ 0  7  9 14] [11  1  3 15]
[ 2  6 10 12] [ 4  5  8 13] [11 15  1  3] [ 7 14  0  9]
[ 2  6 10 12] [ 4 13  5  8] [ 3 15  1 11] [ 7 14  0  9]
[ 2  6 10 12] [ 4  5  8 13] [11  7  3  9] [15 14  0  1]
[ 2  6 10 12] [ 4 13  5  8] [ 3  7  9 11] [15 14  0  1]
[ 2  6 10 12] [ 4 11  7  8] [ 5  9  1 15] [13 14  0  3]
[ 6  2 10 12] [11  7  4  8] [ 5  9  1 15] [13  3  0 14]
[10  2  6 12] [11  7  4  8] [ 1  5  9 15] [13  3  0 14]
[ 2  7  8 13] [14  0  4 12] [15 11  1  3] [10  6  5  9]
[ 2  7  8 13] [14 12  0  4] [ 3 11  1 15] [10  6  5  9]
[ 8  2  7 13] [12  4  0 14] [ 5  9  1 15] [11  3  6 10]
[13  2  7  8] [ 0  4 12 14] [ 5  9  1 15] [ 6 10  3 11]
[13  2  7  8] [ 4  0 12 14] [ 9  5  1 15] [10  6  3 11]
[ 7  2  8 13] [14  0  4 12] [10  6  3 11] [15  1  5  9]
[ 7  2  8 13] [ 0  4 12 14] [ 6 10  5  9] [11 15

[10  2  7 11] [ 1  6  8 15] [ 3 13  0 14] [ 5 12  4  9]
[10  2  7 11] [ 1  6  8 15] [ 3 14  0 13] [ 4 12  5  9]
[10  2  7 11] [ 8  6  1 15] [ 3 14  0 13] [ 4  5  9 12]
[11  2  7 10] [ 8  6  1 15] [ 3  5  9 13] [12  4  0 14]
[ 2  7 10 11] [ 6 14  1  9] [ 3  8  4 15] [13 12  0  5]
[ 7  2 10 11] [ 1  9  6 14] [ 3  8  4 15] [13 12  0  5]
[11  2  7 10] [ 9  1  6 14] [ 8  5  4 13] [12  3  0 15]
[10  2  7 11] [ 8  9  1 12] [ 0  3 13 14] [15  5  4  6]
[10  2  7 11] [ 8  9  1 12] [ 0 14  3 13] [ 4  5  6 15]
[10  2  7 11] [ 5  9  3 13] [ 0 14  1 15] [ 4  8  6 12]
[10  2  7 11] [ 5  9  3 13] [ 0 12  4 14] [ 6  8  1 15]
[10  2  7 11] [13  3  5  9] [ 6  4  8 12] [14  0  1 15]
[ 2  7 10 11] [ 3 13  6  8] [ 4 12  0 14] [ 9 15  1  5]
[ 2  7 10 11] [13  3  6  8] [14 12  0  4] [ 9  5  1 15]
[ 2  7 10 11] [15  4  5  6] [13  9  0  8] [12  3  1 14]
[ 2  7 10 11] [ 4  5  6 15] [12  8  1  9] [13 14  0  3]
[ 2  7 10 11] [15  5  4  6] [12  8  1  9] [13  3  0 14]
[10  2  7 11] [ 4  8  5 13] [ 1 15  0 14] [ 3  9

[ 4  3  9 14] [12 10  1  7] [ 2 15  0 13] [ 8  5  6 11]
[14  3  4  9] [ 7  1 10 12] [ 6 11  0 13] [ 2  5  8 15]
[14  3  4  9] [12  1  7 10] [ 6 11  5  8] [ 2  0 13 15]
[ 4  3  9 14] [ 6  7  2 15] [ 5 13  0 12] [10 11  1  8]
[14  3  4  9] [ 2  7  6 15] [ 0  5 12 13] [ 8 10  1 11]
[14  3  4  9] [ 2  7  6 15] [ 0 12  5 13] [ 1 10  8 11]
[ 3  4  9 14] [ 6  2  7 15] [11 13  1  5] [10 12  0  8]
[14  3  4  9] [ 2  6  7 15] [ 1  5 11 13] [ 8 10  0 12]
[14  3  4  9] [ 2  6  7 15] [ 1 13  5 11] [ 0 10  8 12]
[ 3  4  9 14] [ 6  2  7 15] [11 10  1  8] [13 12  0  5]
[ 9  3  4 14] [ 2  6 10 12] [ 1 11  5 13] [ 7 15  0  8]
[14  3  4  9] [12  6  2 10] [ 1  5 11 13] [ 8  0  7 15]
[ 9  3  4 14] [ 2  7 10 11] [ 0 12  5 13] [ 6 15  1  8]
[14  3  4  9] [11  7  2 10] [ 0  5 12 13] [ 8  1  6 15]
[ 4  3  9 14] [ 6 12  5  7] [ 0 13  2 15] [10 11  1  8]
[ 4  3  9 14] [ 6 12  5  7] [ 0 15  2 13] [ 8 11  1 10]
[ 4  3  9 14] [ 7 12  5  6] [ 0 15  2 13] [ 8 10  1 11]
[ 3  4  9 14] [ 5 12  6  7] [ 1  8 10 11] [15 13

[ 8  3  5 14] [13  6  0 11] [ 2  9  7 12] [10  4  1 15]
[ 8  3  5 14] [11  7  0 12] [ 1 10  4 15] [ 9  6  2 13]
[ 5  3  8 14] [11  7  0 12] [ 4  9  2 15] [13  6  1 10]
[ 5  3  8 14] [11  9  0 10] [ 2 15  1 12] [ 7  6  4 13]
[ 5  3  8 14] [11 10  0  9] [ 1 15  2 12] [ 7  6  4 13]
[ 3  5  8 14] [12  2  1 15] [11 13  0  6] [ 9  7  4 10]
[ 3  5  8 14] [15  2  1 12] [11 13  0  6] [ 9  4  7 10]
[ 3  5  8 14] [12  2  1 15] [11  9  0 10] [13  7  4  6]
[ 3  5  8 14] [15  2  1 12] [11  9  0 10] [13  4  6  7]
[14  3  5  8] [ 1  2 12 15] [ 6  4  7 13] [ 9 10  0 11]
[14  3  5  8] [ 1  2 12 15] [ 6 13  4  7] [ 0 10  9 11]
[14  3  5  8] [ 2  1 12 15] [ 7 13  4  6] [ 0  9 10 11]
[ 3  5  8 14] [12  2  1 15] [11  9  4  6] [13  7  0 10]
[ 3  5  8 14] [10 13  1  6] [ 0 15  4 11] [ 7  9  2 12]
[ 3  5  8 14] [10  1  6 13] [12  7  0 11] [15  9  2  4]
[ 3  5  8 14] [10 13  1  6] [ 0  7 11 12] [15  9  2  4]
[ 3  5  8 14] [12 11  1  6] [ 2 13  0 15] [ 9  7  4 10]
[ 3  5  8 14] [ 6 11  1 12] [ 2 15  4  9] [ 7 13

[ 5  3 10 12] [ 4 13  6  7] [ 0 14  1 15] [ 8 11  2  9]
[ 5  3 10 12] [ 6 13  4  7] [ 0 14  1 15] [ 8  9  2 11]
[10  3  5 12] [ 4  7  6 13] [ 1 15  0 14] [ 2 11  8  9]
[10  3  5 12] [ 6  7  4 13] [ 1 15  0 14] [ 2  9  8 11]
[14  3  6  7] [ 2  0 13 15] [ 9 12  4  5] [ 1  8 10 11]
[ 3  6  7 14] [15  4  0 11] [ 9  8  1 12] [13  5  2 10]
[ 7  3  6 14] [15  5  0 10] [ 4 12  1 13] [ 8  2  9 11]
[14  3  6  7] [ 0  5 12 13] [ 4  2  9 15] [11 10  1  8]
[ 7  3  6 14] [13  8  0  9] [ 1 15  2 12] [ 5  4 10 11]
[14  3  6  7] [ 0  8  9 13] [ 1  2 12 15] [11 10  4  5]
[ 3  6  7 14] [ 8  9  0 13] [ 4 10  1 15] [11 12  2  5]
[ 6  3  7 14] [13  8  0  9] [ 2 11  5 12] [10  4  1 15]
[ 7  3  6 14] [12  1  2 15] [ 8  9  0 13] [11  5  4 10]
[ 6  3  7 14] [15 10  1  4] [ 0 12  5 13] [ 9  2  8 11]
[ 6  3  7 14] [15 10  1  4] [ 0 13  5 12] [ 8  2  9 11]
[ 7  3  6 14] [15  4  1 10] [ 5 12  0 13] [ 8  2  9 11]
[ 6  3  7 14] [15 10  1  4] [ 0  9  8 13] [12  2  5 11]
[ 7  3  6 14] [15  1  4 10] [ 8  9  0 13] [11  2

[ 3  6 10 11] [ 5 14  4  7] [ 2 13  0 15] [ 8 12  1  9]
[11  3  6 10] [ 4  7  5 14] [ 2 15  0 13] [ 1  9  8 12]
[11  3  6 10] [ 5  7  4 14] [ 2 15  0 13] [ 1  8  9 12]
[ 3  6 10 11] [ 4 14  5  7] [ 2 12  1 15] [ 9 13  0  8]
[ 6  3 10 11] [14  4  5  7] [ 9  8  1 12] [13  0  2 15]
[ 6  3 10 11] [ 5 13  4  8] [ 0 14  1 15] [ 7  9  2 12]
[10  3  6 11] [ 5  8  4 13] [ 1 15  0 14] [ 2  9  7 12]
[11  3  6 10] [ 4  8  5 13] [ 1 14  0 15] [ 2  9  7 12]
[11  3  6 10] [ 4  8  5 13] [ 1  2 12 15] [14  9  0  7]
[11  3  6 10] [13  8  4  5] [ 1  2 12 15] [14  0  7  9]
[ 6  3 10 11] [13  4  5  8] [ 9  7  2 12] [14  1  0 15]
[11  3  6 10] [ 5  9  4 12] [ 0 14  1 15] [ 2  8  7 13]
[11  3  6 10] [ 5  9  4 12] [ 0  2 13 15] [14  8  1  7]
[11  3  6 10] [ 5  9  4 12] [ 0 15  2 13] [ 1  8  7 14]
[11  3  6 10] [12  9  4  5] [ 0  2 13 15] [14  1  7  8]
[ 6  3 10 11] [12  5  4  9] [ 8  7  0 15] [14  2  1 13]
[12  3  7  8] [ 0  6  9 15] [ 4  2 10 14] [13 11  1  5]
[12  3  7  8] [ 0  6  9 15] [ 4 10  2 14] [ 5 11

[ 8  3  9 10] [11  0  4 15] [12  5  6  7] [14  2  1 13]
[ 8  3  9 10] [11  0  4 15] [12  6  5  7] [13  2  1 14]
[ 9  3  8 10] [11  4  0 15] [ 7  5  6 12] [13  2  1 14]
[ 3  8  9 10] [11  5  0 14] [12 15  1  2] [ 4  7  6 13]
[ 8  3  9 10] [ 0 11  5 14] [ 1 12  2 15] [ 7 13  4  6]
[ 8  3  9 10] [ 0 11  5 14] [ 1 15  2 12] [ 4 13  6  7]
[ 3  8  9 10] [11  5  0 14] [12  4  1 13] [15  7  2  6]
[ 3  8  9 10] [11  5  0 14] [12 13  1  4] [ 6  7  2 15]
[ 8  3  9 10] [11  0  5 14] [12  4  1 13] [15  2  6  7]
[ 8  3  9 10] [11  0  5 14] [12 13  1  4] [ 6  2  7 15]
[ 3  8  9 10] [ 5 11  0 14] [ 6  7  2 15] [12 13  1  4]
[ 3  8  9 10] [ 5 11  0 14] [ 6 15  2  7] [ 4 13  1 12]
[ 3  8  9 10] [14 11  0  5] [ 6  7  2 15] [12  4  1 13]
[ 8  3  9 10] [ 0  5 11 14] [ 7 15  2  6] [ 4 13  1 12]
[ 8  3  9 10] [11  5  0 14] [ 7  4  6 13] [15  2  1 12]
[ 8  3  9 10] [12  5  0 13] [ 7 15  2  6] [ 4  1 11 14]
[ 9  3  8 10] [12  5  0 13] [ 6  7  2 15] [11  1  4 14]
[ 8  3  9 10] [ 6  0 11 13] [12 15  1  2] [ 4  7

[14  4  5  7] [11  1  6 12] [ 8 10  3  9] [ 2  0 13 15]
[14  4  5  7] [11  6  1 12] [ 3 10  8  9] [ 2  0 13 15]
[ 4  5  7 14] [ 8 12  1  9] [ 0 15  2 13] [ 6 11  3 10]
[ 4  5  7 14] [ 9 12  1  8] [ 0 15  2 13] [ 6 10  3 11]
[ 5  4  7 14] [ 8  9  1 12] [ 2 15  0 13] [ 6 10  3 11]
[ 7  4  5 14] [ 8  9  1 12] [ 0 13  2 15] [ 6 10  3 11]
[14  4  5  7] [ 8  9  1 12] [ 0  2 13 15] [10  3  6 11]
[ 4  5  7 14] [ 9  1  8 12] [11  6  0 13] [15 10  2  3]
[ 4  5  7 14] [ 9 12  1  8] [ 0  6 11 13] [15 10  2  3]
[ 4  5  7 14] [ 8  9  1 12] [ 3 15  2 10] [ 6 11  0 13]
[ 5  4  7 14] [12  8  1  9] [ 3 10  2 15] [11  6  0 13]
[ 5  4  7 14] [12  9  1  8] [ 2 10  3 15] [11  6  0 13]
[14  4  5  7] [ 2  3 10 15] [ 6  0 11 13] [12  9  1  8]
[14  4  5  7] [ 2  3 10 15] [ 6 11  0 13] [ 1  9  8 12]
[14  4  5  7] [10  3  2 15] [ 6  0 11 13] [12  1  8  9]
[14  4  5  7] [ 2  3 10 15] [ 6 12  1 11] [ 0  9  8 13]
[14  4  5  7] [ 2  3 12 13] [ 6  1  8 15] [11  9  0 10]
[ 5  4  7 14] [ 8 11  2  9] [ 0 15  3 12] [ 6 10

[ 5  4  9 12] [ 2 10  7 11] [ 3  6  8 13] [15 14  0  1]
[ 4  5  9 12] [ 6 14  3  7] [ 0 13  2 15] [ 8 11  1 10]
[ 4  5  9 12] [ 7 14  3  6] [ 0 13  2 15] [ 8 10  1 11]
[12  4  5  9] [ 3  7  6 14] [ 2 13  0 15] [ 1 10  8 11]
[ 5  4  9 12] [14  3  6  7] [10  8  1 11] [13  2  0 15]
[ 4  5  9 12] [ 6 13  3  8] [ 1 14  0 15] [ 7 11  2 10]
[ 5  4  9 12] [ 6 13  3  8] [ 0 14  1 15] [ 7 10  2 11]
[ 9  4  5 12] [ 6  8  3 13] [ 1 15  0 14] [ 2 10  7 11]
[11  4  5 10] [ 1  0 14 15] [ 9  7  2 12] [ 8 13  3  6]
[11  4  5 10] [ 1  0 14 15] [ 9 12  2  7] [ 3 13  6  8]
[11  4  5 10] [13  2  0 15] [ 7  3  6 14] [12  1  8  9]
[11  4  5 10] [13  2  0 15] [ 7  6  3 14] [ 9  1  8 12]
[11  4  5 10] [12  0  3 15] [ 9  1  7 13] [14  2  6  8]
[11  4  5 10] [12  0  3 15] [ 9  7  1 13] [ 8  2  6 14]
[10  4  5 11] [13  0  3 14] [ 9  1  8 12] [15  2  6  7]
[10  4  5 11] [14  3  0 13] [ 6  7  2 15] [ 9  1  8 12]
[11  4  5 10] [13  3  0 14] [ 6  7  2 15] [ 8  1  9 12]
[11  4  5 10] [13  0  3 14] [ 9  7  2 12] [ 8  1

[ 8  4  6 12] [13  1  2 14] [ 9 11  0 10] [ 7  3  5 15]
[ 6  4  8 12] [11  3  1 15] [ 9  7  0 14] [13  5  2 10]
[ 6  4  8 12] [ 5  9  1 15] [ 3 13  0 14] [ 7 11  2 10]
[ 6  4  8 12] [ 5 10  1 14] [ 2 13  0 15] [ 7 11  3  9]
[ 8  4  6 12] [ 5 10  1 14] [ 0 15  2 13] [ 3 11  7  9]
[ 6  4  8 12] [14  1  5 10] [11  7  3  9] [13  2  0 15]
[ 8  4  6 12] [14  1  5 10] [ 9  3  7 11] [15  2  0 13]
[ 6  4  8 12] [13  1  7  9] [11  5  0 14] [15  3  2 10]
[ 8  4  6 12] [ 3 10  2 15] [ 0 11  5 14] [ 7 13  1  9]
[ 8  4  6 12] [15 10  2  3] [ 0  5 11 14] [13  1  7  9]
[ 8  4  6 12] [15 10  2  3] [ 0 11  5 14] [ 7  1  9 13]
[ 6  4  8 12] [15  3  2 10] [ 9  7  0 14] [13  1  5 11]
[ 8  4  6 12] [ 3 10  2 15] [ 0  7  9 14] [11 13  1  5]
[ 8  4  6 12] [15 10  2  3] [ 0  7  9 14] [11  1  5 13]
[ 8  4  6 12] [ 2  3 10 15] [ 7 13  1  9] [ 5 14  0 11]
[12  4  6  8] [ 2  3 11 14] [ 7  9  1 13] [ 5 10  0 15]
[ 8  4  6 12] [ 5 10  2 13] [ 0 15  1 14] [ 3 11  7  9]
[ 6  4  8 12] [13  5  2 10] [ 7  9  0 14] [11  3

[ 7  4  9 10] [13  2  0 15] [11  5  6  8] [14  1  3 12]
[ 9  4  7 10] [13  0  2 15] [11  5  6  8] [12  1  3 14]
[ 4  7  9 10] [12 15  0  3] [ 1 13  2 14] [ 6  5  8 11]
[ 7  4  9 10] [ 3  0 12 15] [13 14  1  2] [ 5 11  6  8]
[ 7  4  9 10] [ 3 12  0 15] [ 1 13  2 14] [ 6 11  5  8]
[ 7  4  9 10] [ 3 12  0 15] [ 1 14  2 13] [ 5 11  6  8]
[ 4  7  9 10] [ 3 15  0 12] [ 1 11  5 13] [ 8 14  2  6]
[ 4  7  9 10] [ 3 15  0 12] [ 1 13  5 11] [ 6 14  2  8]
[ 4  7  9 10] [15  3  0 12] [13  5  1 11] [14  2  6  8]
[ 4  7  9 10] [15  3  0 12] [13 11  1  5] [ 8  2  6 14]
[ 7  4  9 10] [ 0 12  3 15] [ 1 11  5 13] [ 8 14  2  6]
[ 7  4  9 10] [ 0 12  3 15] [ 1 13  5 11] [ 6 14  2  8]
[ 7  4  9 10] [12  0  3 15] [13  5  1 11] [14  2  6  8]
[ 7  4  9 10] [12  0  3 15] [13 11  1  5] [ 8  2  6 14]
[ 9  4  7 10] [13  3  0 14] [ 8  5  2 15] [12  1  6 11]
[ 9  4  7 10] [13  0  3 14] [11  2  5 12] [15  1  6  8]
[ 9  4  7 10] [13  0  3 14] [11  5  6  8] [12  1  2 15]
[ 9  4  7 10] [13  3  0 14] [ 8  5  6 11] [12  1

[ 5  6  8 11] [ 4 14  2 10] [ 0 12  3 15] [ 7 13  1  9]
[11  5  6  8] [ 3  9  4 14] [ 2 13  0 15] [ 1 10  7 12]
[ 6  5  8 11] [14  3  4  9] [10  7  0 13] [12  2  1 15]
[11  5  6  8] [ 3  9  4 14] [ 2  1 12 15] [13 10  0  7]
[ 8  5  6 11] [ 4 10  3 13] [ 1 15  0 14] [ 2 12  7  9]
[ 5  6  8 11] [ 3 13  4 10] [ 1 12  2 15] [ 7 14  0  9]
[ 8  5  6 11] [ 4 10  7  9] [ 1 14  0 15] [ 3 12  2 13]
[ 8  5  6 11] [ 4 10  7  9] [ 1 15  0 14] [ 2 12  3 13]
[11  5  6  8] [10  9  4  7] [ 2  0 13 15] [14  3  1 12]
[11  5  6  8] [10  9  4  7] [ 2 13  0 15] [ 1  3 12 14]
[11  5  6  8] [10  9  4  7] [ 2  1 12 15] [13  3  0 14]
[ 8  5  6 11] [ 4  9  7 10] [ 2 14  1 13] [ 3 12  0 15]
[ 8  5  6 11] [ 4 10  7  9] [ 1  2 13 14] [15 12  0  3]
[ 8  5  6 11] [ 4 10  7  9] [ 1 14  2 13] [ 3 12  0 15]
[11  5  6  8] [10  9  4  7] [ 2 14  1 13] [ 0  3 12 15]
[ 6  5  9 10] [ 0  3 13 14] [11  7  4  8] [12 15  1  2]
[ 6  5  9 10] [13  3  0 14] [11  4  7  8] [15  2  1 12]
[ 6  5  9 10] [13  3  0 14] [11  7  4  8] [12  2

[6 7 8 9] [ 3  1 11 15] [14 12  0  4] [ 5 13  2 10]
[6 7 8 9] [ 3 11  1 15] [ 4 12  0 14] [ 5 13  2 10]
[6 7 8 9] [ 3 15  1 11] [ 0 12  4 14] [ 5 13  2 10]
[6 7 8 9] [11  1  3 15] [14  4  0 12] [13  5  2 10]
[6 7 8 9] [11  3  1 15] [12  4  0 14] [13  5  2 10]
[6 7 8 9] [11 15  1  3] [ 0  4 12 14] [13  5  2 10]
[6 7 8 9] [11  1  3 15] [14  4  2 10] [13  5  0 12]
[8 6 7 9] [15  3  1 11] [10  4  2 14] [12  0  5 13]
[8 6 7 9] [15 11  1  3] [ 2  4 10 14] [12  0  5 13]
[9 6 7 8] [ 1 11  3 15] [ 2 10  4 14] [ 5 13  0 12]
[7 6 8 9] [11  1  3 15] [13  5  2 10] [12  4  0 14]
[7 6 8 9] [15  1  3 11] [13  5  2 10] [12  0  4 14]
[8 6 7 9] [11  3  1 15] [10  2  5 13] [14  4  0 12]
[8 6 7 9] [15  3  1 11] [10  2  5 13] [14  0  4 12]
[8 6 7 9] [ 4 10  1 15] [ 3 14  0 13] [ 2 11  5 12]
[6 7 8 9] [ 4 10  1 15] [ 5 14  0 11] [ 3 12  2 13]
[6 7 8 9] [ 4 15  1 10] [ 0 14  5 11] [ 3 12  2 13]
[8 6 7 9] [ 4  1 10 15] [12 13  0  5] [ 3 11  2 14]
[8 6 7 9] [15 10  1  4] [ 3 11  2 14] [ 5  0 12 13]
[7 6 8 9] [ 

In [75]:
AAAA[i,0:4][permute4[j]]

array([ 0,  1, 14, 15])

In [74]:
j=0